/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách tài khoản, mới tạo trước
         * @description Tầng 2: **bất kỳ một** trong `user.lock`, `user.unlock`, `role.assign` (policy any-of, Mục 6.1) — người chỉ có
         *     `role.assign` cũng phải xem được danh sách để chọn người gán vai trò. `ADMIN` qua mọi mã (lối tắt tầng 2).
         *
         *     Sắp `created_at DESC`, hòa thì `user_id DESC`. Cursor opaque — FE chỉ chuyển tiếp `nextCursor`, không tự dựng.
         *     Hết dữ liệu khi `nextCursor` là `null`, không suy từ độ dài `items`.
         *
         *     Bộ lọc kết hợp bằng AND. `roleCode` đúng dạng mà không tồn tại → trang rỗng, không 400 (vai trò là dữ liệu từ GĐ6).
         */
        get: operations["listAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Một tài khoản
         * @description Cùng tầng 2 với danh sách. `userId` là **đích**; người thao tác luôn là chủ token. Không tồn tại → **404** — endpoint
         *     đặc quyền nên 404 không lộ gì cho người ngoài (tầng 2 đã chặn họ).
         */
        get: operations["getAdminUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 7807 Problem Details — dạng lỗi duy nhất của toàn dự án. Sinh bởi
         *     `SocialApp.SharedKernel.Errors.GlobalExceptionHandler`; `traceId` và `type` gắn thống nhất
         *     trong `AddSharedKernel`.
         */
        ProblemDetails: {
            /**
             * Format: uri
             * @description Mặc định `https://httpstatuses.io/{status}`; ca FE phải phân nhánh thì là một URN ổn định.
             */
            type?: string;
            /** @description Nhãn ngắn, ổn định theo loại lỗi. **Không** chứa dữ liệu người dùng. */
            title: string;
            /** Format: int32 */
            status: number;
            /** @description Thông điệp cho người đọc. Vắng mặt ở lỗi 500. */
            detail?: string | null;
            /** @description Path của request gây lỗi. */
            instance?: string;
            /** @description Bằng header `X-Correlation-ID` của chính request đó — dùng để tra log. */
            traceId: string;
            /** @description Chỉ có ở lỗi validation (400). Map `tên trường → danh sách thông điệp`. */
            errors?: {
                [key: string]: string[];
            } | null;
        };
        /** @description 503 fail-closed của endpoint quản trị (Đ-6.8). Cùng hình dạng `ProblemDetails`, `type` cố định. */
        RevocationUnavailableProblem: components["schemas"]["ProblemDetails"] & {
            /** @enum {string} */
            type: "urn:socialapp:problem:revocation-unavailable";
        };
        /**
         * @description `roles.code` — bất biến, cùng định nghĩa `RoleCode` của `identity-v1`. Ba vai trò hệ thống luôn có: `USER`,
         *     `MODERATOR`, `ADMIN`; từ GĐ6 Admin tạo được vai trò mới nên đây là chuỗi mở.
         * @example USER
         */
        RoleCode: string;
        /**
         * @description Khớp `CONSTRAINT ck_users_status` — cùng bốn giá trị với `UserStatus` của `identity-v1` (quyết định 5 của GĐ1: giữ đủ
         *     bốn để GĐ6/GĐ8 không mở lại hợp đồng). `disabled` = bị Admin khóa (Đ-6.5). `locked` không ai ghi; `deleted` chờ GĐ8.
         *     Khóa tạm do đăng nhập sai (FR-003) **không** ở đây mà ở `lockedUntil`.
         * @enum {string}
         */
        UserStatus: "active" | "locked" | "disabled" | "deleted";
        AdminUser: {
            /** Format: uuid */
            userId: string;
            /**
             * Format: email
             * @description PII (Mục 8.2) — chỉ có ở nhóm `admin-v1`.
             */
            email: string;
            /** @description Tên hiển thị từ hồ sơ. `null` khi người này chưa tạo hồ sơ (onboarding). */
            displayName: string | null;
            roleCode: components["schemas"]["RoleCode"];
            /**
             * @description Tên vai trò cho người đọc (`roles.display_name`) — không dùng để so sánh logic.
             * @example Người dùng
             */
            roleDisplayName: string;
            status: components["schemas"]["UserStatus"];
            emailVerified: boolean;
            /**
             * Format: date-time
             * @description Khóa **tạm** do đăng nhập sai nhiều lần (FR-003) — khác `status = disabled` của Admin. Chỉ có giá trị khi mốc còn ở
             *     tương lai; mốc đã qua (tài khoản đã tự mở) trả `null`.
             */
            lockedUntil: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        AdminUserPage: {
            /** @description Sắp `created_at DESC`, hòa thì `user_id DESC`. */
            items: components["schemas"]["AdminUser"][];
            /** @description Opaque. `null` khi hết dữ liệu — không phải chuỗi rỗng. */
            nextCursor: string | null;
        };
    };
    responses: {
        /**
         * @description Dữ liệu đầu vào không hợp lệ. `errors` là map `tên trường → danh sách thông điệp`: `cursor` rác, `limit` ngoài
         *     `1..50`, `q` quá dài, `status`/`roleCode` sai dạng, `userId` không phải UUID.
         */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/400",
                 *       "title": "Dữ liệu không hợp lệ",
                 *       "status": 400,
                 *       "detail": "Dữ liệu đầu vào không hợp lệ",
                 *       "instance": "/api/v1/admin/users",
                 *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8",
                 *       "errors": {
                 *         "status": [
                 *           "Trạng thái chỉ nhận active hoặc disabled."
                 *         ]
                 *       }
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Thiếu access token, token sai chữ ký, hết hạn, hoặc đã bị thu hồi. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/401",
                 *       "title": "Chưa xác thực",
                 *       "status": 401,
                 *       "detail": "Yêu cầu access token hợp lệ.",
                 *       "instance": "/api/v1/admin/users",
                 *       "traceId": "a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Tầng 2 từ chối — vai trò không có mã quyền nào endpoint đòi (dòng `TC-A05` của AuthZ matrix). Để lại một dòng
         *     `access.denied` trong nhật ký kiểm toán (Đ-6.15). Thông điệp không nêu quyền còn thiếu.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/403",
                 *       "title": "Bị từ chối",
                 *       "status": 403,
                 *       "detail": "Bạn không có quyền thực hiện thao tác này.",
                 *       "instance": "/api/v1/admin/users",
                 *       "traceId": "c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Tài khoản không tồn tại. */
        UserNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/404",
                 *       "title": "Không tìm thấy tài nguyên",
                 *       "status": 404,
                 *       "detail": "Không tìm thấy tài khoản.",
                 *       "instance": "/api/v1/admin/users/0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                 *       "traceId": "d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Vượt hạn mức 100 req/phút/user (ISS-04). Không có `Retry-After`. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/429",
                 *       "title": "Quá nhiều yêu cầu",
                 *       "status": 429,
                 *       "detail": "Bạn đã gửi quá nhiều yêu cầu. Vui lòng thử lại sau ít phút.",
                 *       "instance": "/api/v1/admin/users",
                 *       "traceId": "e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Lỗi không mong muốn. **Không bao giờ có `detail`** — `GlobalExceptionHandler` giấu chi tiết nội bộ, chỉ
         *     `traceId` đi ra ngoài để đối chiếu với log.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/500",
                 *       "title": "Đã xảy ra lỗi không mong muốn",
                 *       "status": 500,
                 *       "instance": "/api/v1/admin/users",
                 *       "traceId": "b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Fail-closed (Đ-6.8): server không kiểm được access token có bị thu hồi không. Không phải lỗi của phiên — FE **không**
         *     đăng xuất, hiện thông báo tạm thời và cho thử lại. Phân nhánh theo `type`, không theo `title`.
         */
        RevocationUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:socialapp:problem:revocation-unavailable",
                 *       "title": "Tạm thời không kiểm tra được phiên đăng nhập",
                 *       "status": 503,
                 *       "detail": "Chức năng quản trị tạm thời không khả dụng. Vui lòng thử lại sau ít phút.",
                 *       "instance": "/api/v1/admin/users",
                 *       "traceId": "f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6e8"
                 *     }
                 */
                "application/problem+json": components["schemas"]["RevocationUnavailableProblem"];
            };
        };
    };
    parameters: {
        /** @description UUID của tài khoản đích. Sai dạng → 400 `errors.userId`. */
        UserId: string;
        /** @description `nextCursor` của trang trước. Bỏ trống để lấy trang đầu. Cursor rác → 400 `errors.cursor`. */
        Cursor: string;
        /** @description Số tài khoản mỗi trang, mặc định 20, tối đa 50 (AGENTS.md Mục 9). Ngoài `1..50` → 400 `errors.limit`. */
        Limit: number;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Correlation ID của request, bằng đúng `traceId` trong Problem Details khi có lỗi.
         *     Client gửi header cùng tên thì server dùng lại giá trị đó.
         * @example 9f2c7b1e4a6d4f0b8c3e5a7d9b1f3c5e
         */
        XCorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAdminUsers: {
        parameters: {
            query?: {
                /**
                 * @description **Tiền tố** email, không phân biệt hoa thường (cột `citext`). `%`, `_` và `\` hiểu theo **nghĩa đen** — `a_`
                 *     không khớp `ab@…`. Không cắt khoảng trắng. Tối đa 254 ký tự → quá thì 400 `errors.q`.
                 * @example an.nguyen
                 */
                q?: string;
                /** @description Chỉ tài khoản ở trạng thái này. Giá trị khác hai giá trị dưới → 400 `errors.status`. */
                status?: "active" | "disabled";
                /** @description Chỉ tài khoản có vai trò này (`roles.code`). Sai dạng `RoleCode` → 400 `errors.roleCode`. */
                roleCode?: components["schemas"]["RoleCode"];
                /** @description `nextCursor` của trang trước. Bỏ trống để lấy trang đầu. Cursor rác → 400 `errors.cursor`. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Số tài khoản mỗi trang, mặc định 20, tối đa 50 (AGENTS.md Mục 9). Ngoài `1..50` → 400 `errors.limit`. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Một trang tài khoản. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *           "email": "an.nguyen@example.com",
                     *           "displayName": "Nguyễn Văn An",
                     *           "roleCode": "USER",
                     *           "roleDisplayName": "Người dùng",
                     *           "status": "active",
                     *           "emailVerified": true,
                     *           "lockedUntil": null,
                     *           "createdAt": "2026-09-08T03:10:22Z"
                     *         }
                     *       ],
                     *       "nextCursor": "MjAyNi0wOS0wOFQwMzoxMDoyMi4wMDAwMDAwKzAwOjAwfDAxOTJmM2MxLThhNGUtN2MzMS05ZjJhLTZiNWQ0ZTNjMmExMA"
                     *     }
                     */
                    "application/json": components["schemas"]["AdminUserPage"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    getAdminUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID của tài khoản đích. Sai dạng → 400 `errors.userId`. */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tài khoản. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *       "email": "an.nguyen@example.com",
                     *       "displayName": "Nguyễn Văn An",
                     *       "roleCode": "USER",
                     *       "roleDisplayName": "Người dùng",
                     *       "status": "active",
                     *       "emailVerified": true,
                     *       "lockedUntil": "2026-09-24T08:15:00Z",
                     *       "createdAt": "2026-09-08T03:10:22Z"
                     *     }
                     */
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
}
