/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách tài khoản, mới tạo trước
         * @description Tầng 2: **bất kỳ một** trong `user.lock`, `user.unlock`, `role.assign` (policy any-of, Mục 6.1) — người chỉ có
         *     `role.assign` cũng phải xem được danh sách để chọn người gán vai trò. `ADMIN` qua mọi mã (lối tắt tầng 2).
         *
         *     Sắp `created_at DESC`, hòa thì `user_id DESC`. Cursor opaque — FE chỉ chuyển tiếp `nextCursor`, không tự dựng.
         *     Hết dữ liệu khi `nextCursor` là `null`, không suy từ độ dài `items`.
         *
         *     Bộ lọc kết hợp bằng AND. `roleCode` đúng dạng mà không tồn tại → trang rỗng, không 400 (vai trò là dữ liệu từ GĐ6).
         */
        get: operations["listAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Một tài khoản
         * @description Cùng tầng 2 với danh sách. `userId` là **đích**; người thao tác luôn là chủ token. Không tồn tại → **404** — endpoint
         *     đặc quyền nên 404 không lộ gì cho người ngoài (tầng 2 đã chặn họ).
         */
        get: operations["getAdminUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Khóa tài khoản
         * @description Tầng 2: `user.lock`. `status` thành `disabled` (Đ-6.5) và **mọi** refresh family của người đó bị thu hồi trong CÙNG
         *     transaction; mốc `revoked:user` ghi **sau** `COMMIT` (Đ-6.6). Người bị khóa: request kế tiếp 401 → refresh 401 → về màn
         *     đăng nhập; đăng nhập lại đúng mật khẩu → 403 `account-disabled` (`identity-v1`).
         *
         *     | Tình huống | Phản hồi |
         *     |---|---|
         *     | Khóa thành công | 200, `revocation: applied` (hoặc `deferred` nếu Redis hỏng sau khi đã lưu) |
         *     | Tài khoản đã bị khóa | 200, `revocation: not-needed` — không đổi gì, không ghi nhật ký |
         *     | Tự khóa chính mình | 400 `errors.userId` |
         *     | Khóa quản trị viên hoạt động cuối cùng | 409 `last-admin` — không đổi gì |
         *
         *     `reason` vào nhật ký kiểm toán (`metadata.reason`), không lưu ở tài khoản.
         */
        post: operations["lockAdminUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mở khóa tài khoản
         * @description Tầng 2: `user.unlock`. Không body. `status` về `active` **và** xóa khóa tạm do đăng nhập sai (`lockedUntil`, bộ đếm) —
         *     người đó đăng nhập được ngay, không phải đợi 15 phút (Đ-6.5).
         *
         *     Không thu hồi gì (tài khoản bị khóa không có phiên sống) nên `revocation` luôn là `not-needed`. Tài khoản đang hoạt động
         *     và không bị khóa tạm → 200, không đổi gì, không ghi nhật ký.
         */
        post: operations["unlockAdminUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Đổi vai trò của tài khoản
         * @description Tầng 2: `role.assign`. Thao tác **chạm vai trò ADMIN** — nâng ai đó lên `ADMIN`, hoặc đổi vai trò của một người đang là
         *     `ADMIN` — cần **thêm** `role.manage` (tầng 2 kép, L-D18): người chỉ có `role.assign` (vai trò "Nhân sự") không tự nâng
         *     được mình hay ai khác lên toàn quyền. Thiếu → 403, có dòng `access.denied` trong nhật ký.
         *
         *     Có hiệu lực ở **request kế tiếp** mà người đó **không** bị đăng xuất (Mục 7.3): access token cũ 401 → BFF refresh cùng
         *     family → token mới mang vai trò mới (đọc từ DB). Refresh family **không** bị thu hồi.
         *
         *     | Tình huống | Phản hồi |
         *     |---|---|
         *     | Đổi thành công | 200, `revocation: applied` (hoặc `deferred` nếu Redis hỏng sau khi đã lưu) |
         *     | Đã mang đúng vai trò đó | 200, `revocation: not-needed` — không đổi gì, không ghi nhật ký |
         *     | `roleCode` không tồn tại (so **chính xác**, phân biệt hoa thường) | 400 `errors.roleCode` |
         *     | Hạ quản trị viên hoạt động cuối cùng | 409 `last-admin` — không đổi gì |
         *
         *     Tự hạ vai trò của chính mình **được**, miễn còn quản trị viên khác (Đ-6.7).
         */
        put: operations["assignAdminUserRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mọi vai trò, kèm quyền hiệu lực và số người mang
         * @description Tầng 2: `role.manage` (chỉ ADMIN có — Đ-6.9). Sắp theo `roleId`. `ADMIN` có `permissions` = cả 18 mã và
         *     `editable: false`.
         */
        get: operations["listAdminRoles"];
        put?: never;
        /**
         * Tạo vai trò
         * @description `code` bất biến từ lúc tạo — không endpoint nào sửa được nó (Đ-6.9). `permissions` là tập mã GÁN ĐƯỢC
         *     (`GET /admin/permissions` với `assignable: true`); rỗng được — vai trò tự tạo không có luật "ít nhất một quyền".
         *
         *     | Tình huống | Phản hồi |
         *     |---|---|
         *     | Mã sai dạng, trùng ba mã hệ thống, tên rỗng/quá 50, mã quyền lạ hoặc `role.manage` | 400 theo trường |
         *     | Mã đã có | 409 `role-code-taken` |
         */
        post: operations["createAdminRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Xóa vai trò tự tạo
         * @description Ba vai trò hệ thống → 409 `system-role`. Còn tài khoản mang vai trò (mọi trạng thái) → 409 `role-in-use` — gán họ sang
         *     vai trò khác trước. Tập quyền của vai trò bị xóa theo. Cache quyền mọi instance được xóa ngay (Đ-6.10).
         */
        delete: operations["deleteAdminRole"];
        options?: never;
        head?: never;
        /**
         * Đổi tên hiển thị của vai trò
         * @description CHỈ nhận `displayName` (1–50 ký tự sau cắt khoảng trắng). Body có `code` hay trường lạ bất kỳ → 400 theo tên trường —
         *     không lờ đi (GĐ1 Mục 3.1). Đổi tên vai trò hệ thống được. Cùng tên → 200, không ghi nhật ký.
         */
        patch: operations["renameAdminRole"];
        trace?: never;
    };
    "/admin/roles/{roleId}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Thay cả tập quyền của vai trò
         * @description Thay **cả tập** (idempotent) — gửi đúng tập muốn có, không gửi phần thêm/bớt. Có hiệu lực ở request KẾ TIẾP trên mọi
         *     instance (Đ-6.10) — người mang vai trò không phải đăng nhập lại.
         *
         *     | Tình huống | Phản hồi |
         *     |---|---|
         *     | `ADMIN` | 409 `system-role` — ADMIN có mọi quyền, không có tập nào để sửa |
         *     | Mã quyền lạ hoặc `role.manage` | 400 `errors.permissions` |
         *     | Không đổi gì | 200, không ghi nhật ký |
         *     | `USER`/`MODERATOR` về tập rỗng | 400 `errors.permissions` |
         *     | `USER`/`MODERATOR` có thay đổi mà thiếu `confirm: true` | **409** `confirmation-required` kèm `added`, `removed`, `affectedUsers` — không đổi gì; FE hiện đúng các con số đó rồi gửi lại với `confirm: true` |
         *
         *     Bước xác nhận bắt buộc ở SERVER — gọi thẳng API cũng phải qua.
         */
        put: operations["setAdminRolePermissions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh mục 18 mã quyền
         * @description Theo `permission_id`. `assignable: false` đúng với một mã, `role.manage` — chỉ ADMIN có (Đ-6.9), không gán cho vai trò
         *     nào qua API (L-D19); FE vẽ ô đó khóa.
         */
        get: operations["listAdminPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 7807 Problem Details — dạng lỗi duy nhất của toàn dự án. Sinh bởi
         *     `SocialApp.SharedKernel.Errors.GlobalExceptionHandler`; `traceId` và `type` gắn thống nhất
         *     trong `AddSharedKernel`.
         */
        ProblemDetails: {
            /**
             * Format: uri
             * @description Mặc định `https://httpstatuses.io/{status}`; ca FE phải phân nhánh thì là một URN ổn định.
             */
            type?: string;
            /** @description Nhãn ngắn, ổn định theo loại lỗi. **Không** chứa dữ liệu người dùng. */
            title: string;
            /** Format: int32 */
            status: number;
            /** @description Thông điệp cho người đọc. Vắng mặt ở lỗi 500. */
            detail?: string | null;
            /** @description Path của request gây lỗi. */
            instance?: string;
            /** @description Bằng header `X-Correlation-ID` của chính request đó — dùng để tra log. */
            traceId: string;
            /** @description Chỉ có ở lỗi validation (400). Map `tên trường → danh sách thông điệp`. */
            errors?: {
                [key: string]: string[];
            } | null;
        };
        /** @description 503 fail-closed của endpoint quản trị (Đ-6.8). Cùng hình dạng `ProblemDetails`, `type` cố định. */
        RevocationUnavailableProblem: components["schemas"]["ProblemDetails"] & {
            /** @enum {string} */
            type: "urn:socialapp:problem:revocation-unavailable";
        };
        /** @description 409 "phải còn ít nhất một quản trị viên hoạt động" (Đ-6.7). Cùng hình dạng `ProblemDetails`, `type` cố định. */
        LastAdminProblem: components["schemas"]["ProblemDetails"] & {
            /** @enum {string} */
            type: "urn:socialapp:problem:last-admin";
        };
        /**
         * @description `roles.code` — bất biến, cùng định nghĩa `RoleCode` của `identity-v1`. Ba vai trò hệ thống luôn có: `USER`,
         *     `MODERATOR`, `ADMIN`; từ GĐ6 Admin tạo được vai trò mới nên đây là chuỗi mở.
         * @example USER
         */
        RoleCode: string;
        /**
         * @description Khớp `CONSTRAINT ck_users_status` — cùng bốn giá trị với `UserStatus` của `identity-v1` (quyết định 5 của GĐ1: giữ đủ
         *     bốn để GĐ6/GĐ8 không mở lại hợp đồng). `disabled` = bị Admin khóa (Đ-6.5). `locked` không ai ghi; `deleted` chờ GĐ8.
         *     Khóa tạm do đăng nhập sai (FR-003) **không** ở đây mà ở `lockedUntil`.
         * @enum {string}
         */
        UserStatus: "active" | "locked" | "disabled" | "deleted";
        AdminUser: {
            /** Format: uuid */
            userId: string;
            /**
             * Format: email
             * @description PII (Mục 8.2) — chỉ có ở nhóm `admin-v1`.
             */
            email: string;
            /** @description Tên hiển thị từ hồ sơ. `null` khi người này chưa tạo hồ sơ (onboarding). */
            displayName: string | null;
            roleCode: components["schemas"]["RoleCode"];
            /**
             * @description Tên vai trò cho người đọc (`roles.display_name`) — không dùng để so sánh logic.
             * @example Người dùng
             */
            roleDisplayName: string;
            status: components["schemas"]["UserStatus"];
            emailVerified: boolean;
            /**
             * Format: date-time
             * @description Khóa **tạm** do đăng nhập sai nhiều lần (FR-003) — khác `status = disabled` của Admin. Chỉ có giá trị khi mốc còn ở
             *     tương lai; mốc đã qua (tài khoản đã tự mở) trả `null`.
             */
            lockedUntil: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        AdminUserPage: {
            /** @description Sắp `created_at DESC`, hòa thì `user_id DESC`. */
            items: components["schemas"]["AdminUser"][];
            /** @description Opaque. `null` khi hết dữ liệu — không phải chuỗi rỗng. */
            nextCursor: string | null;
        };
        LockRequest: {
            /**
             * @description Lý do khóa, 1–500 ký tự sau khi cắt khoảng trắng hai đầu. Vào `metadata.reason` của nhật ký kiểm toán — không lưu ở
             *     tài khoản, không vào log. Thiếu, rỗng hay quá dài → 400 `errors.reason`.
             */
            reason: string;
        };
        AdminUserChange: {
            user: components["schemas"]["AdminUser"];
            /**
             * @description Phiên đang mở của người bị đổi (Đ-6.6):
             *     - `applied` — đã thu hồi; request kế tiếp của họ 401.
             *     - `deferred` — thay đổi **đã lưu** nhưng chưa thu hồi được phiên: phiên đang mở có thể giữ quyền cũ tối đa 15 phút.
             *       UI hiện đúng câu đó, không báo lỗi.
             *     - `not-needed` — không có gì để thu hồi (mở khóa, hoặc thao tác không đổi gì).
             * @enum {string}
             */
            revocation: "applied" | "deferred" | "not-needed";
        };
        AssignRoleRequest: {
            /**
             * @description Mã vai trò đích (`roles.code`), so **chính xác** — `user` không phải `USER`. Thiếu, rỗng hay dài hơn 30 ký tự → 400
             *     `errors.roleCode`; không tồn tại → 400 `errors.roleCode` *"Vai trò không tồn tại."*
             * @example MODERATOR
             */
            roleCode: string;
        };
        /** @description 409 của vai trò (Đ-6.9). Cùng hình dạng `ProblemDetails`, `type` cho biết loại. */
        RoleConflictProblem: components["schemas"]["ProblemDetails"] & {
            /** @enum {string} */
            type: "urn:socialapp:problem:role-code-taken" | "urn:socialapp:problem:system-role" | "urn:socialapp:problem:role-in-use";
        };
        /**
         * @description 409 khi sửa quyền USER/MODERATOR mà chưa xác nhận (Đ-6.9, L-D11). Không có gì bị đổi. `added`/`removed` sắp theo mã;
         *     `affectedUsers` đếm MỌI tài khoản mang vai trò (kể cả đang bị khóa).
         */
        ConfirmationRequiredProblem: components["schemas"]["ProblemDetails"] & {
            /** @enum {string} */
            type: "urn:socialapp:problem:confirmation-required";
            added: string[];
            removed: string[];
            /** Format: int32 */
            affectedUsers: number;
        };
        RoleSummary: {
            /**
             * Format: int32
             * @description Id vai trò. Ba vai trò hệ thống 1–3; vai trò tự tạo từ 100.
             */
            roleId: number;
            code: components["schemas"]["RoleCode"];
            displayName: string;
            /** @description `USER`, `MODERATOR`, `ADMIN` — tính từ mã, không phải cột. */
            isSystem: boolean;
            /** @description Sửa được tập quyền — mọi vai trò trừ `ADMIN`. */
            editable: boolean;
            /**
             * Format: int32
             * @description Số tài khoản mang vai trò, mọi trạng thái.
             */
            userCount: number;
            /** @description Quyền hiệu lực, theo `permission_id`. `ADMIN` = cả 18 mã. */
            permissions: string[];
        };
        CreateRoleRequest: {
            code: components["schemas"]["RoleCode"];
            displayName: string;
            /** @description Tập mã gán được. Mã trùng được gộp. */
            permissions: string[];
        };
        /** @description CHỈ `displayName` — có `code` hay trường lạ → 400. */
        RenameRoleRequest: {
            displayName: string;
        };
        SetRolePermissionsRequest: {
            /** @description CẢ tập mong muốn. Mã trùng được gộp. */
            permissions: string[];
            /** @description Bắt buộc `true` khi sửa `USER`/`MODERATOR` — thiếu thì 409 `confirmation-required`. */
            confirm?: boolean;
        };
        PermissionInfo: {
            code: string;
            description: string | null;
            /** @description `false` với `role.manage` — không gán được cho vai trò nào (L-D19). */
            assignable: boolean;
        };
    };
    responses: {
        /**
         * @description Dữ liệu đầu vào không hợp lệ. `errors` là map `tên trường → danh sách thông điệp`: `cursor` rác, `limit` ngoài
         *     `1..50`, `q` quá dài, `status`/`roleCode` sai dạng, `userId` không phải UUID.
         */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/400",
                 *       "title": "Dữ liệu không hợp lệ",
                 *       "status": 400,
                 *       "detail": "Dữ liệu đầu vào không hợp lệ",
                 *       "instance": "/api/v1/admin/users",
                 *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8",
                 *       "errors": {
                 *         "status": [
                 *           "Trạng thái chỉ nhận active hoặc disabled."
                 *         ]
                 *       }
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Thiếu access token, token sai chữ ký, hết hạn, hoặc đã bị thu hồi. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/401",
                 *       "title": "Chưa xác thực",
                 *       "status": 401,
                 *       "detail": "Yêu cầu access token hợp lệ.",
                 *       "instance": "/api/v1/admin/users",
                 *       "traceId": "a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Tầng 2 từ chối — vai trò không có mã quyền nào endpoint đòi (dòng `TC-A05` của AuthZ matrix), hoặc tầng 2 kép của đổi
         *     vai trò (thao tác chạm ADMIN mà thiếu `role.manage`). Để lại một dòng `access.denied` trong nhật ký kiểm toán (Đ-6.15).
         *     Thông điệp không nêu quyền còn thiếu.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/403",
                 *       "title": "Bị từ chối",
                 *       "status": 403,
                 *       "detail": "Bạn không có quyền thực hiện thao tác này.",
                 *       "instance": "/api/v1/admin/users",
                 *       "traceId": "c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Tài khoản không tồn tại. */
        UserNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/404",
                 *       "title": "Không tìm thấy tài nguyên",
                 *       "status": 404,
                 *       "detail": "Không tìm thấy tài khoản.",
                 *       "instance": "/api/v1/admin/users/0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                 *       "traceId": "d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Thao tác sẽ làm hệ thống còn **0** quản trị viên hoạt động (Đ-6.7) — không có gì bị đổi. Kiểm sau khi ghi, trong cùng
         *     transaction, dưới khóa tư vấn: hai Admin khóa nhau cùng lúc thì đúng một bên thành công. Phân nhánh theo `type`.
         */
        LastAdmin: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:socialapp:problem:last-admin",
                 *       "title": "Xung đột dữ liệu",
                 *       "status": 409,
                 *       "detail": "Hệ thống phải còn ít nhất một quản trị viên đang hoạt động.",
                 *       "instance": "/api/v1/admin/users/0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10/lock",
                 *       "traceId": "a2c4e6b8d0f2a4c6e8b0d2f4a6c8e0b2"
                 *     }
                 */
                "application/problem+json": components["schemas"]["LastAdminProblem"];
            };
        };
        /** @description Vai trò không tồn tại. */
        RoleNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/404",
                 *       "title": "Không tìm thấy tài nguyên",
                 *       "status": 404,
                 *       "detail": "Không tìm thấy vai trò.",
                 *       "instance": "/api/v1/admin/roles/100",
                 *       "traceId": "d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Xung đột với trạng thái vai trò. Phân nhánh theo `type`: `role-code-taken` (tạo trùng mã) · `system-role` (xóa vai trò
         *     hệ thống) · `role-in-use` (xóa vai trò còn người mang).
         */
        RoleConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:socialapp:problem:role-in-use",
                 *       "title": "Xung đột dữ liệu",
                 *       "status": 409,
                 *       "detail": "Vai trò đang có người dùng, không xóa được.",
                 *       "instance": "/api/v1/admin/roles/100",
                 *       "traceId": "a2c4e6b8d0f2a4c6e8b0d2f4a6c8e0b2"
                 *     }
                 */
                "application/problem+json": components["schemas"]["RoleConflictProblem"];
            };
        };
        /**
         * @description `system-role` (sửa quyền ADMIN) hoặc `confirmation-required` (sửa USER/MODERATOR thiếu `confirm: true` — mang `added`,
         *     `removed`, `affectedUsers`). Phân nhánh theo `type`.
         */
        RolePermissionsConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:socialapp:problem:confirmation-required",
                 *       "title": "Cần xác nhận",
                 *       "status": 409,
                 *       "detail": "Thay đổi quyền của vai trò hệ thống cần được xác nhận.",
                 *       "instance": "/api/v1/admin/roles/1/permissions",
                 *       "traceId": "a2c4e6b8d0f2a4c6e8b0d2f4a6c8e0b2",
                 *       "added": [],
                 *       "removed": [
                 *         "post.create"
                 *       ],
                 *       "affectedUsers": 1523
                 *     }
                 */
                "application/problem+json": components["schemas"]["ConfirmationRequiredProblem"] | components["schemas"]["RoleConflictProblem"];
            };
        };
        /** @description Vượt hạn mức 100 req/phút/user (ISS-04). Không có `Retry-After`. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/429",
                 *       "title": "Quá nhiều yêu cầu",
                 *       "status": 429,
                 *       "detail": "Bạn đã gửi quá nhiều yêu cầu. Vui lòng thử lại sau ít phút.",
                 *       "instance": "/api/v1/admin/users",
                 *       "traceId": "e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Lỗi không mong muốn. **Không bao giờ có `detail`** — `GlobalExceptionHandler` giấu chi tiết nội bộ, chỉ
         *     `traceId` đi ra ngoài để đối chiếu với log.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/500",
                 *       "title": "Đã xảy ra lỗi không mong muốn",
                 *       "status": 500,
                 *       "instance": "/api/v1/admin/users",
                 *       "traceId": "b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Fail-closed (Đ-6.8): server không kiểm được access token có bị thu hồi không. Không phải lỗi của phiên — FE **không**
         *     đăng xuất, hiện thông báo tạm thời và cho thử lại. Phân nhánh theo `type`, không theo `title`.
         */
        RevocationUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:socialapp:problem:revocation-unavailable",
                 *       "title": "Tạm thời không kiểm tra được phiên đăng nhập",
                 *       "status": 503,
                 *       "detail": "Chức năng quản trị tạm thời không khả dụng. Vui lòng thử lại sau ít phút.",
                 *       "instance": "/api/v1/admin/users",
                 *       "traceId": "f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6e8"
                 *     }
                 */
                "application/problem+json": components["schemas"]["RevocationUnavailableProblem"];
            };
        };
    };
    parameters: {
        /** @description Id vai trò. Sai dạng → 400 `errors.roleId`. */
        RoleId: number;
        /** @description UUID của tài khoản đích. Sai dạng → 400 `errors.userId`. */
        UserId: string;
        /** @description `nextCursor` của trang trước. Bỏ trống để lấy trang đầu. Cursor rác → 400 `errors.cursor`. */
        Cursor: string;
        /** @description Số tài khoản mỗi trang, mặc định 20, tối đa 50 (AGENTS.md Mục 9). Ngoài `1..50` → 400 `errors.limit`. */
        Limit: number;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Correlation ID của request, bằng đúng `traceId` trong Problem Details khi có lỗi.
         *     Client gửi header cùng tên thì server dùng lại giá trị đó.
         * @example 9f2c7b1e4a6d4f0b8c3e5a7d9b1f3c5e
         */
        XCorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAdminUsers: {
        parameters: {
            query?: {
                /**
                 * @description **Tiền tố** email, không phân biệt hoa thường (cột `citext`). `%`, `_` và `\` hiểu theo **nghĩa đen** — `a_`
                 *     không khớp `ab@…`. Không cắt khoảng trắng. Tối đa 254 ký tự → quá thì 400 `errors.q`.
                 * @example an.nguyen
                 */
                q?: string;
                /** @description Chỉ tài khoản ở trạng thái này. Giá trị khác hai giá trị dưới → 400 `errors.status`. */
                status?: "active" | "disabled";
                /** @description Chỉ tài khoản có vai trò này (`roles.code`). Sai dạng `RoleCode` → 400 `errors.roleCode`. */
                roleCode?: components["schemas"]["RoleCode"];
                /** @description `nextCursor` của trang trước. Bỏ trống để lấy trang đầu. Cursor rác → 400 `errors.cursor`. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Số tài khoản mỗi trang, mặc định 20, tối đa 50 (AGENTS.md Mục 9). Ngoài `1..50` → 400 `errors.limit`. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Một trang tài khoản. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *           "email": "an.nguyen@example.com",
                     *           "displayName": "Nguyễn Văn An",
                     *           "roleCode": "USER",
                     *           "roleDisplayName": "Người dùng",
                     *           "status": "active",
                     *           "emailVerified": true,
                     *           "lockedUntil": null,
                     *           "createdAt": "2026-09-08T03:10:22Z"
                     *         }
                     *       ],
                     *       "nextCursor": "MjAyNi0wOS0wOFQwMzoxMDoyMi4wMDAwMDAwKzAwOjAwfDAxOTJmM2MxLThhNGUtN2MzMS05ZjJhLTZiNWQ0ZTNjMmExMA"
                     *     }
                     */
                    "application/json": components["schemas"]["AdminUserPage"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    getAdminUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID của tài khoản đích. Sai dạng → 400 `errors.userId`. */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tài khoản. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *       "email": "an.nguyen@example.com",
                     *       "displayName": "Nguyễn Văn An",
                     *       "roleCode": "USER",
                     *       "roleDisplayName": "Người dùng",
                     *       "status": "active",
                     *       "emailVerified": true,
                     *       "lockedUntil": "2026-09-24T08:15:00Z",
                     *       "createdAt": "2026-09-08T03:10:22Z"
                     *     }
                     */
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    lockAdminUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID của tài khoản đích. Sai dạng → 400 `errors.userId`. */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "reason": "Đăng nội dung lừa đảo lặp lại sau hai lần nhắc."
                 *     }
                 */
                "application/json": components["schemas"]["LockRequest"];
            };
        };
        responses: {
            /** @description Tài khoản sau thao tác, kèm trạng thái thu hồi phiên. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "user": {
                     *         "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *         "email": "an.nguyen@example.com",
                     *         "displayName": "Nguyễn Văn An",
                     *         "roleCode": "USER",
                     *         "roleDisplayName": "Người dùng",
                     *         "status": "disabled",
                     *         "emailVerified": true,
                     *         "lockedUntil": null,
                     *         "createdAt": "2026-09-08T03:10:22Z"
                     *       },
                     *       "revocation": "applied"
                     *     }
                     */
                    "application/json": components["schemas"]["AdminUserChange"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
            409: components["responses"]["LastAdmin"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    unlockAdminUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID của tài khoản đích. Sai dạng → 400 `errors.userId`. */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tài khoản sau thao tác. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "user": {
                     *         "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *         "email": "an.nguyen@example.com",
                     *         "displayName": "Nguyễn Văn An",
                     *         "roleCode": "USER",
                     *         "roleDisplayName": "Người dùng",
                     *         "status": "active",
                     *         "emailVerified": true,
                     *         "lockedUntil": null,
                     *         "createdAt": "2026-09-08T03:10:22Z"
                     *       },
                     *       "revocation": "not-needed"
                     *     }
                     */
                    "application/json": components["schemas"]["AdminUserChange"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    assignAdminUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID của tài khoản đích. Sai dạng → 400 `errors.userId`. */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "roleCode": "MODERATOR"
                 *     }
                 */
                "application/json": components["schemas"]["AssignRoleRequest"];
            };
        };
        responses: {
            /** @description Tài khoản sau thao tác, kèm trạng thái thu hồi phiên. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "user": {
                     *         "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *         "email": "an.nguyen@example.com",
                     *         "displayName": "Nguyễn Văn An",
                     *         "roleCode": "MODERATOR",
                     *         "roleDisplayName": "Kiểm duyệt viên",
                     *         "status": "active",
                     *         "emailVerified": true,
                     *         "lockedUntil": null,
                     *         "createdAt": "2026-09-08T03:10:22Z"
                     *       },
                     *       "revocation": "applied"
                     *     }
                     */
                    "application/json": components["schemas"]["AdminUserChange"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
            409: components["responses"]["LastAdmin"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    listAdminRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách vai trò. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleSummary"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    createAdminRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "code": "REVIEWER",
                 *       "displayName": "Người xem xét báo cáo",
                 *       "permissions": [
                 *         "report.resolve"
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["CreateRoleRequest"];
            };
        };
        responses: {
            /** @description Vai trò vừa tạo. */
            201: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "roleId": 100,
                     *       "code": "REVIEWER",
                     *       "displayName": "Người xem xét báo cáo",
                     *       "isSystem": false,
                     *       "editable": true,
                     *       "userCount": 0,
                     *       "permissions": [
                     *         "report.resolve"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["RoleSummary"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["RoleConflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    deleteAdminRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id vai trò. Sai dạng → 400 `errors.roleId`. */
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã xóa. */
            204: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["RoleNotFound"];
            409: components["responses"]["RoleConflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    renameAdminRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id vai trò. Sai dạng → 400 `errors.roleId`. */
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "displayName": "Kiểm duyệt nội dung"
                 *     }
                 */
                "application/json": components["schemas"]["RenameRoleRequest"];
            };
        };
        responses: {
            /** @description Vai trò sau thao tác. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "roleId": 100,
                     *       "code": "REVIEWER",
                     *       "displayName": "Người xem xét báo cáo",
                     *       "isSystem": false,
                     *       "editable": true,
                     *       "userCount": 2,
                     *       "permissions": [
                     *         "report.resolve"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["RoleSummary"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["RoleNotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    setAdminRolePermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id vai trò. Sai dạng → 400 `errors.roleId`. */
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "permissions": [
                 *         "post.read.public",
                 *         "post.read.friends",
                 *         "post.update",
                 *         "post.delete",
                 *         "comment.create",
                 *         "reaction.set",
                 *         "friend.request",
                 *         "friend.respond",
                 *         "message.send",
                 *         "report.create"
                 *       ],
                 *       "confirm": true
                 *     }
                 */
                "application/json": components["schemas"]["SetRolePermissionsRequest"];
            };
        };
        responses: {
            /** @description Vai trò sau thao tác. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "roleId": 100,
                     *       "code": "REVIEWER",
                     *       "displayName": "Người xem xét báo cáo",
                     *       "isSystem": false,
                     *       "editable": true,
                     *       "userCount": 2,
                     *       "permissions": [
                     *         "report.resolve"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["RoleSummary"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["RoleNotFound"];
            409: components["responses"]["RolePermissionsConflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    listAdminPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh mục quyền. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "code": "post.read.public",
                     *         "description": "Đọc bài công khai",
                     *         "assignable": true
                     *       },
                     *       {
                     *         "code": "role.manage",
                     *         "description": "Định nghĩa vai trò và tập quyền",
                     *         "assignable": false
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["PermissionInfo"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
}
