/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng ký tài khoản (FR-001)
         * @description Tạo tài khoản với `role_id = 1 (USER)`, `email_verified_at = NULL`, mật khẩu băm BCrypt
         *     cost 12, rồi gửi mail xác minh (token ngẫu nhiên 32 byte, lưu **băm**, hạn 24 giờ).
         *     Ở dev mail đi qua Mailpit; ở staging đi qua Brevo tới hộp thư thật.
         *
         *     Tài khoản **chưa đăng nhập được** cho tới khi gọi `/auth/verify-email` — đăng nhập lúc này
         *     trả `403`.
         *
         *     > Endpoint này **có** trả `409` khi email đã tồn tại. Đây là ngoại lệ có ý thức so với quy
         *     > tắc "không lộ email tồn tại" của `/auth/login`: không báo trùng thì người dùng không có
         *     > cách nào biết vì sao đăng ký hỏng. Rate limit 10 req/phút/IP là thứ chặn việc lạm dụng
         *     > endpoint này để dò danh sách email.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Xác minh email bằng token trong mail (FR-001)
         * @description Nhận token bản rõ từ link trong mail, băm SHA-256 rồi đối chiếu `token_hash`. Hợp lệ thì
         *     set `users.email_verified_at` và `email_verification_tokens.consumed_at`.
         *
         *     Phân biệt hai mã lỗi — frontend hiển thị khác nhau:
         *
         *     - `400` — token sai định dạng hoặc không tồn tại → "Liên kết không hợp lệ".
         *     - `410` — token đúng nhưng **đã hết hạn (quá 24 giờ) hoặc đã dùng rồi** → "Liên kết đã hết
         *       hiệu lực". Endpoint gửi lại mail **chưa có ở GĐ1**, nên màn này chỉ hướng dẫn đăng ký lại
         *       hoặc liên hệ hỗ trợ.
         */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng nhập, cấp access token + refresh cookie (FR-002, FR-003)
         * @description Thứ tự kiểm tra (docs/giai-doan-1.md Mục 7.2):
         *
         *     1. Tra user theo email (`citext`, không phân biệt hoa thường).
         *     2. **Không tồn tại → vẫn chạy một phép BCrypt giả** rồi trả `401`. Bỏ bước này là thời gian
         *        phản hồi lộ ra email nào có thật.
         *     3. `locked_until > now()` → `423`.
         *     4. Sai mật khẩu → `failed_login_count++`; đạt 5 thì `locked_until = now() + 15 phút` → `401`.
         *     5. `email_verified_at IS NULL` → `403`.
         *     6. Thành công → reset bộ đếm, phát access token 15 phút + refresh token với `family_id`
         *        **mới** (một lần đăng nhập = một family = một thiết bị).
         *
         *     > **AC-02 — `401` không được lộ email có tồn tại hay không.** Sai mật khẩu và email không
         *     > tồn tại dùng **cùng một** `title`/`detail`, và thời gian phản hồi phải tương đương.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Xoay vòng refresh token, cấp access token mới (NFR-SEC-03)
         * @description **Endpoint này KHÔNG NHẬN BODY.** Refresh token đọc từ cookie `refresh_token`
         *     (quyết định 6 ở cổng mở).
         *
         *     Toàn bộ chạy trong một transaction: khóa theo `family_id` rồi `SELECT ... FOR UPDATE` trên dòng token
         *     (docs/giai-doan-1.md Mục 7.3):
         *
         *     1. Băm SHA-256 token nhận được → tra `token_hash`.
         *     2. Không thấy → `401`.
         *     3. `revoked_at IS NOT NULL` hoặc `replaced_by_id IS NOT NULL` → **REUSE DETECTION**:
         *        thu hồi toàn bộ `family_id` → `401`. Người dùng bị đăng xuất khỏi thiết bị đó.
         *     4. `expires_at < now()` → `401`.
         *     5. Hợp lệ → sinh token mới **cùng `family_id`**; token cũ nhận `revoked_at = now()` và
         *        `replaced_by_id = <id mới>`.
         *
         *     > **Ân hạn 10 giây.** Nếu token đã bị thay thế **trong vòng 10 giây** và chuỗi chưa bị thu
         *     > hồi, server phát một refresh token **mới cùng chuỗi** (kèm access token mới) thay vì coi là
         *     > reuse — không trả lại đúng token kế nhiệm, vì server chỉ lưu băm. Đây là cái đỡ cho race hai tab
         *     > (test RT-04) — nhưng nó **không thay thế** yêu cầu single-flight ở client: ân hạn che
         *     > được phần lớn, không phải tất cả.
         *
         *     Mọi trường hợp hỏng của endpoint này đều là `401` — cố ý. Phân biệt "hết hạn" với "bị thu
         *     hồi do reuse" là nói cho kẻ tấn công biết token nó đang cầm ở trạng thái nào.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng xuất — thu hồi toàn bộ family của refresh token
         * @description Thu hồi **toàn bộ `family_id`** của refresh token gửi lên, không chỉ một dòng — báo cáo
         *     Mục 6.7.3 yêu cầu "đăng xuất thu hồi toàn bộ phiên" (docs/giai-doan-1.md Mục 7.4). Cookie bị xóa
         *     trong cùng response.
         *
         *     Access token đang cầm **vẫn còn hiệu lực tối đa 15 phút** — đó là bản chất stateless của
         *     JWT, không phải bug. Client phải tự xóa nó khỏi memory. Cắt ngay lập tức cần ghi
         *     `revoked:user`, mà ở GĐ1 trigger ghi đó chỉ nối cho reuse detection (Mục 7.5).
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hồ sơ rút gọn của phiên hiện tại
         * @description Smoke test rẻ nhất chứng minh tầng 1 (AuthN) + tầng 2 (RBAC) chạy thông từ đầu đến cuối —
         *     giữ endpoint này qua mọi giai đoạn sau.
         *
         *     Trả về `role` (chuỗi `code`, thứ nằm trong JWT) **và** `roleDisplayName` (chuỗi cho người
         *     đọc) — đây chính là lý do bảng `roles` tách hai cột (quyết định 3). Frontend hiển thị
         *     `roleDisplayName`, so sánh logic thì dùng `role`.
         *
         *     `role` trong response đọc từ **DB**, còn `role` trong JWT là bản đã đóng dấu lúc phát token.
         *     Từ GĐ6 hai giá trị này có thể lệch nhau trong tối đa 15 phút sau khi Admin đổi vai trò —
         *     `revoked:user` + `iat` là thứ rút khoảng lệch đó về gần như tức thì.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 7807 Problem Details — dạng lỗi duy nhất của toàn dự án. Sinh bởi
         *     `SocialApp.SharedKernel.Errors.GlobalExceptionHandler`; `traceId` và `type` gắn thống nhất
         *     trong `AddSharedKernel`.
         */
        ProblemDetails: {
            /**
             * Format: uri
             * @description Mặc định `https://httpstatuses.io/{status}`.
             */
            type?: string;
            /** @description Nhãn ngắn, ổn định theo loại lỗi. **Không** chứa dữ liệu người dùng. */
            title: string;
            /** Format: int32 */
            status: number;
            /** @description Thông điệp cho người đọc. Vắng mặt ở lỗi 500. */
            detail?: string | null;
            /** @description Path của request gây lỗi. */
            instance?: string;
            /** @description Bằng header `X-Correlation-ID` của chính request đó — dùng để tra log. */
            traceId: string;
            /** @description Chỉ có ở lỗi validation (400). Map `tên trường → danh sách thông điệp`. */
            errors?: {
                [key: string]: string[];
            } | null;
        };
        RegisterRequest: {
            /**
             * Format: email
             * @description Không phân biệt hoa thường (cột `citext`) — `An@Example.com` và `an@example.com` là
             *     **một** tài khoản.
             */
            email: string;
            /**
             * Format: password
             * @description Tối thiểu 8 ký tự. Trần 72 là **giới hạn cứng của BCrypt**: ký tự thứ 73 trở đi bị
             *     thuật toán bỏ qua âm thầm, nên chặn ở validator thay vì để người dùng tin nhầm là mật
             *     khẩu của mình dài hơn thực tế.
             */
            password: string;
        };
        RegisterResponse: {
            /**
             * Format: uuid
             * @description UUID **v7** (tuần tự theo thời gian), sinh bằng `UUIDNext` — không phải `Guid.NewGuid()`.
             */
            userId: string;
            /** Format: email */
            email: string;
        };
        VerifyEmailRequest: {
            /**
             * @description Token bản rõ lấy từ query string của link trong mail. Server chỉ lưu băm SHA-256 của nó,
             *     nên rò rỉ DB không kéo theo rò rỉ tài khoản.
             */
            token: string;
        };
        VerifyEmailResponse: {
            /** Format: email */
            email: string;
            /** Format: date-time */
            verifiedAt: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        /**
         * @description Body của `/auth/login` và `/auth/refresh`. Refresh token **không** nằm ở đây — nó đi trong
         *     `Set-Cookie` (quyết định 6).
         */
        TokenResponse: {
            /** @description JWT HS256. Client giữ trong memory, gắn vào header `Authorization: Bearer <token>`. */
            accessToken: string;
            /**
             * Format: int32
             * @description Số **giây** access token còn sống — 900. TTL của `revoked:user` trên Redis tính từ CÙNG
             *     hằng số này cộng `ClockSkew` (900 + 30); tính từ nguồn khác là một lỗ hổng câm không test
             *     nào bắt được (docs/giai-doan-1.md Mục 7.5).
             * @example 900
             */
            expiresIn: number;
        };
        MeResponse: {
            /** Format: uuid */
            userId: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["RoleCode"];
            /**
             * @description Tên hiển thị cho người đọc (`roles.display_name`) — sửa được, **không** dùng để so sánh
             *     logic.
             * @example Người dùng
             */
            roleDisplayName: string;
            /**
             * Format: date-time
             * @description Luôn khác `null` ở đây — chưa xác minh thì đã bị chặn từ `/auth/login` với 403, không có
             *     token để gọi endpoint này.
             */
            emailVerifiedAt?: string | null;
            status: components["schemas"]["UserStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * @description `roles.code` — **bất biến theo hợp đồng API**. Không endpoint nào cho phép sửa trường này;
         *     endpoint sửa vai trò ở GĐ6 chỉ nhận `displayName`.
         *
         *     Đây cũng chính là giá trị của claim `role` trong JWT, cho **mọi** vai trò. `ADMIN` đi lối
         *     tắt ở tầng 2 nên không có dòng nào trong `role_permissions` — đúng thiết kế, không phải
         *     thiếu dữ liệu seed.
         * @example USER
         * @enum {string}
         */
        RoleCode: "USER" | "MODERATOR" | "ADMIN";
        /**
         * @description Khớp `CONSTRAINT ck_users_status`. Ở GĐ1 chỉ `active` xuất hiện thực tế — khóa do lockout
         *     FR-003 là trạng thái tạm nằm ở cột `locked_until`, còn `disabled`/`deleted` chờ GĐ6/GĐ8.
         * @example active
         * @enum {string}
         */
        UserStatus: "active" | "locked" | "disabled" | "deleted";
    };
    responses: {
        /**
         * @description Dữ liệu đầu vào không hợp lệ. `errors` là map `tên trường → danh sách thông điệp`.
         *
         *     Cũng là mã trả về khi body chứa **field lạ** — quy ước `UnmappedMemberHandling = Disallow`
         *     của toàn dự án (AGENTS.md Mục 9).
         */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/400",
                 *       "title": "Dữ liệu không hợp lệ",
                 *       "status": 400,
                 *       "detail": "Dữ liệu đầu vào không hợp lệ",
                 *       "instance": "/api/v1/auth/register",
                 *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8",
                 *       "errors": {
                 *         "email": [
                 *           "Email không đúng định dạng."
                 *         ],
                 *         "password": [
                 *           "Mật khẩu phải có ít nhất 8 ký tự."
                 *         ]
                 *       }
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Thiếu access token, token sai chữ ký, hết hạn, hoặc đã bị thu hồi qua `revoked:user`
         *     (`iat` cũ hơn mốc thu hồi).
         *
         *     Đây là hai dòng đầu của AuthZ matrix — TC-A01 và TC-A02, cổng chặn merge từ GĐ1
         *     (docs/giai-doan-1.md Mục 10.2).
         */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/401",
                 *       "title": "Chưa xác thực",
                 *       "status": 401,
                 *       "detail": "Yêu cầu access token hợp lệ.",
                 *       "instance": "/api/v1/me",
                 *       "traceId": "a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Vượt rate limit — 10 req/phút/IP cho nhóm auth, 100 req/phút/user cho phần còn lại (ISS-04). */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/429",
                 *       "title": "Quá nhiều yêu cầu",
                 *       "status": 429,
                 *       "detail": "Bạn đã gửi quá nhiều yêu cầu. Vui lòng thử lại sau ít phút.",
                 *       "instance": "/api/v1/auth/login",
                 *       "traceId": "e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Lỗi không mong muốn. **Không bao giờ có `detail`** — `GlobalExceptionHandler` giấu chi tiết
         *     nội bộ, chỉ `traceId` đi ra ngoài để đối chiếu với log.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/500",
                 *       "title": "Đã xảy ra lỗi không mong muốn",
                 *       "status": 500,
                 *       "instance": "/api/v1/auth/login",
                 *       "traceId": "b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /**
         * @description Correlation ID của request, bằng đúng `traceId` trong Problem Details khi có lỗi.
         *     Client gửi header cùng tên thì server dùng lại giá trị đó.
         * @example 9f2c7b1e4a6d4f0b8c3e5a7d9b1f3c5e
         */
        XCorrelationId: string;
        /**
         * @description Cookie refresh token. Thuộc tính là **một phần của hợp đồng**, không phải chi tiết cài đặt:
         *
         *     - `HttpOnly` — chặn XSS đọc mất token sống lâu nhất trong hệ thống.
         *     - `Secure` — chỉ đi qua HTTPS (trình duyệt vẫn chấp nhận trên `http://localhost`).
         *     - `SameSite=Lax` — chặn CSRF cơ bản; endpoint nghiệp vụ không phụ thuộc cookie vì access
         *       token đi bằng header `Authorization`.
         *     - `Path=/api/v1/auth` — cookie chỉ gửi kèm nhóm auth, không đính vào mọi request.
         *     - `Max-Age=604800` — 7 ngày.
         * @example refresh_token=3f9a7c2bd41e8065a1b3c5d7e9f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6; HttpOnly; Secure; SameSite=Lax; Path=/api/v1/auth; Max-Age=604800
         */
        SetRefreshCookie: string;
        /**
         * @description Xóa cookie refresh (`Max-Age=0`). Thuộc tính `Path` phải khớp lúc set, nếu không trình
         *     duyệt giữ nguyên cookie cũ.
         * @example refresh_token=; HttpOnly; Secure; SameSite=Lax; Path=/api/v1/auth; Max-Age=0
         */
        ClearRefreshCookie: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Đã tạo tài khoản; mail xác minh đã được gửi. */
            201: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *       "email": "an.nguyen@example.com"
                     *     }
                     */
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            /** @description Email đã được đăng ký. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/409",
                     *       "title": "Xung đột dữ liệu",
                     *       "status": 409,
                     *       "detail": "Email này đã được đăng ký.",
                     *       "instance": "/api/v1/auth/register",
                     *       "traceId": "9f2c7b1e4a6d4f0b8c3e5a7d9b1f3c5e"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Email đã được xác minh; tài khoản đăng nhập được. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "email": "an.nguyen@example.com",
                     *       "verifiedAt": "2026-09-08T03:14:07Z"
                     *     }
                     */
                    "application/json": components["schemas"]["VerifyEmailResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            /** @description Token đã hết hạn hoặc đã được dùng. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/410",
                     *       "title": "Liên kết không còn hiệu lực",
                     *       "status": 410,
                     *       "detail": "Liên kết xác minh đã hết hạn hoặc đã được sử dụng.",
                     *       "instance": "/api/v1/auth/verify-email",
                     *       "traceId": "4b8e1d3a7c9f4e2b6a0d8c5f3b7e1a94"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /**
             * @description Đăng nhập thành công. Access token nằm trong body (client giữ **trong memory**),
             *     refresh token nằm trong cookie `HttpOnly` — JS không đọc được và không cần đọc.
             */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SetRefreshCookie"];
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTkyZjNjMS04YTRlLTdjMzEtOWYyYS02YjVkNGUzYzJhMTAiLCJyb2xlIjoiVVNFUiJ9.signature",
                     *       "expiresIn": 900
                     *     }
                     */
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            /**
             * @description Sai thông tin đăng nhập. **Dùng chung cho cả email không tồn tại lẫn sai mật khẩu** —
             *     response phải giống hệt nhau (AC-02).
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/401",
                     *       "title": "Xác thực thất bại",
                     *       "status": 401,
                     *       "detail": "Email hoặc mật khẩu không đúng.",
                     *       "instance": "/api/v1/auth/login",
                     *       "traceId": "c1e5a9d3b7f24608a2c4e6b8d0f2a4c6"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Tài khoản chưa xác minh email (AC-04). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/403",
                     *       "title": "Bị từ chối",
                     *       "status": 403,
                     *       "detail": "Tài khoản chưa xác minh email. Vui lòng kiểm tra hộp thư.",
                     *       "instance": "/api/v1/auth/login",
                     *       "traceId": "7d3f1b5e9a2c4068b4d6f8a0c2e4b6d8"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /**
             * @description Tài khoản bị khóa tạm thời 15 phút do sai mật khẩu 5 lần **liên tiếp** (AC-03, FR-003) — đăng nhập
             *     đúng trước lần thứ 5 thì bộ đếm về 0; không có cửa sổ thời gian cho các lần sai.
             *     Tự mở lại sau khi hết thời gian khóa — GĐ1 không có endpoint mở khóa thủ công.
             */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/423",
                     *       "title": "Tài khoản tạm khóa",
                     *       "status": 423,
                     *       "detail": "Tài khoản tạm khóa do đăng nhập sai nhiều lần. Vui lòng thử lại sau 15 phút.",
                     *       "instance": "/api/v1/auth/login",
                     *       "traceId": "2a6c8e0b4d6f8a0c2e4b6d8f0a2c4e6b"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cặp token mới. Cookie refresh được thay bằng refresh token mới cùng chuỗi. */
            200: {
                headers: {
                    "Set-Cookie": components["headers"]["SetRefreshCookie"];
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.newtoken.signature",
                     *       "expiresIn": 900
                     *     }
                     */
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /**
             * @description Thiếu cookie, token không tồn tại, đã hết hạn, hoặc **bị phát hiện tái sử dụng** (khi
             *     đó cả `family_id` đã bị thu hồi).
             *
             *     Frontend gặp mã này **ở chính `/auth/refresh`** thì xóa access token trong memory và
             *     chuyển hướng về màn đăng nhập — không được thử refresh lại.
             */
            401: {
                headers: {
                    "Set-Cookie": components["headers"]["ClearRefreshCookie"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/401",
                     *       "title": "Phiên không hợp lệ",
                     *       "status": 401,
                     *       "detail": "Phiên đăng nhập không còn hiệu lực. Vui lòng đăng nhập lại.",
                     *       "instance": "/api/v1/auth/refresh",
                     *       "traceId": "8b0d2f4a6c8e0b2d4f6a8c0e2b4d6f8a"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã đăng xuất; cookie refresh đã bị xóa. */
            204: {
                headers: {
                    "Set-Cookie": components["headers"]["ClearRefreshCookie"];
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Thông tin người dùng đang đăng nhập. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *       "email": "an.nguyen@example.com",
                     *       "role": "USER",
                     *       "roleDisplayName": "Người dùng",
                     *       "emailVerifiedAt": "2026-09-08T03:14:07Z",
                     *       "status": "active",
                     *       "createdAt": "2026-09-08T03:10:22Z"
                     *     }
                     */
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
}
