/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Thông báo của tôi — nhóm vừa có sự kiện mới lên đầu
         * @description Sắp theo `updatedAt` giảm dần (rồi `notificationId` giảm dần), phân trang keyset. `updatedAt` là lúc sự kiện mới nhất dồn
         *     vào nhóm — đánh dấu đã đọc **không** đổi nó, nên đọc một thông báo không làm nó nhảy lên đầu.
         */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Số nhóm thông báo chưa đọc — badge của chuông
         * @description Đếm **nhóm** chưa đọc, không đếm sự kiện — mười người bình luận một bài vẫn là 1.
         */
        get: operations["countUnreadNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đánh dấu một thông báo đã đọc
         * @description Idempotent — thông báo đã đọc rồi vẫn trả 204. Không đổi `updatedAt`, không đổi thứ tự danh sách.
         *
         *     Thông báo không tồn tại **hoặc** không phải của người gọi → 403, **cùng** thân lỗi (dòng `NOTIF-IDOR` của AuthZ
         *     matrix): khác status ở đây thì status code tự nó tố cáo id nào có thật.
         */
        post: operations["markNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đánh dấu đã đọc mọi thông báo tới trước một mốc
         * @description Chỉ đánh dấu nhóm có `updatedAt ≤ upTo`. `upTo` bắt buộc — không có nó thì thông báo tới **sau** lúc người dùng mở
         *     chuông bị nuốt mất. FE gửi `updatedAt` của thông báo mới nhất đang hiển thị.
         */
        post: operations["markAllNotificationsRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 7807 Problem Details — dạng lỗi duy nhất của toàn dự án. Sinh bởi
         *     `SocialApp.SharedKernel.Errors.GlobalExceptionHandler`; `traceId` và `type` gắn thống nhất
         *     trong `AddSharedKernel`.
         */
        ProblemDetails: {
            /**
             * Format: uri
             * @description Mặc định `https://httpstatuses.io/{status}`. Nhóm này không có `type` riêng nào — FE không phải phân nhánh.
             */
            type?: string;
            /** @description Nhãn ngắn, ổn định theo loại lỗi. **Không** chứa dữ liệu người dùng. */
            title: string;
            /** Format: int32 */
            status: number;
            /** @description Thông điệp cho người đọc. Vắng mặt ở lỗi 500. */
            detail?: string | null;
            /** @description Path của request gây lỗi. */
            instance?: string;
            /** @description Bằng header `X-Correlation-ID` của chính request đó — dùng để tra log. */
            traceId: string;
            /** @description Chỉ có ở lỗi validation (400). Map `tên trường → danh sách thông điệp`. */
            errors?: {
                [key: string]: string[];
            } | null;
        };
        /**
         * @description Tám loại (Đ-6.17). `comment` bình luận bài của bạn · `reply` trả lời bình luận của bạn · `reaction` cảm xúc MỚI trên
         *     bài/bình luận của bạn · `friend_request` lời mời kết bạn · `friend_accepted` lời mời của bạn được chấp nhận ·
         *     `message` tin nhắn khi bạn offline · `moderation` nội dung của bạn bị ẩn · `tag` được nhắc tên trong bình luận.
         * @enum {string}
         */
        NotificationType: "comment" | "reply" | "reaction" | "friend_request" | "friend_accepted" | "message" | "moderation" | "tag";
        /**
         * @description Loại đích FE dẫn tới. `comment` luôn đi kèm `postId` để mở đúng bài.
         * @enum {string}
         */
        NotificationTargetType: "post" | "comment" | "user" | "conversation";
        /**
         * @description Lý do ẩn — cùng tập với `ReasonCode` của `moderation-v1`. FE hiển thị nhãn tiếng Việt: `spam` Spam · `harassment`
         *     Quấy rối · `nudity` Nội dung khỏa thân · `violence` Bạo lực · `other` Khác.
         * @enum {string}
         */
        ReasonCode: "spam" | "harassment" | "nudity" | "violence" | "other";
        /** @description Thẻ người dùng (tên hiển thị + ảnh đại diện) — hydrate từ hồ sơ lúc đọc, không lưu trong thông báo. */
        UserCard: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            /**
             * Format: uri
             * @description Presigned GET 15 phút, `null` khi chưa có ảnh đại diện.
             */
            avatarUrl: string | null;
        };
        NotificationTarget: {
            type: components["schemas"]["NotificationTargetType"];
            /**
             * Format: uuid
             * @description Id của đích — bài, bình luận, người dùng (người mời / người chấp nhận / chính bạn khi tài khoản bị ẩn), hội thoại.
             */
            id: string;
            /**
             * Format: uuid
             * @description Bài chứa đích — có khi đích là `post` hoặc `comment`; `null` với `user`, `conversation`.
             */
            postId: string | null;
        };
        /** @description Một NHÓM thông báo đã gộp. Mọi trường luôn có mặt; trường không áp dụng là `null`. */
        NotificationResponse: {
            /**
             * Format: uuid
             * @description Khóa khử trùng khi nối trang (và khi hub đẩy tới — C6).
             */
            notificationId: string;
            type: components["schemas"]["NotificationType"];
            /** @description Người gây ra sự kiện MỚI NHẤT. `null` với `moderation` và khi người đó không có hồ sơ. */
            actor: components["schemas"]["UserCard"] | null;
            /**
             * Format: int32
             * @description Số người KHÁC NHAU trong đợt hiện tại. Đọc nhóm rồi có người mới → đếm lại từ 1.
             */
            actorCount: number;
            target: components["schemas"]["NotificationTarget"];
            /** @description Chỉ có với `moderation`. */
            reasonCode: components["schemas"]["ReasonCode"] | null;
            isRead: boolean;
            /**
             * Format: date-time
             * @description Lúc nhóm ra đời.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Lúc sự kiện mới nhất dồn vào nhóm — khóa sắp danh sách. Đánh dấu đã đọc không đổi trường này.
             */
            updatedAt: string;
        };
        NotificationPage: {
            items: components["schemas"]["NotificationResponse"][];
            /** @description `null` khi hết dữ liệu. */
            nextCursor: string | null;
        };
        UnreadCount: {
            /**
             * Format: int32
             * @description Số NHÓM chưa đọc.
             */
            total: number;
        };
        ReadAllRequest: {
            /**
             * Format: date-time
             * @description Chỉ đánh dấu nhóm có `updatedAt ≤ upTo`.
             */
            upTo: string;
        };
    };
    responses: {
        /**
         * @description Dữ liệu đầu vào không hợp lệ. `errors` là map `tên trường → danh sách thông điệp`: `cursor` rác, `limit` ngoài `1..50`,
         *     `notificationId` sai dạng UUID, `upTo` thiếu hoặc sai dạng.
         */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/400",
                 *       "title": "Dữ liệu không hợp lệ",
                 *       "status": 400,
                 *       "detail": "Dữ liệu đầu vào không hợp lệ",
                 *       "instance": "/api/v1/notifications/read-all",
                 *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8",
                 *       "errors": {
                 *         "upTo": [
                 *           "Mốc thời gian là bắt buộc."
                 *         ]
                 *       }
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Thiếu access token, token sai chữ ký, hết hạn, hoặc đã bị thu hồi. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/401",
                 *       "title": "Chưa xác thực",
                 *       "status": 401,
                 *       "detail": "Yêu cầu access token hợp lệ.",
                 *       "instance": "/api/v1/notifications",
                 *       "traceId": "a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Tầng 3 — thông báo không phải của người gọi, **hoặc không tồn tại**: một thân lỗi cho cả hai (quy ước 3b). Thông điệp
         *     không nêu lý do.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/403",
                 *       "title": "Bị từ chối",
                 *       "status": 403,
                 *       "detail": "Bạn không có quyền thực hiện thao tác này.",
                 *       "instance": "/api/v1/notifications/0192f3d0-4a1b-7c2d-8e3f-9a0b1c2d3e4f/read",
                 *       "traceId": "c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Vượt hạn mức 100 req/phút/user (chung, ISS-04). Không có `Retry-After`. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/429",
                 *       "title": "Quá nhiều yêu cầu",
                 *       "status": 429,
                 *       "detail": "Bạn đã gửi quá nhiều yêu cầu. Vui lòng thử lại sau ít phút.",
                 *       "instance": "/api/v1/notifications/unread-count",
                 *       "traceId": "e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Lỗi không mong muốn. **Không bao giờ có `detail`** — `GlobalExceptionHandler` giấu chi tiết nội bộ, chỉ
         *     `traceId` đi ra ngoài để đối chiếu với log.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/500",
                 *       "title": "Đã xảy ra lỗi không mong muốn",
                 *       "status": 500,
                 *       "instance": "/api/v1/notifications",
                 *       "traceId": "b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description UUID của thông báo. Sai dạng → 400 `errors.notificationId`. */
        NotificationId: string;
        /** @description `nextCursor` của trang trước, opaque. Sai dạng → 400 `errors.cursor`. */
        Cursor: string;
        /** @description Số thông báo mỗi trang, `1..50`. Ngoài khoảng → 400 `errors.limit`. */
        Limit: number;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Correlation ID của request, bằng đúng `traceId` trong Problem Details khi có lỗi.
         *     Client gửi header cùng tên thì server dùng lại giá trị đó.
         * @example 9f2c7b1e4a6d4f0b8c3e5a7d9b1f3c5e
         */
        XCorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listNotifications: {
        parameters: {
            query?: {
                /** @description `nextCursor` của trang trước, opaque. Sai dạng → 400 `errors.cursor`. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Số thông báo mỗi trang, `1..50`. Ngoài khoảng → 400 `errors.limit`. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Một trang thông báo. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "notificationId": "0192f3d0-4a1b-7c2d-8e3f-9a0b1c2d3e4f",
                     *           "type": "comment",
                     *           "actor": {
                     *             "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *             "displayName": "Nguyễn Văn An",
                     *             "avatarUrl": null
                     *           },
                     *           "actorCount": 4,
                     *           "target": {
                     *             "type": "post",
                     *             "id": "0192f3c9-2b7d-7e10-8c4a-1f3e5d7b9a20",
                     *             "postId": "0192f3c9-2b7d-7e10-8c4a-1f3e5d7b9a20"
                     *           },
                     *           "reasonCode": null,
                     *           "isRead": false,
                     *           "createdAt": "2026-09-25T07:02:11.482913Z",
                     *           "updatedAt": "2026-09-25T08:15:42.123456Z"
                     *         },
                     *         {
                     *           "notificationId": "0192f3cf-11aa-7b22-9c33-4d44e55f6a77",
                     *           "type": "moderation",
                     *           "actor": null,
                     *           "actorCount": 1,
                     *           "target": {
                     *             "type": "post",
                     *             "id": "0192f3c2-5e6f-7a80-9b1c-2d3e4f5a6b7c",
                     *             "postId": "0192f3c2-5e6f-7a80-9b1c-2d3e4f5a6b7c"
                     *           },
                     *           "reasonCode": "spam",
                     *           "isRead": true,
                     *           "createdAt": "2026-09-24T21:40:03.000001Z",
                     *           "updatedAt": "2026-09-24T21:40:03.000001Z"
                     *         }
                     *       ],
                     *       "nextCursor": "MjAyNi0wOS0yNFQyMTo0MDowMy4wMDAwMDEwKzAwOjAwfDAxOTJmM2NmLTExYWEtN2IyMi05YzMzLTRkNDRlNTVmNmE3Nw"
                     *     }
                     */
                    "application/json": components["schemas"]["NotificationPage"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    countUnreadNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Số nhóm chưa đọc. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "total": 3
                     *     }
                     */
                    "application/json": components["schemas"]["UnreadCount"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    markNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID của thông báo. Sai dạng → 400 `errors.notificationId`. */
                notificationId: components["parameters"]["NotificationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã đánh dấu (hoặc đã đọc từ trước). */
            204: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    markAllNotificationsRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "upTo": "2026-09-25T08:15:42.123456Z"
                 *     }
                 */
                "application/json": components["schemas"]["ReadAllRequest"];
            };
        };
        responses: {
            /** @description Đã đánh dấu. */
            204: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
}
