using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SocialApp.Modules.Moderation.Domain;

namespace SocialApp.Modules.Moderation.Infrastructure.Configurations;

/// <summary>
/// Ánh xạ <see cref="AuditLog"/> → <c>moderation.audit_logs</c> (ENT-13, giai-doan-6.md Mục 4).
///
/// Luật append-only KHÔNG nằm ở đây — EF không biểu diễn được trigger. Nó nằm trong migration <c>InitialModeration</c>
/// (<c>migrationBuilder.Sql</c>, Đ-6.15).
///
/// Khóa <c>long</c> → Npgsql sinh <c>GENERATED BY DEFAULT AS IDENTITY</c>, tương đương <c>bigserial</c> của PTTK và là cách
/// chuẩn hiện nay. Không có index theo <c>action</c>: lọc theo action luôn đi kèm người thao tác, đối tượng hoặc khoảng id.
/// </summary>
internal sealed class AuditLogConfiguration : IEntityTypeConfiguration<AuditLog>
{
    public void Configure(EntityTypeBuilder<AuditLog> builder)
    {
        builder.ToTable("audit_logs");

        builder.HasKey(x => x.Id);
        builder.Property(x => x.Id).HasColumnName("id").UseIdentityByDefaultColumn();

        builder.Property(x => x.ActorId).HasColumnName("actor_id");
        builder.Property(x => x.Action).HasColumnName("action").HasMaxLength(50).IsRequired();
        builder.Property(x => x.TargetType).HasColumnName("target_type").HasMaxLength(20);
        builder.Property(x => x.TargetId).HasColumnName("target_id");
        builder.Property(x => x.Metadata).HasColumnName("metadata").HasColumnType("jsonb");
        builder.Property(x => x.Ip).HasColumnName("ip").HasColumnType("inet");
        builder.Property(x => x.CreatedAt).HasColumnName("created_at").HasDefaultValueSql("now()");

        // Hai đường đọc của GET /admin/audit-logs (D8): theo người thao tác, theo đối tượng — cả hai keyset id DESC.
        builder.HasIndex(x => new { x.ActorId, x.Id })
            .IsDescending(false, true)
            .HasDatabaseName("idx_audit_logs_actor");
        builder.HasIndex(x => new { x.TargetType, x.TargetId, x.Id })
            .IsDescending(false, false, true)
            .HasDatabaseName("idx_audit_logs_target");
    }
}
