// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SocialApp.Modules.Content.Infrastructure;

#nullable disable

namespace SocialApp.Modules.Content.Infrastructure.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20260924152107_Gd3Interactions")]
    partial class Gd3Interactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("content")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SocialApp.Modules.Content.Domain.Comment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid")
                        .HasColumnName("comment_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<short>("Depth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("depth");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<string>("ReactionCounts")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("reaction_counts")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("ReplyCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reply_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'visible'");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CommentId");

                    b.HasIndex("PostId")
                        .HasDatabaseName("IX_comments_post_id");

                    b.HasIndex("ParentId", "CreatedAt", "CommentId")
                        .HasDatabaseName("idx_comments_parent");

                    b.HasIndex("PostId", "CreatedAt", "CommentId")
                        .HasDatabaseName("idx_comments_post_roots")
                        .HasFilter("parent_id IS NULL");

                    b.ToTable("comments", "content", t =>
                        {
                            t.HasCheckConstraint("ck_comments_depth", "depth BETWEEN 1 AND 3");

                            t.HasCheckConstraint("ck_comments_reply_count", "reply_count >= 0");

                            t.HasCheckConstraint("ck_comments_root_depth", "(parent_id IS NULL) = (depth = 1)");

                            t.HasCheckConstraint("ck_comments_status", "status IN ('visible','deleted')");
                        });
                });

            modelBuilder.Entity("SocialApp.Modules.Content.Domain.MediaAttachment", b =>
                {
                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short?>("Height")
                        .HasColumnType("smallint")
                        .HasColumnName("height");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("owner_type");

                    b.Property<short>("Position")
                        .HasColumnType("smallint")
                        .HasColumnName("position");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("storage_key");

                    b.Property<short?>("Width")
                        .HasColumnType("smallint")
                        .HasColumnName("width");

                    b.HasKey("MediaId");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("OwnerType", "OwnerId")
                        .HasDatabaseName("idx_media_owner");

                    b.HasIndex("OwnerType", "OwnerId", "Position")
                        .IsUnique()
                        .HasDatabaseName("uq_media_owner_position");

                    b.ToTable("media_attachments", "content", t =>
                        {
                            t.HasCheckConstraint("ck_media_content_type", "content_type IN ('image/jpeg','image/png','image/webp')");

                            t.HasCheckConstraint("ck_media_owner_type", "owner_type IN ('post','message')");

                            t.HasCheckConstraint("ck_media_position", "position BETWEEN 0 AND 9");

                            t.HasCheckConstraint("ck_media_size", "size_bytes > 0 AND size_bytes <= 10485760");
                        });
                });

            modelBuilder.Entity("SocialApp.Modules.Content.Domain.Post", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid")
                        .HasColumnName("post_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("body");

                    b.Property<int>("CommentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("comment_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<string>("HiddenReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hidden_reason");

                    b.Property<short>("MediaCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("media_count");

                    b.Property<string>("Privacy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("privacy")
                        .HasDefaultValueSql("'public'");

                    b.Property<string>("ReactionCounts")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("reaction_counts")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'published'");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PostId");

                    b.HasIndex("CreatedAt", "PostId")
                        .IsDescending()
                        .HasDatabaseName("idx_posts_public_recent")
                        .HasFilter("status = 'published' AND privacy = 'public'");

                    b.HasIndex("AuthorId", "CreatedAt", "PostId")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("idx_posts_author_created")
                        .HasFilter("status = 'published'");

                    b.ToTable("posts", "content", t =>
                        {
                            t.HasCheckConstraint("ck_posts_comment_count", "comment_count >= 0");

                            t.HasCheckConstraint("ck_posts_media_count", "media_count BETWEEN 0 AND 10");

                            t.HasCheckConstraint("ck_posts_not_empty", "media_count > 0 OR btrim(coalesce(body,'')) <> ''");

                            t.HasCheckConstraint("ck_posts_privacy", "privacy IN ('public','friends','private')");

                            t.HasCheckConstraint("ck_posts_status", "status IN ('published','hidden','deleted')");
                        });
                });

            modelBuilder.Entity("SocialApp.Modules.Content.Domain.Reaction", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("target_type");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "TargetType", "TargetId");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("idx_reactions_target");

                    b.ToTable("reactions", "content", t =>
                        {
                            t.HasCheckConstraint("ck_reactions_target", "target_type IN ('post','comment')");

                            t.HasCheckConstraint("ck_reactions_type", "type IN ('like','love','haha','wow','sad','angry')");
                        });
                });

            modelBuilder.Entity("SocialApp.Modules.Content.Domain.Comment", b =>
                {
                    b.HasOne("SocialApp.Modules.Content.Domain.Comment", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SocialApp.Modules.Content.Domain.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
