// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SocialApp.Modules.SocialGraph.Infrastructure;

#nullable disable

namespace SocialApp.Modules.SocialGraph.Infrastructure.Migrations
{
    [DbContext(typeof(SocialGraphDbContext))]
    [Migration("20260921165316_InitialSocialGraph")]
    partial class InitialSocialGraph
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("socialgraph")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SocialApp.Modules.SocialGraph.Domain.Follow", b =>
                {
                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid")
                        .HasColumnName("follower_id");

                    b.Property<Guid>("FolloweeId")
                        .HasColumnType("uuid")
                        .HasColumnName("followee_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("FollowerId", "FolloweeId");

                    b.ToTable("follows", "socialgraph", t =>
                        {
                            t.HasCheckConstraint("ck_follows_not_self", "follower_id <> followee_id");
                        });
                });

            modelBuilder.Entity("SocialApp.Modules.SocialGraph.Domain.Friendship", b =>
                {
                    b.Property<Guid>("UserMinId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_min_id");

                    b.Property<Guid>("UserMaxId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_max_id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserMinId", "UserMaxId");

                    b.HasIndex("UserMaxId")
                        .HasDatabaseName("idx_friendships_user_max");

                    b.ToTable("friendships", "socialgraph", t =>
                        {
                            t.HasCheckConstraint("ck_friendships_accepted", "(status = 'accepted') = (accepted_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_friendships_order", "user_min_id < user_max_id");

                            t.HasCheckConstraint("ck_friendships_requester", "requester_id IN (user_min_id, user_max_id)");

                            t.HasCheckConstraint("ck_friendships_status", "status IN ('pending','accepted')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
