/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/friends/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lời mời đang chờ của chính người gọi — nhận được hoặc đã gửi
         * @description `[Authorize]`, không mã quyền: luôn là dữ liệu của chính người gọi (Đ-4.12). Chỉ lời mời `pending`; mới trước
         *     theo `created_at DESC`. `since` của mỗi thẻ là thời điểm gửi lời mời.
         *
         *     Người kia chưa có hồ sơ (hoặc hồ sơ đã mất) thì thẻ đó **vắng mặt** — trang có thể ngắn hơn `limit`.
         */
        get: operations["listFriendRequests"];
        put?: never;
        /**
         * Gửi lời mời kết bạn (UC-10, FR-010, BR-03)
         * @description Thứ tự kiểm là **một phần của hợp đồng** vì nó quyết định mã lỗi (Mục 6.1):
         *
         *     1. Tầng 2: quyền `friend.request`.
         *     2. `userId` là chính người gọi → **400** `errors.userId` (US-010 AC-03). Kiểm **trước** khi chạm DB.
         *     3. `userId` không có hồ sơ (tra `IUserDirectory`) → **404**: người chưa onboarding không tồn tại với phần còn
         *        lại của hệ thống (Đ-2.4).
         *     4. INSERT cặp chuẩn hóa `(min, max)`, `status = 'pending'`, `requester = người gọi`. Đã có lời mời hoặc quan hệ
         *        bạn bè **theo bất kỳ chiều nào** (kể cả B đã gửi cho A) → đụng PK → **409**. Hai lời mời chéo nhau cùng lúc:
         *        một cái thành công, cái kia 409 — không bao giờ 500 (AC-02).
         *
         *     Server **không** tự chấp nhận hộ khi người kia đã gửi lời mời trước — FE đọc `GET /relationships/{userId}` nên
         *     thường hiện nút "Chấp nhận" chứ không để người dùng bấm "Kết bạn" ở tình huống đó.
         */
        post: operations["sendFriendRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/requests/{userId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chấp nhận lời mời mà `userId` gửi tới người gọi (UC-10 bước 3)
         * @description Tầng 2: `friend.respond`. Tầng 3 là **một câu `UPDATE` có điều kiện** (Đ-4.14): cặp chuẩn hóa từ
         *     (người gọi, `userId`), `status = 'pending'`, **`requester_id = userId`** — tức người gọi phải là người **nhận**.
         *
         *     0 dòng bị đổi → **403**, **một** phản hồi cho mọi lý do: không có lời mời nào · lời mời do chính người gọi gửi
         *     (tự chấp nhận lời mời của mình, `TC-A03-friend-self-accept`) · đã là bạn · người gọi là người thứ ba
         *     (`TC-A03-friend-accept`, US-010 AC-04). Không có `SELECT` rồi mới `UPDATE` nên không có cửa sổ race.
         */
        post: operations["acceptFriendRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/requests/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Hủy lời mình đã gửi, hoặc từ chối lời mời nhận được (FR-011)
         * @description `[Authorize]`, không mã quyền (Đ-4.12). Xóa lời mời `pending` giữa người gọi và `userId`, **theo chiều nào cũng
         *     được** — cùng một endpoint cho "hủy" (tôi gửi) và "từ chối" (tôi nhận). Từ chối là **xóa dòng**, không có trạng
         *     thái "đã từ chối": người kia gửi lại được (FRD-07).
         *
         *     Idempotent: không có lời mời nào (hoặc hai người đã là bạn) → vẫn **204**, không đụng gì. Quan hệ đã `accepted`
         *     **không** bị xóa ở đây — hủy kết bạn là `DELETE /friends/{userId}`.
         */
        delete: operations["deleteFriendRequest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bạn bè của chính người gọi, mới kết bạn trước
         * @description `[Authorize]`, không mã quyền: luôn là dữ liệu của chính người gọi (Đ-4.12). Sắp theo `accepted_at DESC`;
         *     `since` của mỗi thẻ là thời điểm trở thành bạn.
         *
         *     Cursor opaque cùng bộ mã hóa keyset của GĐ2 (`thời điểm|id của người kia`) — FE chỉ chuyển tiếp `nextCursor`.
         *     Người kia chưa có hồ sơ thì thẻ đó **vắng mặt** — trang có thể ngắn hơn `limit`.
         */
        get: operations["listFriends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/friends/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Hủy kết bạn (FR-011)
         * @description `[Authorize]`, không mã quyền (Đ-4.12): người bị Admin gỡ quyền kết bạn vẫn phải hủy kết bạn được. Xóa quan hệ
         *     `accepted` giữa người gọi và `userId`.
         *
         *     Có hiệu lực **ngay** với `GET /posts/{id}` (`IFriendshipReader` không cache, Đ-4.3) và với feed kế tiếp của cả
         *     hai người (FRD-09, Mục 7.3). Dòng theo dõi riêng (nếu có) **không** bị xóa theo (Đ-4.5).
         *
         *     Idempotent: không phải bạn → vẫn **204**. Lời mời `pending` **không** bị xóa ở đây.
         */
        delete: operations["unfriend"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/follows/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Theo dõi một người (UC-13, FR-012)
         * @description Tầng 2: `friend.request` (Đ-4.12 — cùng là "chủ động tạo một kết nối xã hội"). `userId` là chính người gọi →
         *     **400** `errors.userId`; không có hồ sơ → **404**.
         *
         *     `INSERT … ON CONFLICT DO NOTHING`: đã theo dõi rồi → vẫn **204** (idempotent — vì vậy là `PUT`, không phải
         *     `POST`). Theo dõi không cần người kia đồng ý và không tạo lời mời kết bạn nào.
         */
        put: operations["follow"];
        post?: never;
        /**
         * Bỏ theo dõi
         * @description `[Authorize]`, không mã quyền (Đ-4.12). Idempotent: chưa theo dõi → vẫn **204**. Không chạm quan hệ bạn bè
         *     (Đ-4.5): bỏ theo dõi một người bạn thì vẫn là bạn, vẫn thấy bài của họ trong feed.
         */
        delete: operations["unfollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relationships/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quan hệ giữa người gọi và `userId` — để vẽ nút trên trang hồ sơ (Đ-4.16)
         * @description `[Authorize]`, không mã quyền. Hai sự thật độc lập (Đ-4.5): `friendship` (bốn trạng thái, nhìn **từ phía người
         *     gọi**) và `following` (người gọi có đang theo dõi `userId` không).
         *
         *     `userId` là chính người gọi → **400** `errors.userId` (không có quan hệ nào với chính mình để hỏi). `userId` không
         *     tồn tại → **200** `{ friendship: "none", following: false }`, không 404: endpoint này không tiết lộ ai có tài
         *     khoản.
         */
        get: operations["getRelationship"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 7807 Problem Details — dạng lỗi duy nhất của toàn dự án. Sinh bởi
         *     `SocialApp.SharedKernel.Errors.GlobalExceptionHandler`; `traceId` và `type` gắn thống nhất
         *     trong `AddSharedKernel`.
         */
        ProblemDetails: {
            /**
             * Format: uri
             * @description Mặc định `https://httpstatuses.io/{status}`.
             */
            type?: string;
            /** @description Nhãn ngắn, ổn định theo loại lỗi. **Không** chứa dữ liệu người dùng. */
            title: string;
            /** Format: int32 */
            status: number;
            /** @description Thông điệp cho người đọc. Vắng mặt ở lỗi 500. */
            detail?: string | null;
            /** @description Path của request gây lỗi. */
            instance?: string;
            /** @description Bằng header `X-Correlation-ID` của chính request đó — dùng để tra log. */
            traceId: string;
            /** @description Chỉ có ở lỗi validation (400). Map `tên trường → danh sách thông điệp`. */
            errors?: {
                [key: string]: string[];
            } | null;
        };
        /** @description Chỉ MỘT id — người kia. Người gửi luôn là người gọi (Mục 6.2), không nhận từ body. */
        CreateFriendRequest: {
            /**
             * Format: uuid
             * @description Người được mời. Là chính người gọi → 400 `errors.userId`.
             */
            userId: string;
        };
        /**
         * @description Nhìn **từ phía người gọi** — trùng tên `FriendshipView` ở `SocialGraph.Domain` (khối A, lệch L1):
         *     `none` chưa có gì · `outgoing` tôi đã gửi lời mời · `incoming` người kia gửi cho tôi · `friends` đã là bạn.
         * @enum {string}
         */
        FriendshipState: "none" | "outgoing" | "incoming" | "friends";
        /**
         * @default incoming
         * @enum {string}
         */
        FriendRequestDirection: "incoming" | "outgoing";
        /** @description Trả từ mọi thao tác ghi có body, để FE vẽ lại nút mà không gọi thêm `GET` (Mục 7.1). */
        RelationshipResponse: {
            /**
             * Format: uuid
             * @description Người kia trong quan hệ.
             */
            userId: string;
            friendship: components["schemas"]["FriendshipState"];
            /** @description Người gọi có đang theo dõi `userId` không. **Độc lập** với `friendship` (Đ-4.5). */
            following: boolean;
        };
        /**
         * @description Cùng hình dạng `PostAuthor` của `content-v1` nhưng **định nghĩa lại ở đây** (Mục 8.1): hai file hợp đồng độc
         *     lập, không `$ref` chéo file. Từ `IUserDirectory` — một lời gọi batch cho cả trang.
         */
        UserCard: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            /**
             * Format: uri
             * @description Presigned GET 15 phút, `null` khi chưa có avatar.
             */
            avatarUrl?: string | null;
        };
        FriendCard: {
            user: components["schemas"]["UserCard"];
            /**
             * Format: date-time
             * @description Danh sách bạn bè → thời điểm trở thành bạn (`accepted_at`); danh sách lời mời → thời điểm gửi (`created_at`).
             */
            since: string;
        };
        /** @description Bạn bè, `accepted_at DESC`. */
        FriendPage: {
            items: components["schemas"]["FriendCard"][];
            /** @description Opaque. `items` có thể ít hơn `limit`. Hết dữ liệu khi và chỉ khi `nextCursor` là `null`. */
            nextCursor: string | null;
        };
        /** @description Lời mời `pending`, `created_at DESC`. */
        FriendRequestPage: {
            items: components["schemas"]["FriendCard"][];
            /** @description Opaque. `items` có thể ít hơn `limit`. Hết dữ liệu khi và chỉ khi `nextCursor` là `null`. */
            nextCursor: string | null;
        };
    };
    responses: {
        /**
         * @description Dữ liệu đầu vào không hợp lệ. `errors` là map `tên trường → danh sách thông điệp`.
         *
         *     Cũng là mã trả về khi body chứa **field lạ** (`UnmappedMemberHandling = Disallow`, AGENTS.md Mục 9), khi tham số
         *     path sai dạng UUID, khi `cursor` rác, `limit` ngoài `1..50`, hay `direction` lạ.
         */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/400",
                 *       "title": "Dữ liệu không hợp lệ",
                 *       "status": 400,
                 *       "detail": "Dữ liệu đầu vào không hợp lệ",
                 *       "instance": "/api/v1/friends",
                 *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8",
                 *       "errors": {
                 *         "cursor": [
                 *           "Cursor không hợp lệ."
                 *         ]
                 *       }
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Thiếu access token, token sai chữ ký, hết hạn, hoặc đã bị thu hồi. Dòng `TC-A01-friends` của AuthZ matrix. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/401",
                 *       "title": "Chưa xác thực",
                 *       "status": 401,
                 *       "detail": "Yêu cầu access token hợp lệ.",
                 *       "instance": "/api/v1/friends/requests",
                 *       "traceId": "a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Tầng 2 (thiếu `friend.request` / `friend.respond`) hoặc tầng 3 từ chối. Ở chấp nhận lời mời: không có lời mời,
         *     lời mời do chính mình gửi, đã là bạn, hay người gọi là người thứ ba đều trả **cùng** phản hồi này (Đ-4.14) —
         *     thông điệp không nêu lý do.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/403",
                 *       "title": "Bị từ chối",
                 *       "status": 403,
                 *       "detail": "Bạn không có quyền thực hiện thao tác này.",
                 *       "instance": "/api/v1/friends/requests/0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10/accept",
                 *       "traceId": "c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Người được mời / được theo dõi không có hồ sơ (Đ-2.4) — kể cả khi tài khoản tồn tại nhưng chưa onboarding. */
        UserNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/404",
                 *       "title": "Không tìm thấy tài nguyên",
                 *       "status": 404,
                 *       "detail": "Không tìm thấy người dùng.",
                 *       "instance": "/api/v1/friends/requests",
                 *       "traceId": "d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Vượt hạn mức 100 req/phút/user (ISS-04). Không có `Retry-After`. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/429",
                 *       "title": "Quá nhiều yêu cầu",
                 *       "status": 429,
                 *       "detail": "Bạn đã gửi quá nhiều yêu cầu. Vui lòng thử lại sau ít phút.",
                 *       "instance": "/api/v1/friends",
                 *       "traceId": "e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Lỗi không mong muốn. **Không bao giờ có `detail`** — `GlobalExceptionHandler` giấu chi tiết nội bộ, chỉ
         *     `traceId` đi ra ngoài để đối chiếu với log.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/500",
                 *       "title": "Đã xảy ra lỗi không mong muốn",
                 *       "status": 500,
                 *       "instance": "/api/v1/friends",
                 *       "traceId": "b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description UUID v7 của người kia trong quan hệ. Sai dạng → 400 `errors.userId`. */
        UserId: string;
        /** @description `nextCursor` của trang trước. Bỏ trống để lấy trang đầu. Cursor rác → 400 `errors.cursor`. */
        Cursor: string;
        /** @description Số thẻ mỗi trang, mặc định 20, tối đa 50 (AGENTS.md Mục 9). Ngoài `1..50` → 400 `errors.limit`. */
        Limit: number;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Correlation ID của request, bằng đúng `traceId` trong Problem Details khi có lỗi.
         *     Client gửi header cùng tên thì server dùng lại giá trị đó.
         * @example 9f2c7b1e4a6d4f0b8c3e5a7d9b1f3c5e
         */
        XCorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listFriendRequests: {
        parameters: {
            query?: {
                /** @description `incoming` = người khác gửi cho tôi (mặc định) · `outgoing` = tôi gửi đi. Giá trị khác → 400 `errors.direction`. */
                direction?: components["schemas"]["FriendRequestDirection"];
                /** @description `nextCursor` của trang trước. Bỏ trống để lấy trang đầu. Cursor rác → 400 `errors.cursor`. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Số thẻ mỗi trang, mặc định 20, tối đa 50 (AGENTS.md Mục 9). Ngoài `1..50` → 400 `errors.limit`. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Một trang lời mời. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendRequestPage"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    sendFriendRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10"
                 *     }
                 */
                "application/json": components["schemas"]["CreateFriendRequest"];
            };
        };
        responses: {
            /** @description Lời mời đã gửi — `friendship` là `outgoing`. */
            201: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *       "friendship": "outgoing",
                     *       "following": false
                     *     }
                     */
                    "application/json": components["schemas"]["RelationshipResponse"];
                };
            };
            /** @description `userId` thiếu, sai dạng UUID, hoặc là chính người gọi. `errors.userId`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/400",
                     *       "title": "Dữ liệu không hợp lệ",
                     *       "status": 400,
                     *       "detail": "Dữ liệu đầu vào không hợp lệ",
                     *       "instance": "/api/v1/friends/requests",
                     *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8",
                     *       "errors": {
                     *         "userId": [
                     *           "Không thể gửi lời mời kết bạn cho chính mình."
                     *         ]
                     *       }
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
            /** @description Đã có lời mời (theo bất kỳ chiều nào) hoặc đã là bạn (FRD-06). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/409",
                     *       "title": "Xung đột dữ liệu",
                     *       "status": 409,
                     *       "detail": "Đã có lời mời hoặc quan hệ bạn bè giữa hai người.",
                     *       "instance": "/api/v1/friends/requests",
                     *       "traceId": "9f2c7b1e4a6d4f0b8c3e5a7d9b1f3c5e"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    acceptFriendRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 của người kia trong quan hệ. Sai dạng → 400 `errors.userId`. */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã là bạn — `friendship` là `friends`. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *       "friendship": "friends",
                     *       "following": false
                     *     }
                     */
                    "application/json": components["schemas"]["RelationshipResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteFriendRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 của người kia trong quan hệ. Sai dạng → 400 `errors.userId`. */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Không còn lời mời nào giữa hai người. */
            204: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    listFriends: {
        parameters: {
            query?: {
                /** @description `nextCursor` của trang trước. Bỏ trống để lấy trang đầu. Cursor rác → 400 `errors.cursor`. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Số thẻ mỗi trang, mặc định 20, tối đa 50 (AGENTS.md Mục 9). Ngoài `1..50` → 400 `errors.limit`. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Một trang bạn bè. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendPage"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    unfriend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 của người kia trong quan hệ. Sai dạng → 400 `errors.userId`. */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hai người không còn là bạn. */
            204: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    follow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 của người kia trong quan hệ. Sai dạng → 400 `errors.userId`. */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Người gọi đang theo dõi `userId`. */
            204: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `userId` sai dạng UUID, hoặc là chính người gọi. `errors.userId`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/400",
                     *       "title": "Dữ liệu không hợp lệ",
                     *       "status": 400,
                     *       "detail": "Dữ liệu đầu vào không hợp lệ",
                     *       "instance": "/api/v1/follows/0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8",
                     *       "errors": {
                     *         "userId": [
                     *           "Không thể theo dõi chính mình."
                     *         ]
                     *       }
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    unfollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 của người kia trong quan hệ. Sai dạng → 400 `errors.userId`. */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Người gọi không còn theo dõi `userId`. */
            204: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getRelationship: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 của người kia trong quan hệ. Sai dạng → 400 `errors.userId`. */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quan hệ hiện tại. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *       "friendship": "incoming",
                     *       "following": true
                     *     }
                     */
                    "application/json": components["schemas"]["RelationshipResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
}
