// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SocialApp.Modules.Moderation.Infrastructure;

#nullable disable

namespace SocialApp.Modules.Moderation.Infrastructure.Migrations
{
    [DbContext(typeof(ModerationDbContext))]
    [Migration("20260923151519_InitialModeration")]
    partial class InitialModeration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("moderation")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SocialApp.Modules.Moderation.Domain.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<IPAddress>("Ip")
                        .HasColumnType("inet")
                        .HasColumnName("ip");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("ActorId", "Id")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_audit_logs_actor");

                    b.HasIndex("TargetType", "TargetId", "Id")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_audit_logs_target");

                    b.ToTable("audit_logs", "moderation");
                });

            modelBuilder.Entity("SocialApp.Modules.Moderation.Domain.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Detail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detail");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reason_code");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolverId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolver_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("open")
                        .HasColumnName("status");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("target_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("idx_reports_open_queue")
                        .HasFilter("status = 'open'");

                    b.HasIndex("ReporterId", "TargetType", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("uq_reports_open_per_reporter")
                        .HasFilter("status = 'open'");

                    b.HasIndex("TargetType", "TargetId", "Status")
                        .HasDatabaseName("idx_reports_target");

                    b.ToTable("reports", "moderation", t =>
                        {
                            t.HasCheckConstraint("ck_reports_decided", "(status = 'open') = (resolved_at IS NULL AND resolver_id IS NULL)");

                            t.HasCheckConstraint("ck_reports_other_detail", "reason_code <> 'other' OR detail IS NOT NULL");

                            t.HasCheckConstraint("ck_reports_reason", "reason_code IN ('spam','harassment','nudity','violence','other')");

                            t.HasCheckConstraint("ck_reports_status", "status IN ('open','resolved','dismissed')");

                            t.HasCheckConstraint("ck_reports_target_type", "target_type IN ('post','comment','user')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
