/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/realtime/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Xin vé bắt tay hub (Đ-E16, Đ-5.9)
         * @description Vé 32 byte ngẫu nhiên, sống **30 giây**, dùng **một lần** — lưu băm trong Redis, không lưu thô. Danh tính của vé lấy từ
         *     access token của chính request này. Dùng cho mọi `/hubs/*`.
         *
         *     **503** khi Redis không sẵn sàng (không fail-open): client chuyển fallback REST (gửi bằng `POST …/messages`, nhận bằng
         *     hỏi lại `afterSeq` mỗi 3 giây — Đ-5.12). Phân nhánh bằng `type` `urn:socialapp:problem:realtime-unavailable`.
         */
        post: operations["issueRealtimeTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details — dạng lỗi duy nhất của toàn dự án (SharedKernel dựng, module không tự chế). */
        ProblemDetails: {
            /** @description Mặc định `https://httpstatuses.io/{status}`; lỗi có nghĩa riêng dùng `urn:socialapp:problem:*`. */
            type?: string;
            title: string;
            /** Format: int32 */
            status: number;
            /** @description Thông điệp cho người đọc. Vắng mặt ở lỗi 500. */
            detail?: string | null;
            instance?: string;
            traceId: string;
            /** @description Chỉ có ở lỗi validation (400). Map `tên trường → danh sách thông điệp`. */
            errors?: {
                [key: string]: string[];
            } | null;
        };
        RealtimeTicket: {
            /** @description base64url của 32 byte ngẫu nhiên. Đặt vào `?access_token=` khi nối `/hubs/*`. Dùng MỘT lần. */
            ticket: string;
            /**
             * Format: int32
             * @description Số giây còn hiệu lực — luôn 30.
             */
            expiresIn: number;
        };
        /** @description Chỉ MỘT id — người kia. Người gọi luôn là thành viên còn lại (không nhận từ body). */
        CreateConversation: {
            /**
             * Format: uuid
             * @description Người muốn nhắn. Là chính người gọi → 400 `errors.userId`.
             */
            userId: string;
        };
        /**
         * @description Cùng hình dạng `UserCard` của `socialgraph-v1` nhưng **định nghĩa lại ở đây** — hai file hợp đồng độc lập, không `$ref`
         *     chéo file. Từ `IUserDirectory` — một lời gọi batch cho cả trang.
         */
        UserCard: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            /**
             * Format: uri
             * @description Presigned GET 15 phút, `null` khi chưa có avatar.
             */
            avatarUrl?: string | null;
        };
        /**
         * @description Một tin. **Không** có trường `status` (Đ-5.6): trạng thái tin của mình suy từ `peerDeliveredSeq` / `peerSeenSeq` của
         *     hội thoại và sự kiện hub `ReceiptUpdated`. Cùng hình dạng payload của sự kiện hub `MessageReceived`.
         */
        MessageResponse: {
            /**
             * Format: uuid
             * @description Khóa khử trùng ở client.
             */
            messageId: string;
            /** Format: uuid */
            conversationId: string;
            /** Format: uuid */
            senderId: string;
            /**
             * Format: int64
             * @description Thứ tự trong hội thoại, 1, 2, 3… không lỗ. Thứ tự DUY NHẤT đáng tin.
             */
            seq: number;
            content: string;
            /**
             * Format: uuid
             * @description Khóa idempotency do client sinh — tin optimistic khớp với tin server theo trường này.
             */
            clientMsgId: string;
            /** Format: date-time */
            createdAt: string;
        };
        ConversationResponse: {
            /** Format: uuid */
            conversationId: string;
            peer: components["schemas"]["UserCard"];
            /** @description `null` khi hội thoại chưa có tin. */
            lastMessage?: components["schemas"]["MessageResponse"] | null;
            /**
             * Format: int64
             * @description Số tin của NGƯỜI KIA mà người gọi chưa xem (Đ-5.14).
             */
            unreadCount: number;
            /**
             * Format: int64
             * @description Người kia đã nhận mọi tin có `seq` ≤ giá trị này.
             */
            peerDeliveredSeq: number;
            /**
             * Format: int64
             * @description Người kia đã xem mọi tin có `seq` ≤ giá trị này.
             */
            peerSeenSeq: number;
            /**
             * @description Có gửi tin được không (hai người còn là bạn — BR-09, tính sống). CHỈ có ở `GET /conversations/{id}` và
             *     `POST /conversations`; `null` trong danh sách (Đ-5.3 — tránh N+1).
             */
            canSend?: boolean | null;
        };
        /** @description Hội thoại đã có tin, `lastMessage.createdAt DESC`. Hội thoại rỗng không có ở đây. */
        ConversationPage: {
            items: components["schemas"]["ConversationResponse"][];
            /** @description Opaque. Hết dữ liệu khi và chỉ khi `nextCursor` là `null`. */
            nextCursor: string | null;
        };
        UnreadCount: {
            /**
             * Format: int64
             * @description Tổng tin chưa đọc trên mọi hội thoại — số trên badge.
             */
            total: number;
        };
        SendMessageRequest: {
            /** @description 1–2000 ký tự (đếm theo code point), không toàn khoảng trắng. */
            content: string;
            /**
             * Format: uuid
             * @description Client sinh (`crypto.randomUUID()`) trước khi gửi; gửi lại dùng LẠI giá trị này.
             */
            clientMsgId: string;
        };
        /** @description Không tham số hoặc có `cursor`: `seq DESC` (cuộn ngược). Có `afterSeq`: `seq ASC` và `nextCursor` luôn `null`. */
        MessagePage: {
            items: components["schemas"]["MessageResponse"][];
            /** @description Opaque. Hết lịch sử khi và chỉ khi `nextCursor` là `null`. */
            nextCursor: string | null;
        };
        /**
         * @description `seen` kéo theo `delivered`.
         * @enum {string}
         */
        ReceiptKind: "delivered" | "seen";
        ReceiptRequest: {
            kind: components["schemas"]["ReceiptKind"];
            /**
             * Format: int64
             * @description Đã nhận/đã xem mọi tin có `seq` ≤ giá trị này. Lớn hơn tin cuối → server kẹp, không lỗi.
             */
            upToSeq: number;
        };
    };
    responses: {
        /**
         * @description Dữ liệu đầu vào không hợp lệ. `errors` là map `tên trường → danh sách thông điệp`. Cũng là mã trả về khi body chứa
         *     **field lạ**, khi tham số path sai dạng UUID, khi `cursor` rác, `limit` ngoài `1..50`, hay `cursor` đi cùng `afterSeq`.
         */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/400",
                 *       "title": "Dữ liệu không hợp lệ",
                 *       "status": 400,
                 *       "detail": "Dữ liệu đầu vào không hợp lệ",
                 *       "instance": "/api/v1/conversations/0192f3c1-9b2d-7e40-8a11-3c5d7e9f1a20/messages",
                 *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8",
                 *       "errors": {
                 *         "content": [
                 *           "Tin nhắn không được để trống."
                 *         ]
                 *       }
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Thiếu access token, token sai chữ ký, hết hạn, hoặc đã bị thu hồi. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/401",
                 *       "title": "Chưa xác thực",
                 *       "status": 401,
                 *       "detail": "Yêu cầu access token hợp lệ.",
                 *       "instance": "/api/v1/conversations",
                 *       "traceId": "a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Tầng 2 (thiếu `message.send`) hoặc tầng 3: không phải thành viên của hội thoại, hoặc hội thoại không tồn tại — **cùng**
         *     một phản hồi `auth.forbidden` (Mục 6.1, TC-A04), không tiết lộ id hội thoại có thật hay không.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/403",
                 *       "title": "Bị từ chối",
                 *       "status": 403,
                 *       "detail": "Bạn không có quyền thực hiện thao tác này.",
                 *       "instance": "/api/v1/conversations/0192f3c1-9b2d-7e40-8a11-3c5d7e9f1a20",
                 *       "traceId": "c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Vượt hạn mức (100 req/phút/user; vé 20 req/phút/user). Không có `Retry-After`. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/429",
                 *       "title": "Quá nhiều yêu cầu",
                 *       "status": 429,
                 *       "detail": "Bạn đã gửi quá nhiều yêu cầu. Vui lòng thử lại sau ít phút.",
                 *       "instance": "/api/v1/realtime/tickets",
                 *       "traceId": "e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Redis không sẵn sàng nên không cấp được vé (Đ-5.9 — không fail-open). Client chuyển fallback REST (Đ-5.12). Phân nhánh
         *     theo `type`, không theo status: 503 này khác 503 "feed quá tải" của `content-v1`.
         */
        RealtimeUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:socialapp:problem:realtime-unavailable",
                 *       "title": "Kênh thời gian thực không sẵn sàng",
                 *       "status": 503,
                 *       "detail": "Kênh thời gian thực tạm thời không sẵn sàng. Tin nhắn vẫn gửi được.",
                 *       "instance": "/api/v1/realtime/tickets",
                 *       "traceId": "f2a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description UUID v7 của hội thoại. Sai dạng → 400 `errors.conversationId`. */
        ConversationId: string;
        /** @description `nextCursor` của trang trước. Bỏ trống để lấy trang đầu. Cursor rác → 400 `errors.cursor`. */
        Cursor: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Correlation ID của request, bằng đúng `traceId` trong Problem Details khi có lỗi.
         *     Client gửi header cùng tên thì server dùng lại giá trị đó.
         * @example 9f2c7b1e4a6d4f0b8c3e5a7d9b1f3c5e
         */
        XCorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    issueRealtimeTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vé vừa cấp. */
            201: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "ticket": "q3Xk9vVh2mS0bE7rT1uYw5Zc8NdLfJpA4GiHoKsRtUe",
                     *       "expiresIn": 30
                     *     }
                     */
                    "application/json": components["schemas"]["RealtimeTicket"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["RealtimeUnavailable"];
        };
    };
}
