/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hàng đợi kiểm duyệt — mỗi đối tượng bị báo một dòng, cũ nhất trước
         * @description Tầng 2: `report.resolve` (MODERATOR, ADMIN có). Endpoint đặc quyền: fail-closed khi không kiểm được thu hồi
         *     (503 `revocation-unavailable`), bị từ chối thì ghi nhật ký kiểm toán `access.denied`.
         *
         *     Báo cáo **đang mở** gom theo đối tượng (Đ-6.13): ba người báo cùng một bài là **một** dòng `reportCount: 3`.
         *     Sắp theo `firstReportedAt` tăng dần (báo cáo mở cũ nhất của đối tượng), hòa thì theo `target.id`. `reportId` là
         *     báo cáo mở cũ nhất của đối tượng — mở chi tiết bằng id này; nó không đổi giữa các lần tải.
         *
         *     Hết dữ liệu khi và chỉ khi `nextCursor` là `null`. Cursor opaque — không tự dựng.
         */
        get: operations["listReports"];
        put?: never;
        /**
         * Báo cáo một bài viết, bình luận hoặc tài khoản
         * @description Tầng 2: `report.create` (người dùng thường có). Người báo là người gọi — không nhận từ body.
         *
         *     | Tình huống | Phản hồi |
         *     |---|---|
         *     | Báo cáo mới | **201** `ReportReceipt` |
         *     | Đã có báo cáo **đang mở** của chính người này cho cùng đối tượng (bấm hai lần, hai tab) | **200** — CHÍNH báo cáo đó, cùng `reportId` |
         *     | Báo cáo cũ đã được xử lý rồi báo lại | **201** — báo cáo mới |
         *     | Đối tượng không tồn tại, đã bị ẩn/xóa, **hoặc người gọi không được xem** | **404** — một thân lỗi cho mọi trường hợp |
         *     | Báo cáo nội dung/tài khoản của chính mình | 400 `errors.targetId` |
         *     | Quá 10 báo cáo trong một phút (báo trùng vẫn tính) | 429 |
         *
         *     "Được xem" theo đúng luật đọc của đối tượng: bài `private` của người khác, bài `friends` của người không phải
         *     bạn → 404 như bài không tồn tại (Đ-6.12). `targetType: comment` hợp lệ nhưng chưa có module bình luận → 404.
         *
         *     `detail`: cắt khoảng trắng hai đầu; chỉ có khoảng trắng coi như **vắng mặt**. Bắt buộc khi `reasonCode: other`.
         *
         *     Phản hồi **không** nhắc lại đối tượng bị báo — không xác nhận thêm điều gì về nó.
         */
        post: operations["createReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết báo cáo — nội dung thật của đối tượng, báo cáo đang mở, lịch sử quyết định
         * @description Tầng 2: `report.resolve`. Endpoint đặc quyền như `GET /reports`.
         *
         *     - `target` là ảnh chụp **tại lúc đọc**, kể cả bài `private`/`friends`, đã bị ẩn hay đã xóa mềm — Moderator phải thấy
         *       nội dung mới quyết được. Đây là đường **duy nhất** Moderator đọc nội dung không công khai (`GET /posts/{id}` trả
         *       404 cho họ với bài bị ẩn). Đối tượng không còn trong bảng nào → `status: deleted`, `author`, `body`, `createdAt` là
         *       `null`.
         *     - `openReports`: mọi báo cáo **đang mở** của cùng đối tượng, cũ nhất trước — quyết định (D7c) đóng tất cả cùng lúc.
         *     - `history`: mỗi quyết định đã có một dòng, cũ nhất trước.
         *     - **Không có người báo** ở bất kỳ trường nào — quyết theo nội dung, không theo người báo.
         *
         *     Báo cáo đã đóng vẫn mở được (xem lại lịch sử). Báo cáo không tồn tại → 404.
         */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Quyết định một báo cáo — ẩn, bỏ qua hoặc đã xử lý; đóng MỌI báo cáo mở của cùng đối tượng
         * @description Tầng 2: `report.resolve`. `decision: hide` cần **thêm** `post.hide` (Đ-6.9) — thiếu thì 403 và một dòng nhật ký
         *     `access.denied`, kể cả khi báo cáo không tồn tại. Endpoint đặc quyền như `GET /reports`.
         *
         *     | `decision` | Áp cho | Làm gì |
         *     |---|---|---|
         *     | `hide` | bài, bình luận | Ẩn đối tượng (tác giả thấy biểu ngữ kèm lý do, người khác 404) + thông báo tác giả |
         *     | `dismiss` | mọi loại | Không vi phạm — chỉ đóng báo cáo |
         *     | `resolve` | tài khoản | Đã xử lý ngoài luồng (vd Admin đã khóa) — **bắt buộc** `note` |
         *
         *     Sai cặp `decision` × loại đối tượng → 400 `errors.decision`.
         *
         *     Ẩn đối tượng, đóng **mọi** báo cáo đang mở của nó và ghi nhật ký kiểm toán là **một** transaction: lỗi giữa chừng
         *     thì không gì thay đổi. `reasonCode` vắng → lý do của báo cáo được mở; có → dùng đúng giá trị đó cho `hidden_reason`
         *     và thông báo. Báo cáo thứ hai cho bài **đã** ẩn: `hide` vẫn 200, đóng báo cáo, không thông báo lại.
         *
         *     | Tình huống | Phản hồi |
         *     |---|---|
         *     | Báo cáo đã được quyết (người khác vừa quyết, hoặc bấm lần hai) | 409 `report-already-decided` — không đổi gì |
         *     | `hide` mà đối tượng đã bị xóa/không còn | 409 `moderation-target-gone` — báo cáo vẫn mở, `dismiss` nó |
         */
        patch: operations["decideReport"];
        trace?: never;
    };
    "/moderation/targets/{targetType}/{targetId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Khôi phục bài/bình luận bị ẩn
         * @description Tầng 2: `post.hide`. Endpoint đặc quyền. `hidden → published` và một dòng nhật ký `content.restore` trong **một**
         *     transaction. **Không** mở lại báo cáo đã đóng, **không** thông báo ai.
         *
         *     `targetType: user` → 400 `errors.targetType` (tài khoản không "ẩn" được). Đối tượng không tồn tại → 404; đang không bị
         *     ẩn → 409 `moderation-not-hidden`. Body tùy chọn.
         */
        post: operations["restoreTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nhật ký kiểm toán — ai làm gì, trên cái gì, lúc nào, từ đâu; mới nhất trước
         * @description Tầng 2: `audit.read` (chỉ ADMIN). Endpoint đặc quyền: fail-closed khi không kiểm được thu hồi (503), bị từ chối thì
         *     chính lần đó ghi `access.denied`. Nhật ký là **append-only** — không có đường sửa hay xóa.
         *
         *     Sắp theo `id` giảm dần, phân trang keyset. Bộ lọc tùy chọn, cộng dồn: `actorId`, `action`, `targetType` (+ `targetId`).
         *     `targetId` phải đi kèm `targetType`. `action` lọc được một mình.
         *
         *     `metadata` là JSON như lúc ghi — mã, id, ghi chú của người thao tác; **không bao giờ** chứa nội dung bài, bình luận
         *     hay mô tả của người báo (Đ-6.15).
         */
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 7807 Problem Details — dạng lỗi duy nhất của toàn dự án. Sinh bởi
         *     `SocialApp.SharedKernel.Errors.GlobalExceptionHandler`; `traceId` và `type` gắn thống nhất
         *     trong `AddSharedKernel`.
         */
        ProblemDetails: {
            /**
             * Format: uri
             * @description Mặc định `https://httpstatuses.io/{status}`; ca FE phải phân nhánh thì là một URN ổn định.
             */
            type?: string;
            /** @description Nhãn ngắn, ổn định theo loại lỗi. **Không** chứa dữ liệu người dùng. */
            title: string;
            /** Format: int32 */
            status: number;
            /** @description Thông điệp cho người đọc. Vắng mặt ở lỗi 500. */
            detail?: string | null;
            /** @description Path của request gây lỗi. */
            instance?: string;
            /** @description Bằng header `X-Correlation-ID` của chính request đó — dùng để tra log. */
            traceId: string;
            /** @description Chỉ có ở lỗi validation (400). Map `tên trường → danh sách thông điệp`. */
            errors?: {
                [key: string]: string[];
            } | null;
        };
        /** @description 503 fail-closed của endpoint đặc quyền (Đ-6.8). Cùng hình dạng `ProblemDetails`, `type` cố định. */
        RevocationUnavailableProblem: components["schemas"]["ProblemDetails"] & {
            /** @enum {string} */
            type: "urn:socialapp:problem:revocation-unavailable";
        };
        /**
         * @description Loại đối tượng bị báo cáo. `comment` hợp lệ nhưng trả 404 tới khi có module bình luận (L-D13).
         * @enum {string}
         */
        ReportTargetType: "post" | "comment" | "user";
        /**
         * @description Lý do chuẩn hóa (PTTK ENT-12). FE hiển thị nhãn tiếng Việt: `spam` Spam · `harassment` Quấy rối ·
         *     `nudity` Nội dung khỏa thân · `violence` Bạo lực · `other` Khác (bắt buộc mô tả).
         * @enum {string}
         */
        ReasonCode: "spam" | "harassment" | "nudity" | "violence" | "other";
        CreateReportRequest: {
            targetType: components["schemas"]["ReportTargetType"];
            /** Format: uuid */
            targetId: string;
            reasonCode: components["schemas"]["ReasonCode"];
            /**
             * @description Mô tả thêm, tối đa 500 ký tự sau khi cắt khoảng trắng hai đầu. **Bắt buộc** khi `reasonCode: other`. Chỉ
             *     người kiểm duyệt đọc — không bao giờ hiện lại cho người khác.
             */
            detail?: string;
        };
        /** @description Biên nhận báo cáo. Cố ý không nhắc lại đối tượng bị báo (Mục 8.1). */
        ReportReceipt: {
            /** Format: uuid */
            reportId: string;
            /**
             * @description Luôn `open` — báo cáo trả về luôn là báo cáo đang chờ xử lý.
             * @enum {string}
             */
            status: "open";
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Đối tượng bị báo, dạng tham chiếu. */
        ReportTargetRef: {
            type: components["schemas"]["ReportTargetType"];
            /** Format: uuid */
            id: string;
        };
        /** @description Một dòng hàng đợi = một ĐỐI TƯỢNG bị báo (không phải một báo cáo). Không có người báo, không có nội dung. */
        ReportQueueItem: {
            /**
             * Format: uuid
             * @description Báo cáo mở cũ nhất của đối tượng — dùng để mở `GET /reports/{reportId}`.
             */
            reportId: string;
            target: components["schemas"]["ReportTargetRef"];
            /**
             * Format: int32
             * @description Số báo cáo đang mở của đối tượng.
             */
            reportCount: number;
            /** @description Số báo cáo đang mở theo lý do. Chỉ có lý do đếm được ít nhất một; key là `ReasonCode`. */
            reasons: {
                [key: string]: number;
            };
            /**
             * Format: date-time
             * @description Thời điểm báo cáo mở cũ nhất — khóa sắp xếp, cũ nhất trước.
             */
            firstReportedAt: string;
        };
        ReportQueuePage: {
            items: components["schemas"]["ReportQueueItem"][];
            /** @description Opaque. `null` khi hết dữ liệu — không phải chuỗi rỗng. */
            nextCursor: string | null;
        };
        /** @description Thẻ người dùng (tên hiển thị + ảnh đại diện) — hydrate từ hồ sơ. */
        UserCard: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            /**
             * Format: uri
             * @description Presigned GET 15 phút, `null` khi chưa có ảnh đại diện.
             */
            avatarUrl: string | null;
        };
        /** @description Một ảnh của đối tượng. Không có key lưu trữ. */
        TargetMedia: {
            /**
             * Format: uri
             * @description Presigned GET 15 phút.
             */
            url: string;
        };
        /**
         * @description Ảnh chụp đối tượng tại lúc đọc, **không** theo luật hiển thị của người dùng: bài riêng tư, bị ẩn, đã xóa mềm vẫn có
         *     `body`. Mọi trường luôn có mặt; trường không áp dụng là `null`.
         */
        TargetSnapshot: {
            type: components["schemas"]["ReportTargetType"];
            /** Format: uuid */
            id: string;
            /**
             * @description Bài: `published` · `hidden` · `deleted`. Người dùng: `active` · `disabled`. Đối tượng không còn trong bảng nào →
             *     `deleted`.
             * @enum {string}
             */
            status: "published" | "hidden" | "deleted" | "active" | "disabled";
            /** @description Tác giả bài; với người dùng là chính người đó. `null` khi không có hồ sơ hoặc đối tượng đã biến mất. */
            author: components["schemas"]["UserCard"] | null;
            /** @description Nội dung bài / tiểu sử người dùng. */
            body: string | null;
            /** @description Ảnh bài theo thứ tự hiển thị / ảnh đại diện của người dùng. */
            media: components["schemas"]["TargetMedia"][];
            /**
             * Format: uuid
             * @description Bài chứa đối tượng — với bài là chính nó; với người dùng là `null`.
             */
            postId: string | null;
            /**
             * Format: date-time
             * @description `null` chỉ khi đối tượng không còn trong bảng nào.
             */
            createdAt: string | null;
            /** Format: date-time */
            editedAt: string | null;
        };
        /** @description Một báo cáo đang mở. **Không** có người báo. */
        OpenReport: {
            /** Format: uuid */
            reportId: string;
            reasonCode: components["schemas"]["ReasonCode"];
            /** @description Mô tả người báo tự gõ (bắt buộc với `other`). */
            detail: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * @description Một quyết định đã có trên đối tượng. `outcome` là trạng thái các báo cáo sau quyết định (L-D15): `resolved` (đã ẩn
         *     nội dung hoặc đã xử lý) hoặc `dismissed` (không vi phạm). Nội dung có đang bị ẩn không: đọc `target.status`.
         */
        ReportHistoryEntry: {
            /** @enum {string} */
            outcome: "resolved" | "dismissed";
            /**
             * Format: uuid
             * @description Moderator/Admin đã quyết.
             */
            resolverId: string;
            /** Format: date-time */
            resolvedAt: string;
            /** @description Ghi chú của người quyết. */
            note: string | null;
        };
        /** @description Chi tiết một báo cáo. **Không** có người báo ở bất kỳ độ sâu nào. */
        ReportDetail: {
            /** Format: uuid */
            reportId: string;
            target: components["schemas"]["TargetSnapshot"];
            /** @description Mọi báo cáo đang mở của cùng đối tượng, cũ nhất trước. */
            openReports: components["schemas"]["OpenReport"][];
            /** @description Các quyết định đã có trên đối tượng, cũ nhất trước. */
            history: components["schemas"]["ReportHistoryEntry"][];
        };
        /** @description 409 của `PATCH /reports/{reportId}` (Đ-6.13). Cùng hình dạng `ProblemDetails`, `type` là một trong hai URN. */
        ReportDecisionConflictProblem: components["schemas"]["ProblemDetails"] & {
            /** @enum {string} */
            type: "urn:socialapp:problem:report-already-decided" | "urn:socialapp:problem:moderation-target-gone";
        };
        /** @description 409 của khôi phục. Cùng hình dạng `ProblemDetails`, `type` cố định. */
        TargetNotHiddenProblem: components["schemas"]["ProblemDetails"] & {
            /** @enum {string} */
            type: "urn:socialapp:problem:moderation-not-hidden";
        };
        /**
         * @description `hide` (bài, bình luận) · `dismiss` (mọi loại) · `resolve` (tài khoản, bắt buộc `note`).
         * @enum {string}
         */
        ReportDecision: "hide" | "dismiss" | "resolve";
        DecideReportRequest: {
            decision: components["schemas"]["ReportDecision"];
            reasonCode?: components["schemas"]["ReasonCode"];
            /**
             * @description Ghi chú của người quyết, tối đa 500 ký tự sau khi cắt khoảng trắng; chỉ khoảng trắng coi như vắng. **Bắt buộc** khi
             *     `resolve`. Hiện ở lịch sử quyết định cho Moderator khác, không bao giờ cho tác giả hay người báo.
             */
            note?: string;
        };
        ReportDecisionResult: {
            decision: components["schemas"]["ReportDecision"];
            /** @description Mọi báo cáo vừa đóng — báo cáo được mở và mọi báo cáo đang mở khác của cùng đối tượng. */
            closedReportIds: string[];
            /**
             * @description Trạng thái đối tượng sau quyết định — `hide` → `hidden`, còn lại giữ nguyên.
             * @enum {string}
             */
            targetStatus: "published" | "hidden" | "deleted" | "active" | "disabled";
        };
        RestoreTargetRequest: {
            /** @description Ghi chú của người khôi phục (nhật ký kiểm toán). */
            note?: string;
        };
        ModerationTargetChange: {
            targetType: components["schemas"]["ReportTargetType"];
            /** Format: uuid */
            targetId: string;
            /** @enum {string} */
            targetStatus: "published";
        };
        /**
         * @description Mã hành động (Đ-6.15). Kiểm duyệt: `report.hide`, `report.dismiss`, `report.resolve`, `content.restore`. Tài khoản:
         *     `user.lock`, `user.unlock`, `role.assign`. Vai trò: `role.create`, `role.rename`, `role.permissions`, `role.delete`.
         *     Truy cập: `access.denied`.
         * @enum {string}
         */
        AuditAction: "report.hide" | "report.dismiss" | "report.resolve" | "content.restore" | "user.lock" | "user.unlock" | "role.assign" | "role.create" | "role.rename" | "role.permissions" | "role.delete" | "access.denied";
        /** @description Một dòng nhật ký. Mọi trường luôn có mặt; không áp dụng thì `null`. */
        AuditLogItem: {
            /**
             * Format: int64
             * @description Tăng dần theo thời gian ghi — khóa sắp xếp.
             */
            id: number;
            /** Format: uuid */
            actorId: string;
            /** @description `null` khi người thao tác chưa có hồ sơ. */
            actor: components["schemas"]["UserCard"] | null;
            action: components["schemas"]["AuditAction"];
            targetType: string | null;
            /** Format: uuid */
            targetId: string | null;
            /** @description JSON như lúc ghi — mã, id, ghi chú của người thao tác. Không chứa nội dung người dùng. */
            metadata: {
                [key: string]: unknown;
            } | null;
            /** @description IP người thao tác; `null` khi không có request (job nền). */
            ip: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        AuditLogPage: {
            items: components["schemas"]["AuditLogItem"][];
            /** @description Opaque. `null` khi hết dữ liệu. */
            nextCursor: string | null;
        };
    };
    responses: {
        /**
         * @description Dữ liệu đầu vào không hợp lệ. `errors` là map `tên trường → danh sách thông điệp`: `targetType`, `targetId`,
         *     `reasonCode` thiếu hoặc ngoài tập giá trị, `detail` thiếu khi `other` hoặc quá 500 ký tự; `targetId` cũng là key của
         *     lỗi "báo cáo chính mình". Hàng đợi và chi tiết: `status` khác `open`, `cursor` rác, `limit` ngoài `1..50`,
         *     `reportId` sai dạng UUID. Quyết định: `decision` ngoài tập hoặc sai cặp với loại đối tượng, `reasonCode` ngoài tập,
         *     `note` quá 500 ký tự hoặc thiếu khi `resolve`. Khôi phục: `targetType` khác `post`/`comment`, `targetId` sai dạng.
         *     Nhật ký: `actorId`/`targetId` sai dạng, `action` lạ, `targetId` thiếu `targetType`, `limit` ngoài `1..100`, `cursor` rác.
         */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/400",
                 *       "title": "Dữ liệu không hợp lệ",
                 *       "status": 400,
                 *       "detail": "Dữ liệu đầu vào không hợp lệ",
                 *       "instance": "/api/v1/reports",
                 *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8",
                 *       "errors": {
                 *         "detail": [
                 *           "Vui lòng mô tả lý do."
                 *         ]
                 *       }
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Thiếu access token, token sai chữ ký, hết hạn, hoặc đã bị thu hồi. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/401",
                 *       "title": "Chưa xác thực",
                 *       "status": 401,
                 *       "detail": "Yêu cầu access token hợp lệ.",
                 *       "instance": "/api/v1/reports",
                 *       "traceId": "a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Tầng 2 từ chối — vai trò của người gọi không có mã quyền endpoint đòi. `POST /reports` đòi `report.create` (USER,
         *     MODERATOR đều có; 403 chỉ gặp ở vai trò tự tạo không được gán nó). Hàng đợi, chi tiết, quyết định đòi `report.resolve`
         *     (USER không có); `decision: hide` và khôi phục đòi thêm/đòi `post.hide`; nhật ký đòi `audit.read` (chỉ ADMIN). Lần từ chối ở các endpoint kiểm duyệt ghi nhật
         *     ký kiểm toán `access.denied`. Thông điệp không nêu quyền còn thiếu.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/403",
                 *       "title": "Bị từ chối",
                 *       "status": 403,
                 *       "detail": "Bạn không có quyền thực hiện thao tác này.",
                 *       "instance": "/api/v1/reports",
                 *       "traceId": "c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Đối tượng không tồn tại, đã bị ẩn/xóa, loại chưa hỗ trợ, **hoặc người gọi không được xem nó** — MỘT thân lỗi cho mọi
         *     trường hợp (Đ-6.12, dòng `REP-IDOR` của AuthZ matrix). Khác nhau ở đây thì status code tự nó tố cáo bài riêng tư có
         *     tồn tại.
         */
        ReportTargetNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/404",
                 *       "title": "Không tìm thấy tài nguyên",
                 *       "status": 404,
                 *       "detail": "Không tìm thấy nội dung cần báo cáo.",
                 *       "instance": "/api/v1/reports",
                 *       "traceId": "d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Báo cáo không tồn tại. Chỉ người có `report.resolve` tới được đây — người khác dừng ở 403. */
        ReportNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/404",
                 *       "title": "Không tìm thấy tài nguyên",
                 *       "status": 404,
                 *       "detail": "Không tìm thấy báo cáo.",
                 *       "instance": "/api/v1/reports/0192f3ca-6e41-7a02-b3d5-8c7e9f1a2b30",
                 *       "traceId": "d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Không quyết được — không có gì bị đổi. Phân nhánh theo `type`: `report-already-decided` (báo cáo không còn mở — nạp lại
         *     hàng đợi) · `moderation-target-gone` (`hide` mà đối tượng đã bị xóa — báo cáo vẫn mở, hãy `dismiss`).
         */
        ReportDecisionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:socialapp:problem:report-already-decided",
                 *       "title": "Xung đột dữ liệu",
                 *       "status": 409,
                 *       "detail": "Báo cáo này đã được xử lý.",
                 *       "instance": "/api/v1/reports/0192f3ca-6e41-7a02-b3d5-8c7e9f1a2b30",
                 *       "traceId": "1a3c5e7b9d1f3a5c7e9b1d3f5a7c9e1b"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ReportDecisionConflictProblem"];
            };
        };
        /** @description Đối tượng không tồn tại. Chỉ người có `post.hide` tới được đây — người khác dừng ở 403. */
        ModerationTargetNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/404",
                 *       "title": "Không tìm thấy tài nguyên",
                 *       "status": 404,
                 *       "detail": "Không tìm thấy nội dung.",
                 *       "instance": "/api/v1/moderation/targets/post/0192f3c9-2b7d-7e10-8c4a-1f3e5d7b9a20/restore",
                 *       "traceId": "2b4d6f8a0c2e4b6d8f0a2c4e6b8d0f2a"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Đối tượng đang không bị ẩn — không có gì để khôi phục, không đổi gì. */
        TargetNotHidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:socialapp:problem:moderation-not-hidden",
                 *       "title": "Xung đột dữ liệu",
                 *       "status": 409,
                 *       "detail": "Nội dung này hiện không bị ẩn.",
                 *       "instance": "/api/v1/moderation/targets/post/0192f3c9-2b7d-7e10-8c4a-1f3e5d7b9a20/restore",
                 *       "traceId": "3c5e7a9b1d3f5a7c9e1b3d5f7a9c1e3b"
                 *     }
                 */
                "application/problem+json": components["schemas"]["TargetNotHiddenProblem"];
            };
        };
        /**
         * @description Vượt hạn mức — 10 báo cáo/phút/người (`POST /reports`, Đ-6.12) hoặc 100 req/phút/user (chung, ISS-04). Không có
         *     `Retry-After`.
         */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/429",
                 *       "title": "Quá nhiều yêu cầu",
                 *       "status": 429,
                 *       "detail": "Bạn đã gửi quá nhiều yêu cầu. Vui lòng thử lại sau ít phút.",
                 *       "instance": "/api/v1/reports",
                 *       "traceId": "e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Lỗi không mong muốn. **Không bao giờ có `detail`** — `GlobalExceptionHandler` giấu chi tiết nội bộ, chỉ
         *     `traceId` đi ra ngoài để đối chiếu với log.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/500",
                 *       "title": "Đã xảy ra lỗi không mong muốn",
                 *       "status": 500,
                 *       "instance": "/api/v1/reports",
                 *       "traceId": "b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Fail-closed (Đ-6.8) của các endpoint kiểm duyệt đặc quyền (D7, D8 — **không** áp cho `POST /reports`): server không
         *     kiểm được access token có bị thu hồi không. Không phải lỗi của phiên — FE **không** đăng xuất, hiện thông báo tạm
         *     thời và cho thử lại. Phân nhánh theo `type`, không theo `title`.
         */
        RevocationUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:socialapp:problem:revocation-unavailable",
                 *       "title": "Tạm thời không kiểm tra được phiên đăng nhập",
                 *       "status": 503,
                 *       "detail": "Chức năng quản trị tạm thời không khả dụng. Vui lòng thử lại sau ít phút.",
                 *       "instance": "/api/v1/reports",
                 *       "traceId": "f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6e8"
                 *     }
                 */
                "application/problem+json": components["schemas"]["RevocationUnavailableProblem"];
            };
        };
    };
    parameters: {
        /** @description UUID v7 của báo cáo. Sai dạng → 400 `errors.reportId`. */
        ReportId: string;
        /** @description `post` hoặc `comment`. `user` hay giá trị khác → 400 `errors.targetType`. */
        TargetType: string;
        /** @description UUID của đối tượng. Sai dạng → 400 `errors.targetId`. */
        TargetId: string;
        /** @description `nextCursor` của trang trước, opaque. Sai dạng → 400 `errors.cursor`. */
        Cursor: string;
        /** @description Số dòng mỗi trang, `1..50`. Ngoài khoảng → 400 `errors.limit`. */
        Limit: number;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Correlation ID của request, bằng đúng `traceId` trong Problem Details khi có lỗi.
         *     Client gửi header cùng tên thì server dùng lại giá trị đó.
         * @example 9f2c7b1e4a6d4f0b8c3e5a7d9b1f3c5e
         */
        XCorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listReports: {
        parameters: {
            query?: {
                /** @description Chỉ `open` (mặc định). Giá trị khác → 400 `errors.status`. */
                status?: "open";
                /** @description `nextCursor` của trang trước, opaque. Sai dạng → 400 `errors.cursor`. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Số dòng mỗi trang, `1..50`. Ngoài khoảng → 400 `errors.limit`. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Một trang hàng đợi. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "reportId": "0192f3ca-6e41-7a02-b3d5-8c7e9f1a2b30",
                     *           "target": {
                     *             "type": "post",
                     *             "id": "0192f3c9-2b7d-7e10-8c4a-1f3e5d7b9a20"
                     *           },
                     *           "reportCount": 3,
                     *           "reasons": {
                     *             "spam": 2,
                     *             "violence": 1
                     *           },
                     *           "firstReportedAt": "2026-09-24T08:15:42.123456Z"
                     *         }
                     *       ],
                     *       "nextCursor": null
                     *     }
                     */
                    "application/json": components["schemas"]["ReportQueuePage"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    createReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "targetType": "post",
                 *       "targetId": "0192f3c9-2b7d-7e10-8c4a-1f3e5d7b9a20",
                 *       "reasonCode": "spam"
                 *     }
                 */
                "application/json": components["schemas"]["CreateReportRequest"];
            };
        };
        responses: {
            /** @description Người gọi đã có báo cáo đang mở cho đối tượng này — trả lại chính báo cáo đó, không tạo thêm. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "reportId": "0192f3ca-6e41-7a02-b3d5-8c7e9f1a2b30",
                     *       "status": "open",
                     *       "createdAt": "2026-09-24T08:15:42.123456Z"
                     *     }
                     */
                    "application/json": components["schemas"]["ReportReceipt"];
                };
            };
            /** @description Báo cáo mới, đang chờ xử lý. */
            201: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "reportId": "0192f3ca-6e41-7a02-b3d5-8c7e9f1a2b30",
                     *       "status": "open",
                     *       "createdAt": "2026-09-24T08:15:42.123456Z"
                     *     }
                     */
                    "application/json": components["schemas"]["ReportReceipt"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ReportTargetNotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 của báo cáo. Sai dạng → 400 `errors.reportId`. */
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chi tiết báo cáo. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "reportId": "0192f3ca-6e41-7a02-b3d5-8c7e9f1a2b30",
                     *       "target": {
                     *         "type": "post",
                     *         "id": "0192f3c9-2b7d-7e10-8c4a-1f3e5d7b9a20",
                     *         "status": "published",
                     *         "author": {
                     *           "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *           "displayName": "Bình Minh",
                     *           "avatarUrl": null
                     *         },
                     *         "body": "Nội dung bài bị báo cáo.",
                     *         "media": [],
                     *         "postId": "0192f3c9-2b7d-7e10-8c4a-1f3e5d7b9a20",
                     *         "createdAt": "2026-09-24T07:00:00.000000Z",
                     *         "editedAt": null
                     *       },
                     *       "openReports": [
                     *         {
                     *           "reportId": "0192f3ca-6e41-7a02-b3d5-8c7e9f1a2b30",
                     *           "reasonCode": "spam",
                     *           "detail": null,
                     *           "createdAt": "2026-09-24T08:15:42.123456Z"
                     *         }
                     *       ],
                     *       "history": []
                     *     }
                     */
                    "application/json": components["schemas"]["ReportDetail"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ReportNotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    decideReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 của báo cáo. Sai dạng → 400 `errors.reportId`. */
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "decision": "hide",
                 *       "reasonCode": "spam",
                 *       "note": "Quảng cáo lặp lại nhiều lần."
                 *     }
                 */
                "application/json": components["schemas"]["DecideReportRequest"];
            };
        };
        responses: {
            /** @description Đã quyết. `closedReportIds` là mọi báo cáo vừa đóng. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "decision": "hide",
                     *       "closedReportIds": [
                     *         "0192f3ca-6e41-7a02-b3d5-8c7e9f1a2b30",
                     *         "0192f3cb-1a22-7c10-9d4e-5f6a7b8c9d01"
                     *       ],
                     *       "targetStatus": "hidden"
                     *     }
                     */
                    "application/json": components["schemas"]["ReportDecisionResult"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ReportNotFound"];
            409: components["responses"]["ReportDecisionConflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    restoreTarget: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description `post` hoặc `comment`. `user` hay giá trị khác → 400 `errors.targetType`. */
                targetType: components["parameters"]["TargetType"];
                /** @description UUID của đối tượng. Sai dạng → 400 `errors.targetId`. */
                targetId: components["parameters"]["TargetId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                /**
                 * @example {
                 *       "note": "Ẩn nhầm — bài không vi phạm."
                 *     }
                 */
                "application/json": components["schemas"]["RestoreTargetRequest"];
            };
        };
        responses: {
            /** @description Đã khôi phục. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "targetType": "post",
                     *       "targetId": "0192f3c9-2b7d-7e10-8c4a-1f3e5d7b9a20",
                     *       "targetStatus": "published"
                     *     }
                     */
                    "application/json": components["schemas"]["ModerationTargetChange"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ModerationTargetNotFound"];
            409: components["responses"]["TargetNotHidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                /** @description Người thao tác. Sai dạng UUID → 400 `errors.actorId`. */
                actorId?: string;
                /** @description Một mã `AuditAction`. Mã lạ → 400 `errors.action`. */
                action?: components["schemas"]["AuditAction"];
                /** @description Loại đối tượng (`post`, `comment`, `user`, `role`, `report`, `endpoint`…), tối đa 20 ký tự. */
                targetType?: string;
                /** @description Chỉ đi kèm `targetType` — thiếu `targetType` → 400 `errors.targetId`. */
                targetId?: string;
                /** @description `nextCursor` của trang trước, opaque. Sai dạng → 400 `errors.cursor`. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Số dòng mỗi trang, `1..100`. Ngoài khoảng → 400 `errors.limit`. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Một trang nhật ký. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "id": 1042,
                     *           "actorId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *           "actor": {
                     *             "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *             "displayName": "Kiểm duyệt viên",
                     *             "avatarUrl": null
                     *           },
                     *           "action": "report.hide",
                     *           "targetType": "post",
                     *           "targetId": "0192f3c9-2b7d-7e10-8c4a-1f3e5d7b9a20",
                     *           "metadata": {
                     *             "reportIds": [
                     *               "0192f3ca-6e41-7a02-b3d5-8c7e9f1a2b30"
                     *             ],
                     *             "reasonCode": "spam",
                     *             "note": null
                     *           },
                     *           "ip": "203.0.113.7",
                     *           "createdAt": "2026-09-25T08:15:42.123456Z"
                     *         }
                     *       ],
                     *       "nextCursor": "MTA0Mg"
                     *     }
                     */
                    "application/json": components["schemas"]["AuditLogPage"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
}
