/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hàng đợi kiểm duyệt — mỗi đối tượng bị báo một dòng, cũ nhất trước
         * @description Tầng 2: `report.resolve` (MODERATOR, ADMIN có). Endpoint đặc quyền: fail-closed khi không kiểm được thu hồi
         *     (503 `revocation-unavailable`), bị từ chối thì ghi nhật ký kiểm toán `access.denied`.
         *
         *     Báo cáo **đang mở** gom theo đối tượng (Đ-6.13): ba người báo cùng một bài là **một** dòng `reportCount: 3`.
         *     Sắp theo `firstReportedAt` tăng dần (báo cáo mở cũ nhất của đối tượng), hòa thì theo `target.id`. `reportId` là
         *     báo cáo mở cũ nhất của đối tượng — mở chi tiết bằng id này; nó không đổi giữa các lần tải.
         *
         *     Hết dữ liệu khi và chỉ khi `nextCursor` là `null`. Cursor opaque — không tự dựng.
         */
        get: operations["listReports"];
        put?: never;
        /**
         * Báo cáo một bài viết, bình luận hoặc tài khoản
         * @description Tầng 2: `report.create` (người dùng thường có). Người báo là người gọi — không nhận từ body.
         *
         *     | Tình huống | Phản hồi |
         *     |---|---|
         *     | Báo cáo mới | **201** `ReportReceipt` |
         *     | Đã có báo cáo **đang mở** của chính người này cho cùng đối tượng (bấm hai lần, hai tab) | **200** — CHÍNH báo cáo đó, cùng `reportId` |
         *     | Báo cáo cũ đã được xử lý rồi báo lại | **201** — báo cáo mới |
         *     | Đối tượng không tồn tại, đã bị ẩn/xóa, **hoặc người gọi không được xem** | **404** — một thân lỗi cho mọi trường hợp |
         *     | Báo cáo nội dung/tài khoản của chính mình | 400 `errors.targetId` |
         *     | Quá 10 báo cáo trong một phút (báo trùng vẫn tính) | 429 |
         *
         *     "Được xem" theo đúng luật đọc của đối tượng: bài `private` của người khác, bài `friends` của người không phải
         *     bạn → 404 như bài không tồn tại (Đ-6.12). `targetType: comment` hợp lệ nhưng chưa có module bình luận → 404.
         *
         *     `detail`: cắt khoảng trắng hai đầu; chỉ có khoảng trắng coi như **vắng mặt**. Bắt buộc khi `reasonCode: other`.
         *
         *     Phản hồi **không** nhắc lại đối tượng bị báo — không xác nhận thêm điều gì về nó.
         */
        post: operations["createReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chi tiết báo cáo — nội dung thật của đối tượng, báo cáo đang mở, lịch sử quyết định
         * @description Tầng 2: `report.resolve`. Endpoint đặc quyền như `GET /reports`.
         *
         *     - `target` là ảnh chụp **tại lúc đọc**, kể cả bài `private`/`friends`, đã bị ẩn hay đã xóa mềm — Moderator phải thấy
         *       nội dung mới quyết được. Đây là đường **duy nhất** Moderator đọc nội dung không công khai (`GET /posts/{id}` trả
         *       404 cho họ với bài bị ẩn). Đối tượng không còn trong bảng nào → `status: deleted`, `author`, `body`, `createdAt` là
         *       `null`.
         *     - `openReports`: mọi báo cáo **đang mở** của cùng đối tượng, cũ nhất trước — quyết định (D7c) đóng tất cả cùng lúc.
         *     - `history`: mỗi quyết định đã có một dòng, cũ nhất trước.
         *     - **Không có người báo** ở bất kỳ trường nào — quyết theo nội dung, không theo người báo.
         *
         *     Báo cáo đã đóng vẫn mở được (xem lại lịch sử). Báo cáo không tồn tại → 404.
         */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 7807 Problem Details — dạng lỗi duy nhất của toàn dự án. Sinh bởi
         *     `SocialApp.SharedKernel.Errors.GlobalExceptionHandler`; `traceId` và `type` gắn thống nhất
         *     trong `AddSharedKernel`.
         */
        ProblemDetails: {
            /**
             * Format: uri
             * @description Mặc định `https://httpstatuses.io/{status}`; ca FE phải phân nhánh thì là một URN ổn định.
             */
            type?: string;
            /** @description Nhãn ngắn, ổn định theo loại lỗi. **Không** chứa dữ liệu người dùng. */
            title: string;
            /** Format: int32 */
            status: number;
            /** @description Thông điệp cho người đọc. Vắng mặt ở lỗi 500. */
            detail?: string | null;
            /** @description Path của request gây lỗi. */
            instance?: string;
            /** @description Bằng header `X-Correlation-ID` của chính request đó — dùng để tra log. */
            traceId: string;
            /** @description Chỉ có ở lỗi validation (400). Map `tên trường → danh sách thông điệp`. */
            errors?: {
                [key: string]: string[];
            } | null;
        };
        /** @description 503 fail-closed của endpoint đặc quyền (Đ-6.8). Cùng hình dạng `ProblemDetails`, `type` cố định. */
        RevocationUnavailableProblem: components["schemas"]["ProblemDetails"] & {
            /** @enum {string} */
            type: "urn:socialapp:problem:revocation-unavailable";
        };
        /**
         * @description Loại đối tượng bị báo cáo. `comment` hợp lệ nhưng trả 404 tới khi có module bình luận (L-D13).
         * @enum {string}
         */
        ReportTargetType: "post" | "comment" | "user";
        /**
         * @description Lý do chuẩn hóa (PTTK ENT-12). FE hiển thị nhãn tiếng Việt: `spam` Spam · `harassment` Quấy rối ·
         *     `nudity` Nội dung khỏa thân · `violence` Bạo lực · `other` Khác (bắt buộc mô tả).
         * @enum {string}
         */
        ReasonCode: "spam" | "harassment" | "nudity" | "violence" | "other";
        CreateReportRequest: {
            targetType: components["schemas"]["ReportTargetType"];
            /** Format: uuid */
            targetId: string;
            reasonCode: components["schemas"]["ReasonCode"];
            /**
             * @description Mô tả thêm, tối đa 500 ký tự sau khi cắt khoảng trắng hai đầu. **Bắt buộc** khi `reasonCode: other`. Chỉ
             *     người kiểm duyệt đọc — không bao giờ hiện lại cho người khác.
             */
            detail?: string;
        };
        /** @description Biên nhận báo cáo. Cố ý không nhắc lại đối tượng bị báo (Mục 8.1). */
        ReportReceipt: {
            /** Format: uuid */
            reportId: string;
            /**
             * @description Luôn `open` — báo cáo trả về luôn là báo cáo đang chờ xử lý.
             * @enum {string}
             */
            status: "open";
            /** Format: date-time */
            createdAt: string;
        };
        /** @description Đối tượng bị báo, dạng tham chiếu. */
        ReportTargetRef: {
            type: components["schemas"]["ReportTargetType"];
            /** Format: uuid */
            id: string;
        };
        /** @description Một dòng hàng đợi = một ĐỐI TƯỢNG bị báo (không phải một báo cáo). Không có người báo, không có nội dung. */
        ReportQueueItem: {
            /**
             * Format: uuid
             * @description Báo cáo mở cũ nhất của đối tượng — dùng để mở `GET /reports/{reportId}`.
             */
            reportId: string;
            target: components["schemas"]["ReportTargetRef"];
            /**
             * Format: int32
             * @description Số báo cáo đang mở của đối tượng.
             */
            reportCount: number;
            /** @description Số báo cáo đang mở theo lý do. Chỉ có lý do đếm được ít nhất một; key là `ReasonCode`. */
            reasons: {
                [key: string]: number;
            };
            /**
             * Format: date-time
             * @description Thời điểm báo cáo mở cũ nhất — khóa sắp xếp, cũ nhất trước.
             */
            firstReportedAt: string;
        };
        ReportQueuePage: {
            items: components["schemas"]["ReportQueueItem"][];
            /** @description Opaque. `null` khi hết dữ liệu — không phải chuỗi rỗng. */
            nextCursor: string | null;
        };
        /** @description Thẻ người dùng (tên hiển thị + ảnh đại diện) — hydrate từ hồ sơ. */
        UserCard: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            /**
             * Format: uri
             * @description Presigned GET 15 phút, `null` khi chưa có ảnh đại diện.
             */
            avatarUrl: string | null;
        };
        /** @description Một ảnh của đối tượng. Không có key lưu trữ. */
        TargetMedia: {
            /**
             * Format: uri
             * @description Presigned GET 15 phút.
             */
            url: string;
        };
        /**
         * @description Ảnh chụp đối tượng tại lúc đọc, **không** theo luật hiển thị của người dùng: bài riêng tư, bị ẩn, đã xóa mềm vẫn có
         *     `body`. Mọi trường luôn có mặt; trường không áp dụng là `null`.
         */
        TargetSnapshot: {
            type: components["schemas"]["ReportTargetType"];
            /** Format: uuid */
            id: string;
            /**
             * @description Bài: `published` · `hidden` · `deleted`. Người dùng: `active` · `disabled`. Đối tượng không còn trong bảng nào →
             *     `deleted`.
             * @enum {string}
             */
            status: "published" | "hidden" | "deleted" | "active" | "disabled";
            /** @description Tác giả bài; với người dùng là chính người đó. `null` khi không có hồ sơ hoặc đối tượng đã biến mất. */
            author: components["schemas"]["UserCard"] | null;
            /** @description Nội dung bài / tiểu sử người dùng. */
            body: string | null;
            /** @description Ảnh bài theo thứ tự hiển thị / ảnh đại diện của người dùng. */
            media: components["schemas"]["TargetMedia"][];
            /**
             * Format: uuid
             * @description Bài chứa đối tượng — với bài là chính nó; với người dùng là `null`.
             */
            postId: string | null;
            /**
             * Format: date-time
             * @description `null` chỉ khi đối tượng không còn trong bảng nào.
             */
            createdAt: string | null;
            /** Format: date-time */
            editedAt: string | null;
        };
        /** @description Một báo cáo đang mở. **Không** có người báo. */
        OpenReport: {
            /** Format: uuid */
            reportId: string;
            reasonCode: components["schemas"]["ReasonCode"];
            /** @description Mô tả người báo tự gõ (bắt buộc với `other`). */
            detail: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        /**
         * @description Một quyết định đã có trên đối tượng. `outcome` là trạng thái các báo cáo sau quyết định (L-D15): `resolved` (đã ẩn
         *     nội dung hoặc đã xử lý) hoặc `dismissed` (không vi phạm). Nội dung có đang bị ẩn không: đọc `target.status`.
         */
        ReportHistoryEntry: {
            /** @enum {string} */
            outcome: "resolved" | "dismissed";
            /**
             * Format: uuid
             * @description Moderator/Admin đã quyết.
             */
            resolverId: string;
            /** Format: date-time */
            resolvedAt: string;
            /** @description Ghi chú của người quyết. */
            note: string | null;
        };
        /** @description Chi tiết một báo cáo. **Không** có người báo ở bất kỳ độ sâu nào. */
        ReportDetail: {
            /** Format: uuid */
            reportId: string;
            target: components["schemas"]["TargetSnapshot"];
            /** @description Mọi báo cáo đang mở của cùng đối tượng, cũ nhất trước. */
            openReports: components["schemas"]["OpenReport"][];
            /** @description Các quyết định đã có trên đối tượng, cũ nhất trước. */
            history: components["schemas"]["ReportHistoryEntry"][];
        };
    };
    responses: {
        /**
         * @description Dữ liệu đầu vào không hợp lệ. `errors` là map `tên trường → danh sách thông điệp`: `targetType`, `targetId`,
         *     `reasonCode` thiếu hoặc ngoài tập giá trị, `detail` thiếu khi `other` hoặc quá 500 ký tự; `targetId` cũng là key của
         *     lỗi "báo cáo chính mình". Hàng đợi và chi tiết: `status` khác `open`, `cursor` rác, `limit` ngoài `1..50`,
         *     `reportId` sai dạng UUID.
         */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/400",
                 *       "title": "Dữ liệu không hợp lệ",
                 *       "status": 400,
                 *       "detail": "Dữ liệu đầu vào không hợp lệ",
                 *       "instance": "/api/v1/reports",
                 *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8",
                 *       "errors": {
                 *         "detail": [
                 *           "Vui lòng mô tả lý do."
                 *         ]
                 *       }
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Thiếu access token, token sai chữ ký, hết hạn, hoặc đã bị thu hồi. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/401",
                 *       "title": "Chưa xác thực",
                 *       "status": 401,
                 *       "detail": "Yêu cầu access token hợp lệ.",
                 *       "instance": "/api/v1/reports",
                 *       "traceId": "a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Tầng 2 từ chối — vai trò của người gọi không có mã quyền endpoint đòi. `POST /reports` đòi `report.create` (USER,
         *     MODERATOR đều có; 403 chỉ gặp ở vai trò tự tạo không được gán nó). Hàng đợi và chi tiết đòi `report.resolve` (USER
         *     không có) — lần từ chối đó ghi nhật ký kiểm toán `access.denied`. Thông điệp không nêu quyền còn thiếu.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/403",
                 *       "title": "Bị từ chối",
                 *       "status": 403,
                 *       "detail": "Bạn không có quyền thực hiện thao tác này.",
                 *       "instance": "/api/v1/reports",
                 *       "traceId": "c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Đối tượng không tồn tại, đã bị ẩn/xóa, loại chưa hỗ trợ, **hoặc người gọi không được xem nó** — MỘT thân lỗi cho mọi
         *     trường hợp (Đ-6.12, dòng `REP-IDOR` của AuthZ matrix). Khác nhau ở đây thì status code tự nó tố cáo bài riêng tư có
         *     tồn tại.
         */
        ReportTargetNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/404",
                 *       "title": "Không tìm thấy tài nguyên",
                 *       "status": 404,
                 *       "detail": "Không tìm thấy nội dung cần báo cáo.",
                 *       "instance": "/api/v1/reports",
                 *       "traceId": "d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Báo cáo không tồn tại. Chỉ người có `report.resolve` tới được đây — người khác dừng ở 403. */
        ReportNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/404",
                 *       "title": "Không tìm thấy tài nguyên",
                 *       "status": 404,
                 *       "detail": "Không tìm thấy báo cáo.",
                 *       "instance": "/api/v1/reports/0192f3ca-6e41-7a02-b3d5-8c7e9f1a2b30",
                 *       "traceId": "d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Vượt hạn mức — 10 báo cáo/phút/người (`POST /reports`, Đ-6.12) hoặc 100 req/phút/user (chung, ISS-04). Không có
         *     `Retry-After`.
         */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/429",
                 *       "title": "Quá nhiều yêu cầu",
                 *       "status": 429,
                 *       "detail": "Bạn đã gửi quá nhiều yêu cầu. Vui lòng thử lại sau ít phút.",
                 *       "instance": "/api/v1/reports",
                 *       "traceId": "e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Lỗi không mong muốn. **Không bao giờ có `detail`** — `GlobalExceptionHandler` giấu chi tiết nội bộ, chỉ
         *     `traceId` đi ra ngoài để đối chiếu với log.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/500",
                 *       "title": "Đã xảy ra lỗi không mong muốn",
                 *       "status": 500,
                 *       "instance": "/api/v1/reports",
                 *       "traceId": "b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Fail-closed (Đ-6.8) của các endpoint kiểm duyệt đặc quyền (D7, D8 — **không** áp cho `POST /reports`): server không
         *     kiểm được access token có bị thu hồi không. Không phải lỗi của phiên — FE **không** đăng xuất, hiện thông báo tạm
         *     thời và cho thử lại. Phân nhánh theo `type`, không theo `title`.
         */
        RevocationUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:socialapp:problem:revocation-unavailable",
                 *       "title": "Tạm thời không kiểm tra được phiên đăng nhập",
                 *       "status": 503,
                 *       "detail": "Chức năng quản trị tạm thời không khả dụng. Vui lòng thử lại sau ít phút.",
                 *       "instance": "/api/v1/reports",
                 *       "traceId": "f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6e8"
                 *     }
                 */
                "application/problem+json": components["schemas"]["RevocationUnavailableProblem"];
            };
        };
    };
    parameters: {
        /** @description UUID v7 của báo cáo. Sai dạng → 400 `errors.reportId`. */
        ReportId: string;
        /** @description `nextCursor` của trang trước, opaque. Sai dạng → 400 `errors.cursor`. */
        Cursor: string;
        /** @description Số dòng mỗi trang, `1..50`. Ngoài khoảng → 400 `errors.limit`. */
        Limit: number;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Correlation ID của request, bằng đúng `traceId` trong Problem Details khi có lỗi.
         *     Client gửi header cùng tên thì server dùng lại giá trị đó.
         * @example 9f2c7b1e4a6d4f0b8c3e5a7d9b1f3c5e
         */
        XCorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listReports: {
        parameters: {
            query?: {
                /** @description Chỉ `open` (mặc định). Giá trị khác → 400 `errors.status`. */
                status?: "open";
                /** @description `nextCursor` của trang trước, opaque. Sai dạng → 400 `errors.cursor`. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Số dòng mỗi trang, `1..50`. Ngoài khoảng → 400 `errors.limit`. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Một trang hàng đợi. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "reportId": "0192f3ca-6e41-7a02-b3d5-8c7e9f1a2b30",
                     *           "target": {
                     *             "type": "post",
                     *             "id": "0192f3c9-2b7d-7e10-8c4a-1f3e5d7b9a20"
                     *           },
                     *           "reportCount": 3,
                     *           "reasons": {
                     *             "spam": 2,
                     *             "violence": 1
                     *           },
                     *           "firstReportedAt": "2026-09-24T08:15:42.123456Z"
                     *         }
                     *       ],
                     *       "nextCursor": null
                     *     }
                     */
                    "application/json": components["schemas"]["ReportQueuePage"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
    createReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "targetType": "post",
                 *       "targetId": "0192f3c9-2b7d-7e10-8c4a-1f3e5d7b9a20",
                 *       "reasonCode": "spam"
                 *     }
                 */
                "application/json": components["schemas"]["CreateReportRequest"];
            };
        };
        responses: {
            /** @description Người gọi đã có báo cáo đang mở cho đối tượng này — trả lại chính báo cáo đó, không tạo thêm. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "reportId": "0192f3ca-6e41-7a02-b3d5-8c7e9f1a2b30",
                     *       "status": "open",
                     *       "createdAt": "2026-09-24T08:15:42.123456Z"
                     *     }
                     */
                    "application/json": components["schemas"]["ReportReceipt"];
                };
            };
            /** @description Báo cáo mới, đang chờ xử lý. */
            201: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "reportId": "0192f3ca-6e41-7a02-b3d5-8c7e9f1a2b30",
                     *       "status": "open",
                     *       "createdAt": "2026-09-24T08:15:42.123456Z"
                     *     }
                     */
                    "application/json": components["schemas"]["ReportReceipt"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ReportTargetNotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 của báo cáo. Sai dạng → 400 `errors.reportId`. */
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Chi tiết báo cáo. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "reportId": "0192f3ca-6e41-7a02-b3d5-8c7e9f1a2b30",
                     *       "target": {
                     *         "type": "post",
                     *         "id": "0192f3c9-2b7d-7e10-8c4a-1f3e5d7b9a20",
                     *         "status": "published",
                     *         "author": {
                     *           "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *           "displayName": "Bình Minh",
                     *           "avatarUrl": null
                     *         },
                     *         "body": "Nội dung bài bị báo cáo.",
                     *         "media": [],
                     *         "postId": "0192f3c9-2b7d-7e10-8c4a-1f3e5d7b9a20",
                     *         "createdAt": "2026-09-24T07:00:00.000000Z",
                     *         "editedAt": null
                     *       },
                     *       "openReports": [
                     *         {
                     *           "reportId": "0192f3ca-6e41-7a02-b3d5-8c7e9f1a2b30",
                     *           "reasonCode": "spam",
                     *           "detail": null,
                     *           "createdAt": "2026-09-24T08:15:42.123456Z"
                     *         }
                     *       ],
                     *       "history": []
                     *     }
                     */
                    "application/json": components["schemas"]["ReportDetail"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["ReportNotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["RevocationUnavailable"];
        };
    };
}
