// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SocialApp.Modules.Messaging.Infrastructure;

#nullable disable

namespace SocialApp.Modules.Messaging.Infrastructure.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    [Migration("20260924005704_InitialMessaging")]
    partial class InitialMessaging
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("messaging")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SocialApp.Modules.Messaging.Domain.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<Guid?>("LastMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_message_id");

                    b.Property<long>("SeqCounter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("seq_counter");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserADeliveredSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("user_a_delivered_seq");

                    b.Property<Guid>("UserAId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_a_id");

                    b.Property<long>("UserASeenSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("user_a_seen_seq");

                    b.Property<long>("UserBDeliveredSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("user_b_delivered_seq");

                    b.Property<Guid>("UserBId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_b_id");

                    b.Property<long>("UserBSeenSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("user_b_seen_seq");

                    b.HasKey("Id");

                    b.HasIndex("UserAId", "UserBId")
                        .IsUnique()
                        .HasDatabaseName("uq_conversations_pair");

                    b.HasIndex("UserAId", "LastMessageAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("idx_conversations_a_recent")
                        .HasFilter("last_message_at IS NOT NULL");

                    b.HasIndex("UserBId", "LastMessageAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("idx_conversations_b_recent")
                        .HasFilter("last_message_at IS NOT NULL");

                    b.ToTable("conversations", "messaging", t =>
                        {
                            t.HasCheckConstraint("ck_conversations_marks", "user_a_seen_seq <= user_a_delivered_seq AND user_a_delivered_seq <= seq_counter AND user_b_seen_seq <= user_b_delivered_seq AND user_b_delivered_seq <= seq_counter");

                            t.HasCheckConstraint("ck_conversations_order", "user_a_id < user_b_id");
                        });
                });

            modelBuilder.Entity("SocialApp.Modules.Messaging.Domain.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientMsgId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_msg_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "ClientMsgId")
                        .IsUnique()
                        .HasDatabaseName("uq_messages_conv_client_id");

                    b.HasIndex("ConversationId", "Seq")
                        .IsUnique()
                        .HasDatabaseName("uq_messages_conv_seq");

                    b.ToTable("messages", "messaging", t =>
                        {
                            t.HasCheckConstraint("ck_messages_content", "char_length(content) BETWEEN 1 AND 2000 AND btrim(content) <> ''");

                            t.HasCheckConstraint("ck_messages_seq_positive", "seq > 0");
                        });
                });

            modelBuilder.Entity("SocialApp.Modules.Messaging.Domain.Message", b =>
                {
                    b.HasOne("SocialApp.Modules.Messaging.Domain.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversation");
                });
#pragma warning restore 612, 618
        }
    }
}
