/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/media/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Xin URL tải ảnh lên R2 cho tối đa 10 file (presign theo lô, Đ-2.15)
         * @description Tầng 2 (Đ-2.6): `[Authorize]` cho mọi `purpose`; riêng `purpose=post` controller kiểm thêm quyền `post.create`
         *     bằng `IAuthorizationService` với policy `perm:post.create` — thiếu → **403**. Người chưa có quyền đăng bài vẫn
         *     đổi được avatar. Cùng handler và cùng lối tắt ADMIN với `[RequirePermission]` (chốt Q-D5, 2026-09-19: gọi thẳng
         *     `IPermissionCache` chặn nhầm ADMIN, vì ADMIN không có dòng `role_permissions` nào).
         *
         *     Với mỗi file, server kiểm allowlist (`image/jpeg`, `image/png`, `image/webp`) và `sizeBytes ≤ 10485760`
         *     (10 MB), sinh key `posts/{userId}/{uuid7}.{ext}` hay `avatars/{userId}/{uuid7}.{ext}` theo `purpose`, rồi ký
         *     URL `PUT` hạn **600 giây** với `Content-Type` **và** `Content-Length` **nằm trong signed headers** (Đ-2.8 lớp 1).
         *     `PUT` lệch một byte hay lệch kiểu thì R2 trả 403 — vì vậy `requiredHeaders` trả kèm để FE gửi đúng từng cái.
         *
         *     Endpoint này **không** tạo dòng nào trong DB. Object tải lên mà không được gắn vào bài trong 24 giờ sẽ bị worker
         *     dọn (Đ-2.13). **Không bao giờ log `uploadUrl`.**
         */
        post: operations["createUploads"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Đăng bài (FR-004, BR-01)
         * @description Đường dài nhất của giai đoạn (SEQ-01 bước 6–7). Thứ tự kiểm là **một phần của hợp đồng** vì nó quyết định mã lỗi:
         *
         *     1. Tầng 2: quyền `post.create`.
         *     2. Tầng 3 (Đ-2.4): người gọi **đã có hồ sơ** — chưa → **403**.
         *     3. Tầng 3 (Đ-2.7): **mọi** `mediaKey` thuộc `posts/{actorId}/` — khác → **403** (`TC-A03-media`).
         *     4. BR-01: `body` ≤ 5000 ký tự; ≤ 10 ảnh; `body` rỗng thì phải có ít nhất 1 ảnh — sai → **400** với
         *        `errors.body` hoặc `errors.mediaKeys`.
         *     5. Đ-2.8 lớp 2: `HEAD` từng object trên R2 — object chưa có, lệch `sizeBytes`, lệch `contentType` so với khai
         *        báo → **400** `errors.mediaKeys`, **không tạo bài**. HEAD đứng **trước** transaction.
         *     6. Một transaction: INSERT `posts` (`media_count` đúng ngay từ đầu) + INSERT `media_attachments`. Đụng
         *        `storage_key` UNIQUE (cùng object đã gắn vào bài khác, hoặc commit lại cùng lô) → **409**, không để rơi thành 500.
         *
         *     Trả `PostResponse` đầy đủ với URL ảnh đã ký, để FE chèn thẳng vào danh sách mà không gọi lại.
         */
        post: operations["createPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Đọc một bài (BR-02 tại thời điểm đọc)
         * @description Tầng 2: `post.read.public`. Tầng 3 là BR-02 lúc đọc (Mục 7.4): `public` → ai cũng xem; `private` → chỉ tác
         *     giả; `friends` → `IFriendshipReader` (GĐ2 luôn `false` — chỉ tác giả xem được, Đ-2.9).
         *
         *     Không đạt BR-02, bài đã xóa mềm, hay không tồn tại → **404**, **cùng một phản hồi** (quy ước 3b): trả 403 cho
         *     một bên và 404 cho bên kia là status code tự tố cáo bài có tồn tại. Đây là dòng `READ-01` của AuthZ matrix.
         *
         *     Bài bị kiểm duyệt ẩn (GĐ6, Đ-6.14): tác giả → **200** kèm `moderation`; mọi người khác, kể cả bạn bè, Moderator và
         *     Admin → **404**, cùng phản hồi trên. Moderator xem nội dung qua `GET /reports/{reportId}` (`moderation-v1`).
         */
        get: operations["getPost"];
        put?: never;
        post?: never;
        /**
         * Xóa mềm bài của mình (FR-005, Đ-2.10)
         * @description Đặt `status = 'deleted'` + `deleted_at`; không `DELETE` dòng, không xóa object R2 trong request — worker dọn
         *     sau 7 ngày (Đ-2.13). Sau đó `GET /posts/{id}` của **chính tác giả** cũng 404 (Mục 7.3). Bài bị kiểm duyệt ẩn
         *     cũng xóa được (GĐ6, Đ-6.14) — người dùng luôn xóa được nội dung của mình.
         *
         *     Gọi lại lần hai trên bài đã xóa → **403** (cùng phản hồi với "không phải của bạn"), không phải 404 — thao tác
         *     ghi cần ownership dùng 403 (Mục 6.1). Đây là dòng `TC-A03-delete`.
         *
         *     `postId` sai dạng → **400** `errors.postId` (chốt Q-D7, 2026-09-19): route cố ý không ràng buộc `:guid` nên id
         *     hỏng đi qua model binding chứ không rơi khỏi route. Ràng buộc `:guid` sẽ cho **404**, lệch hẳn `GET`/`PATCH`
         *     cùng đường dẫn vốn đã hứa 400.
         */
        delete: operations["deletePost"];
        options?: never;
        head?: never;
        /**
         * Sửa nội dung hoặc mức riêng tư của bài mình (FR-005)
         * @description Chỉ `body` và `privacy`. **Không sửa được ảnh ở GĐ2** (Mục 7.3) — gửi `mediaKeys` vào đây là field lạ → **400**
         *     (`UnmappedMemberHandling = Disallow`). Mỗi lần sửa đóng dấu `editedAt`.
         *
         *     Tầng 3 theo khuôn Mục 6.2: bài không tồn tại, không phải của bạn, hay đã xóa mềm → **403**, cùng một phản hồi
         *     (`TC-A03`). Không có nhánh Admin ở tầng 3.
         *
         *     Hai trường đều tùy chọn nhưng body rỗng `{}` là 400 (không có gì để sửa). BR-01 áp lại với `body` mới: bài
         *     không có ảnh mà `body` thành rỗng → **400** `errors.body`.
         *
         *     Bài của bạn đang bị kiểm duyệt ẩn (GĐ6, Đ-6.14) → **409** `type urn:socialapp:problem:post-hidden`, không đổi gì.
         *     Kiểm sau tầng 3 (người khác vẫn nhận 403) và trước BR-01.
         */
        patch: operations["updatePost"];
        trace?: never;
    };
    "/users/{userId}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bài của một người dùng, mới nhất trước, phân trang keyset (Đ-2.11)
         * @description Tầng 2: `post.read.public`. BR-02 lọc **ngay trong câu truy vấn** — không lọc sau khi lấy 20 dòng, vì lọc sau
         *     thì trang trả về ít hơn `limit` một cách ngẫu nhiên và FE tưởng đã hết dữ liệu (D6). Bài người gọi không được
         *     xem đơn giản là **không có trong danh sách** — không 403.
         *
         *     Người dùng không tồn tại hoặc chưa có bài → `items: []`, `nextCursor: null` — không 404.
         *
         *     Cursor là **opaque** (`base64url("{created_at:O}|{post_id}")`): FE chỉ chuyển tiếp `nextCursor` nhận được, không
         *     tự dựng. Hết dữ liệu → `nextCursor = null` (không phải `""`). Cursor rác → **400** `errors.cursor`, không âm
         *     thầm trả trang đầu (PAGE-02). Bài mới chèn vào giữa hai lần gọi không gây nhân đôi hay nhảy cóc (PAGE-03).
         */
        get: operations["listUserPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bảng tin của người gọi, mới nhất trước, phân trang keyset (GĐ4, SEQ-03)
         * @description Tầng 2: `post.read.public`. Người gọi lấy từ token — không tham số nào mang id người dùng.
         *
         *     **Nguồn** (Đ-4.5): bạn bè thấy `public` + `friends`, người đang theo dõi (không phải bạn) thấy `public`, bài của
         *     chính mình thấy mọi mức. Chỉ bài đã đăng. Có dù chỉ một kết nối → `mode: network`, kể cả khi `items` rỗng — không
         *     trộn bài người lạ. Chưa có kết nối nào → `mode: suggested`: bài `public` mới nhất của người khác, **cộng** bài của
         *     chính mình mọi mức (Đ-4.6, sửa 2026-09-23 — người mới đăng bài xong phải thấy bài mình).
         *
         *     **Trang ngắn là hợp lệ** (Đ-4.9): mọi response kiểm lại quyền xem với quan hệ hiện tại, nên `items` có thể ít hơn
         *     `limit`. Hết dữ liệu **khi và chỉ khi** `nextCursor` là `null`.
         *
         *     Cursor opaque, cùng bộ mã hóa với `/users/{userId}/posts`. Cursor rác → **400** `errors.cursor` (PAGE-04).
         *
         *     **503** khi hệ thống quá tải (truy vấn feed vượt thời hạn, Đ-4.10), kèm header `Retry-After` (giây). Thử lại sau;
         *     FE không hiện đồng hồ đếm ngược.
         */
        get: operations["getFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 7807 Problem Details — dạng lỗi duy nhất của toàn dự án. Sinh bởi
         *     `SocialApp.SharedKernel.Errors.GlobalExceptionHandler`; `traceId` và `type` gắn thống nhất
         *     trong `AddSharedKernel`.
         */
        ProblemDetails: {
            /**
             * Format: uri
             * @description Mặc định `https://httpstatuses.io/{status}`. Lỗi có `type` riêng khai bằng schema riêng (`FeedOverloadedProblem`, `PostHiddenProblem`).
             */
            type?: string;
            /** @description Nhãn ngắn, ổn định theo loại lỗi. **Không** chứa dữ liệu người dùng. */
            title: string;
            /** Format: int32 */
            status: number;
            /** @description Thông điệp cho người đọc. Vắng mặt ở lỗi 500. */
            detail?: string | null;
            /** @description Path của request gây lỗi. */
            instance?: string;
            /** @description Bằng header `X-Correlation-ID` của chính request đó — dùng để tra log. */
            traceId: string;
            /** @description Chỉ có ở lỗi validation (400). Map `tên trường → danh sách thông điệp`. */
            errors?: {
                [key: string]: string[];
            } | null;
        };
        /**
         * @description Allowlist Đ-2.8 — đúng bằng CHECK `ck_media_content_type` ở DB và `StorageKeys.AllowedContentTypes`.
         * @enum {string}
         */
        ImageContentType: "image/jpeg" | "image/png" | "image/webp";
        /**
         * @description Chữ thường, khớp CHECK `ck_posts_privacy`. `friends` ở GĐ2 chỉ tác giả xem được (Đ-2.9, `AlwaysStrangers`);
         *     GĐ4 bật kết bạn thật bằng một dòng DI — hợp đồng không đổi.
         * @enum {string}
         */
        PostPrivacy: "public" | "friends" | "private";
        /**
         * @description Quyết định tiền tố key (`posts/` hay `avatars/`) và mức quyền (`post` cần `post.create`, Đ-2.6).
         * @enum {string}
         */
        UploadPurpose: "post" | "avatar";
        /** @description Thứ client khai cho một file — server ký đúng hai giá trị này vào URL. */
        UploadFileDeclaration: {
            contentType: components["schemas"]["ImageContentType"];
            /**
             * Format: int64
             * @description Dung lượng thật của file (byte), tối đa 10 MB (BR-01, Đ-2.8).
             */
            sizeBytes: number;
        };
        CreateUploadsRequest: {
            purpose: components["schemas"]["UploadPurpose"];
            files: components["schemas"]["UploadFileDeclaration"][];
        };
        /** @description Một URL ký cho một file. `mediaKey` là thứ gửi lại ở `POST /posts` hoặc `PUT /users/me/avatar`. */
        UploadTicket: {
            /** @description `posts/{userId}/{uuid7}.{ext}` hoặc `avatars/{userId}/{uuid7}.{ext}` (Đ-2.7). */
            mediaKey: string;
            /**
             * Format: uri
             * @description Presigned `PUT`, hạn `expiresIn` giây. Mang chữ ký — **không log**, không lưu.
             */
            uploadUrl: string;
            /**
             * Format: int32
             * @description Số giây còn hạn của `uploadUrl` (600).
             */
            expiresIn: number;
            /**
             * @description Header **phải** gửi kèm `PUT` vì chúng nằm trong chữ ký. `Content-Length` trình duyệt tự gửi từ body —
             *     **không** tự đặt bằng tay; giá trị ở đây để FE đối chiếu kích thước file trước khi gửi.
             */
            requiredHeaders: {
                "Content-Type": string;
                "Content-Length": string;
            };
        };
        /** @description Một ảnh đã `PUT` xong, kèm lại khai báo lúc presign để server đối chiếu với `HEAD` (Đ-2.8 lớp 2). Xem Q-D1 ở đầu file. */
        MediaKeyDeclaration: {
            mediaKey: string;
            contentType: components["schemas"]["ImageContentType"];
            /** Format: int64 */
            sizeBytes: number;
        };
        CreatePostRequest: {
            /** @description Rỗng/`null` được nếu có ít nhất một ảnh (BR-01, `ck_posts_not_empty`). */
            body?: string | null;
            privacy: components["schemas"]["PostPrivacy"];
            /** @description Thứ tự trong mảng là `position` hiển thị (0..9). Bỏ trống hoặc `[]` nếu bài chỉ có chữ. */
            mediaKeys?: components["schemas"]["MediaKeyDeclaration"][];
        };
        /** @description Chỉ hai trường; `mediaKeys` không có ở đây — gửi vào là 400 (GĐ2 không sửa ảnh, Mục 7.3). */
        UpdatePostRequest: {
            body?: string | null;
            privacy?: components["schemas"]["PostPrivacy"];
        };
        /** @description Từ `IUserDirectory` (SharedKernel, A6) — một lời gọi batch cho cả trang (Đ-2.3). */
        PostAuthor: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            /**
             * Format: uri
             * @description Presigned GET 15 phút, `null` khi chưa có avatar.
             */
            avatarUrl?: string | null;
        };
        PostMedia: {
            /**
             * Format: uri
             * @description Presigned GET **15 phút** (Đ-2.9), cấp sau khi qua BR-02. **Không có `mediaKey`** — key là chi tiết nội bộ.
             */
            url: string;
            contentType: components["schemas"]["ImageContentType"];
            /** Format: int32 */
            width?: number | null;
            /** Format: int32 */
            height?: number | null;
            /** Format: int32 */
            position: number;
        };
        PostResponse: {
            /**
             * Format: uuid
             * @description UUID v7 — thứ tự PK là thứ tự thời gian, nền của cursor keyset (Đ-2.11).
             */
            postId: string;
            author: components["schemas"]["PostAuthor"];
            body?: string | null;
            privacy: components["schemas"]["PostPrivacy"];
            media: components["schemas"]["PostMedia"][];
            /**
             * Format: int32
             * @description GĐ2 luôn 0 (khung Đ-2.12).
             */
            commentCount: number;
            /** @description GĐ2 luôn `{}` rỗng — **không** `null` (Đ-2.12). Key là loại cảm xúc, value là số lượt. */
            reactionCounts: {
                [key: string]: number;
            };
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description `null` nếu chưa sửa lần nào.
             */
            editedAt?: string | null;
            /** @description Do **server** tính (`author_id == actorId`). FE không tự so id (Mục 8.2). */
            canEdit: boolean;
            /**
             * @description GĐ6 (Đ-6.14). Khác `null` **chỉ** khi bài bị kiểm duyệt ẩn và người gọi là tác giả — FE hiện biểu ngữ "bài bị
             *     ẩn" theo `reasonCode`. `null` với mọi bài khác. Không required: client cũ bỏ qua được.
             */
            moderation?: components["schemas"]["PostModeration"] | null;
        };
        /** @description Trạng thái kiểm duyệt cho tác giả. Không có id Moderator hay ghi chú quyết định — tác giả biết vì sao, không biết ai. */
        PostModeration: {
            /** @enum {string} */
            status: "hidden";
            /**
             * @description Cùng tập với `ReasonCode` của `moderation-v1` (PTTK ENT-12). FE hiển thị nhãn tiếng Việt.
             * @enum {string}
             */
            reasonCode: "spam" | "harassment" | "nudity" | "violence" | "other";
            /**
             * Format: date-time
             * @description Lúc bị ẩn. **Không** phải `editedAt` (lần sửa cuối của tác giả).
             */
            hiddenAt: string;
        };
        PostPage: {
            items: components["schemas"]["PostResponse"][];
            /** @description Opaque. `null` khi hết dữ liệu — không phải chuỗi rỗng (Đ-2.11). */
            nextCursor: string | null;
        };
        /**
         * @description 503 của `GET /feed` (Đ-4.10, Q-E4). Cùng hình dạng `ProblemDetails`, nhưng `type` là định danh ổn định của ca "bảng tin
         *     quá tải" — FE so `type` để tách nó khỏi 503 của hạ tầng (BFF mất kho phiên), không so `title`.
         */
        FeedOverloadedProblem: components["schemas"]["ProblemDetails"] & {
            /** @enum {string} */
            type: "urn:socialapp:problem:feed-overloaded";
        };
        /** @description 409 của `PATCH /posts/{postId}` khi bài đang bị kiểm duyệt ẩn (GĐ6, Đ-6.14). Cùng hình dạng `ProblemDetails`, `type` cố định. */
        PostHiddenProblem: components["schemas"]["ProblemDetails"] & {
            /** @enum {string} */
            type: "urn:socialapp:problem:post-hidden";
        };
        /**
         * @description `network` — có ít nhất một kết nối (bạn hoặc đang theo dõi), kể cả khi feed rỗng. `suggested` — chưa có kết nối
         *     nào, `items` là bài công khai mới nhất của người khác cộng bài của chính mình (Đ-4.6); FE hiện nhãn "Gợi ý cho bạn".
         * @enum {string}
         */
        FeedMode: "network" | "suggested";
        FeedPage: {
            items: components["schemas"]["PostResponse"][];
            /** @description `items` có thể ít hơn `limit`. Hết dữ liệu khi và chỉ khi `nextCursor` là `null`. */
            nextCursor: string | null;
            mode: components["schemas"]["FeedMode"];
        };
    };
    responses: {
        /**
         * @description Dữ liệu đầu vào không hợp lệ. `errors` là map `tên trường → danh sách thông điệp`.
         *
         *     Cũng là mã trả về khi body chứa **field lạ** (`UnmappedMemberHandling = Disallow`, AGENTS.md Mục 9), khi tham số
         *     path sai dạng UUID, khi `cursor` rác hoặc `limit` ngoài `1..50`.
         */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/400",
                 *       "title": "Dữ liệu không hợp lệ",
                 *       "status": 400,
                 *       "detail": "Dữ liệu đầu vào không hợp lệ",
                 *       "instance": "/api/v1/users/0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10/posts",
                 *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8",
                 *       "errors": {
                 *         "cursor": [
                 *           "Cursor không hợp lệ."
                 *         ]
                 *       }
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Thiếu access token, token sai chữ ký, hết hạn, hoặc đã bị thu hồi. Dòng `TC-A01-posts` của AuthZ matrix. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/401",
                 *       "title": "Chưa xác thực",
                 *       "status": 401,
                 *       "detail": "Yêu cầu access token hợp lệ.",
                 *       "instance": "/api/v1/posts",
                 *       "traceId": "a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Tầng 2 hoặc tầng 3 từ chối. Ở thao tác ghi cần ownership: bài không tồn tại, không phải của bạn, hay đã xóa mềm
         *     đều trả **cùng** phản hồi này (Mục 6.2) — thông điệp không nêu id, key hay lý do.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/403",
                 *       "title": "Bị từ chối",
                 *       "status": 403,
                 *       "detail": "Bạn không có quyền thực hiện thao tác này.",
                 *       "instance": "/api/v1/posts/0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                 *       "traceId": "c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Bài không tồn tại, đã xóa mềm, **hoặc người gọi không được xem** (BR-02) — cùng một phản hồi (quy ước 3b). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/404",
                 *       "title": "Không tìm thấy tài nguyên",
                 *       "status": 404,
                 *       "detail": "Không tìm thấy bài viết.",
                 *       "instance": "/api/v1/posts/0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                 *       "traceId": "d2f4a6c8e0b2d4f6a8c0e2b4d6f8a0c2"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Vượt hạn mức 100 req/phút/user (ISS-04). Không có `Retry-After`. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/429",
                 *       "title": "Quá nhiều yêu cầu",
                 *       "status": 429,
                 *       "detail": "Bạn đã gửi quá nhiều yêu cầu. Vui lòng thử lại sau ít phút.",
                 *       "instance": "/api/v1/posts",
                 *       "traceId": "e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Hệ thống đang quá tải — truy vấn feed vượt thời hạn (Đ-4.10). Không phải lỗi hệ thống (500): thử lại sau số giây
         *     trong `Retry-After`. `type` luôn là `urn:socialapp:problem:feed-overloaded` (Q-E4) — định danh để FE nhận ra ca này.
         */
        ServiceUnavailable: {
            headers: {
                /**
                 * @description Số giây nên chờ trước khi thử lại.
                 * @example 5
                 */
                "Retry-After"?: number;
                "X-Correlation-ID": components["headers"]["XCorrelationId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:socialapp:problem:feed-overloaded",
                 *       "title": "Bảng tin đang quá tải",
                 *       "status": 503,
                 *       "detail": "Bảng tin đang có quá nhiều người truy cập. Vui lòng thử lại.",
                 *       "instance": "/api/v1/feed",
                 *       "traceId": "f8a0c2e4b6d8f0a2c4e6b8d0f2a4c6e8"
                 *     }
                 */
                "application/problem+json": components["schemas"]["FeedOverloadedProblem"];
            };
        };
        /**
         * @description Bài đang bị kiểm duyệt ẩn nên không sửa được (GĐ6, Đ-6.14) — không có gì bị đổi. Chỉ tác giả nhận mã này; FE phân
         *     nhánh theo `type`, không theo `title`.
         */
        PostHidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "urn:socialapp:problem:post-hidden",
                 *       "title": "Xung đột dữ liệu",
                 *       "status": 409,
                 *       "detail": "Bài viết đã bị ẩn do vi phạm tiêu chuẩn cộng đồng nên không sửa được.",
                 *       "instance": "/api/v1/posts/0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                 *       "traceId": "0c2e4b6d8f0a2c4e6b8d0f2a4c6e8b0d"
                 *     }
                 */
                "application/problem+json": components["schemas"]["PostHiddenProblem"];
            };
        };
        /**
         * @description Lỗi không mong muốn. **Không bao giờ có `detail`** — `GlobalExceptionHandler` giấu chi tiết nội bộ, chỉ
         *     `traceId` đi ra ngoài để đối chiếu với log.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/500",
                 *       "title": "Đã xảy ra lỗi không mong muốn",
                 *       "status": 500,
                 *       "instance": "/api/v1/posts",
                 *       "traceId": "b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description UUID v7 của người dùng. Sai dạng → 400. */
        UserId: string;
        /** @description UUID v7 của bài. Sai dạng → 400. */
        PostId: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Correlation ID của request, bằng đúng `traceId` trong Problem Details khi có lỗi.
         *     Client gửi header cùng tên thì server dùng lại giá trị đó.
         * @example 9f2c7b1e4a6d4f0b8c3e5a7d9b1f3c5e
         */
        XCorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createUploads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "purpose": "post",
                 *       "files": [
                 *         {
                 *           "contentType": "image/jpeg",
                 *           "sizeBytes": 1048576
                 *         },
                 *         {
                 *           "contentType": "image/png",
                 *           "sizeBytes": 204800
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["CreateUploadsRequest"];
            };
        };
        responses: {
            /** @description Một ticket cho mỗi file, **cùng thứ tự** với `files` gửi lên. */
            201: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example [
                     *       {
                     *         "mediaKey": "posts/0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10/01a0b811f70376b7812581bf3209feca.jpg",
                     *         "uploadUrl": "https://<account-id>.r2.cloudflarestorage.com/socialmedia-dev/posts/0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10/01a0b811f70376b7812581bf3209feca.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=600&X-Amz-SignedHeaders=content-length%3Bcontent-type%3Bhost&X-Amz-Signature=…",
                     *         "expiresIn": 600,
                     *         "requiredHeaders": {
                     *           "Content-Type": "image/jpeg",
                     *           "Content-Length": "1048576"
                     *         }
                     *       }
                     *     ]
                     */
                    "application/json": components["schemas"]["UploadTicket"][];
                };
            };
            /**
             * @description Loại ngoài allowlist, `sizeBytes` ngoài `1..10485760`, `files` rỗng hoặc quá 10, `purpose` không hợp lệ.
             *     `errors` theo `files` / `purpose`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/400",
                     *       "title": "Dữ liệu không hợp lệ",
                     *       "status": 400,
                     *       "detail": "Dữ liệu đầu vào không hợp lệ",
                     *       "instance": "/api/v1/media/uploads",
                     *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8",
                     *       "errors": {
                     *         "files": [
                     *           "Chỉ nhận ảnh JPEG, PNG hoặc WebP, tối đa 10 MB mỗi ảnh."
                     *         ]
                     *       }
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description `purpose=post` nhưng người gọi không có quyền `post.create` (Đ-2.6). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/403",
                     *       "title": "Bị từ chối",
                     *       "status": 403,
                     *       "detail": "Bạn không có quyền thực hiện thao tác này.",
                     *       "instance": "/api/v1/media/uploads",
                     *       "traceId": "c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    createPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            /** @description Bài đã tạo. */
            201: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            /** @description BR-01 hỏng, hoặc HEAD lệch khai báo / object chưa tải lên xong (Đ-2.8 lớp 2). `errors.body` hoặc `errors.mediaKeys`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/400",
                     *       "title": "Dữ liệu không hợp lệ",
                     *       "status": 400,
                     *       "detail": "Dữ liệu đầu vào không hợp lệ",
                     *       "instance": "/api/v1/posts",
                     *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8",
                     *       "errors": {
                     *         "body": [
                     *           "Bài đăng phải có nội dung hoặc ít nhất một ảnh."
                     *         ]
                     *       }
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Thiếu quyền `post.create`, chưa có hồ sơ (Đ-2.4), hoặc một `mediaKey` không thuộc tiền tố của người gọi (Đ-2.7) — cùng một phản hồi, không nêu lý do nào. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/403",
                     *       "title": "Bị từ chối",
                     *       "status": 403,
                     *       "detail": "Bạn không có quyền thực hiện thao tác này.",
                     *       "instance": "/api/v1/posts",
                     *       "traceId": "c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Một object trong `mediaKeys` đã được gắn vào bài khác (`storage_key` UNIQUE) — kể cả khi commit lại cùng lô (POST-08). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/409",
                     *       "title": "Xung đột dữ liệu",
                     *       "status": 409,
                     *       "detail": "Ảnh này đã được dùng trong một bài khác.",
                     *       "instance": "/api/v1/posts",
                     *       "traceId": "9f2c7b1e4a6d4f0b8c3e5a7d9b1f3c5e"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 của bài. Sai dạng → 400. */
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bài đọc được. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    deletePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 của bài. Sai dạng → 400. */
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã xóa mềm. */
            204: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    updatePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 của bài. Sai dạng → 400. */
                postId: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "body": "Chiều nay ở phố cổ — đã sửa.",
                 *       "privacy": "friends"
                 *     }
                 */
                "application/json": components["schemas"]["UpdatePostRequest"];
            };
        };
        responses: {
            /** @description Bài sau khi sửa, `editedAt` khác `null`. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["PostHidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    listUserPosts: {
        parameters: {
            query?: {
                /** @description `nextCursor` của trang trước. Bỏ trống để lấy trang đầu. */
                cursor?: string;
                /** @description Số bài mỗi trang, mặc định 20, tối đa 50 (AGENTS.md Mục 9). Ngoài `1..50` → 400 `errors.limit`. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description UUID v7 của người dùng. Sai dạng → 400. */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Một trang bài. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostPage"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getFeed: {
        parameters: {
            query?: {
                /** @description `nextCursor` của trang trước. Bỏ trống để lấy trang đầu. */
                cursor?: string;
                /** @description Số bài mỗi trang, mặc định 20, tối đa 50 (AGENTS.md Mục 9). Ngoài `1..50` → 400 `errors.limit`. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Một trang bảng tin. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "postId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *           "author": {
                     *             "userId": "0192f3c0-1b2d-7e4f-8a6c-9d0e1f2a3b4c",
                     *             "displayName": "Nguyễn Văn An",
                     *             "avatarUrl": null
                     *           },
                     *           "body": "Chiều nay trời đẹp quá.",
                     *           "privacy": "friends",
                     *           "media": [],
                     *           "commentCount": 0,
                     *           "reactionCounts": {},
                     *           "createdAt": "2026-09-23T08:15:00Z",
                     *           "editedAt": null,
                     *           "canEdit": false
                     *         }
                     *       ],
                     *       "nextCursor": "MjAyNi0wOS0yM1QwODoxNTowMC4wMDAwMDAwKzAwOjAwfDAxOTJmM2MxLThhNGUtN2MzMS05ZjJhLTZiNWQ0ZTNjMmExMA",
                     *       "mode": "network"
                     *     }
                     */
                    "application/json": components["schemas"]["FeedPage"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
