/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/{userId}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hồ sơ công khai của một người dùng
         * @description Hồ sơ là dữ liệu **công khai trong MVP** (Mục 6.1): ai đăng nhập cũng xem được, không có tầng 3.
         *
         *     **404** khi người dùng chưa onboarding — kể cả khi `userId` là một tài khoản có thật. FE dùng 404
         *     của `GET /users/me/profile`-tương-đương (gọi với chính `userId` của mình) để quyết định hiện màn
         *     `/onboarding` (E2).
         */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Onboarding hoặc sửa hồ sơ của chính mình (upsert)
         * @description Lần đầu gọi là **tạo** hồ sơ (bước onboarding, Đ-2.4); các lần sau là **sửa**. Cùng một mã 200
         *     cho cả hai — FE không cần biết đây là lần đầu hay không.
         *
         *     Trả nguyên `ProfileResponse` để FE không phải gọi lại `GET` (D2).
         *
         *     Validation (D2): `displayName` 2–50 ký tự **sau khi trim**, không rỗng; `bio` tối đa 500 ký tự,
         *     có thể bỏ trống hoặc `null` để xóa. Body chứa field lạ → 400 (`UnmappedMemberHandling = Disallow`).
         */
        put: operations["upsertMyProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Đặt ảnh đại diện từ một object đã tải lên R2
         * @description Luồng ba bước (SEQ-01 thu gọn cho avatar): `POST /media/uploads` với `purpose=avatar` (hợp đồng
         *     `content-v1`) → trình duyệt `PUT` thẳng lên `uploadUrl` với đúng `requiredHeaders` → gọi endpoint
         *     này với `mediaKey` nhận được.
         *
         *     Tầng 3 (D3, Đ-2.7 + Đ-2.8): `mediaKey` phải nằm dưới `avatars/{actorId}/` — của người khác → **403**;
         *     sai dạng → **400**; server `HEAD` object trên R2, object chưa có (client chưa `PUT` xong) hay loại
         *     không nằm trong allowlist → **400**. Object avatar cũ **không** bị xóa ở đây (Đ-2.10 — dọn trễ).
         */
        put: operations["setMyAvatar"];
        post?: never;
        /**
         * Gỡ ảnh đại diện
         * @description Chỉ gỡ liên kết (`avatar_key = NULL`), **không** xóa object trên R2 trong request (Đ-2.10). Gọi khi
         *     đang không có avatar vẫn trả 204 — idempotent.
         */
        delete: operations["removeMyAvatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tìm người theo tên — không dấu, tiền tố của từng từ
         * @description Gõ "nguyen" ra "Nguyễn Văn An", "van" cũng ra (tiền tố của từ thứ hai), "duc" ra "Đức". Không phân biệt hoa thường.
         *     `%`, `_`, `\` trong `q` hiểu theo **nghĩa đen**.
         *
         *     Xếp hạng: tên **bắt đầu** bằng từ khóa trước ("an" → "An Bình" trước "Bảo An"), rồi độ giống. Tối đa `limit` kết quả,
         *     **không** phân trang — cần hơn thì gõ thêm chữ. Tài khoản bị khóa hoặc đã xóa không xuất hiện.
         *
         *     FE gọi sau khi người dùng ngừng gõ (debounce) và chỉ khi `q` đã có ít nhất 2 ký tự.
         */
        get: operations["searchUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description RFC 7807 Problem Details — dạng lỗi duy nhất của toàn dự án. Sinh bởi
         *     `SocialApp.SharedKernel.Errors.GlobalExceptionHandler`; `traceId` và `type` gắn thống nhất
         *     trong `AddSharedKernel`.
         */
        ProblemDetails: {
            /**
             * Format: uri
             * @description Mặc định `https://httpstatuses.io/{status}`.
             */
            type?: string;
            /** @description Nhãn ngắn, ổn định theo loại lỗi. **Không** chứa dữ liệu người dùng. */
            title: string;
            /** Format: int32 */
            status: number;
            /** @description Thông điệp cho người đọc. Vắng mặt ở lỗi 500. */
            detail?: string | null;
            /** @description Path của request gây lỗi. */
            instance?: string;
            /** @description Bằng header `X-Correlation-ID` của chính request đó — dùng để tra log. */
            traceId: string;
            /** @description Chỉ có ở lỗi validation (400). Map `tên trường → danh sách thông điệp`. */
            errors?: {
                [key: string]: string[];
            } | null;
        };
        /** @description Hồ sơ trả về từ mọi endpoint của module — một hình dạng, không có bản rút gọn. */
        ProfileResponse: {
            /**
             * Format: uuid
             * @description Bằng `identity.users.user_id`.
             */
            userId: string;
            displayName: string;
            bio?: string | null;
            /**
             * Format: uri
             * @description Presigned GET **15 phút** (Đ-2.9), `null` khi chưa đặt avatar. Không bao giờ là `avatar_key`.
             *     Đừng lưu lâu hơn hạn — GĐ4 cache lưu key rồi ký lại lúc đọc.
             */
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @description Một người khớp từ khóa. Không có trạng thái quan hệ (bạn bè, đã mời…) — mở hồ sơ để biết. */
        SearchResult: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            /**
             * Format: uri
             * @description Presigned GET **15 phút** (Đ-2.9), `null` khi chưa đặt avatar.
             */
            avatarUrl: string | null;
        };
        SearchPage: {
            items: components["schemas"]["SearchResult"][];
        };
        UpsertProfileRequest: {
            /** @description Trim trước khi kiểm độ dài. Không được toàn khoảng trắng. */
            displayName: string;
            /** @description Bỏ trống hoặc `null` để xóa bio. */
            bio?: string | null;
        };
        SetAvatarRequest: {
            /**
             * @description Key do `POST /media/uploads` (`purpose=avatar`) cấp — dạng `avatars/{userId}/{uuid7}.{ext}`
             *     (Đ-2.7). Phải là của **chính** người gọi, nếu không → 403.
             */
            mediaKey: string;
        };
    };
    responses: {
        /**
         * @description Dữ liệu đầu vào không hợp lệ. `errors` là map `tên trường → danh sách thông điệp`.
         *
         *     Cũng là mã trả về khi body chứa **field lạ** (`UnmappedMemberHandling = Disallow`, AGENTS.md Mục 9)
         *     và khi tham số path/query sai dạng (`userId` không phải UUID).
         */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/400",
                 *       "title": "Dữ liệu không hợp lệ",
                 *       "status": 400,
                 *       "detail": "Dữ liệu đầu vào không hợp lệ",
                 *       "instance": "/api/v1/users/me/profile",
                 *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8",
                 *       "errors": {
                 *         "displayName": [
                 *           "Tên hiển thị phải có từ 2 đến 50 ký tự."
                 *         ]
                 *       }
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Thiếu access token, token sai chữ ký, hết hạn, hoặc đã bị thu hồi. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/401",
                 *       "title": "Chưa xác thực",
                 *       "status": 401,
                 *       "detail": "Yêu cầu access token hợp lệ.",
                 *       "instance": "/api/v1/users/me/profile",
                 *       "traceId": "a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Tầng 3 từ chối — ở module này có **hai** trường hợp, cùng một phản hồi: `mediaKey` nằm dưới tiền tố
         *     của **người khác** (Đ-2.7), hoặc **người gọi chưa có hồ sơ** (chốt Q-D9 — `PUT` phải trả một
         *     `ProfileResponse`, mà chưa onboarding thì không có gì để trả; nhất quán với Đ-2.4). Thông điệp cố ý
         *     không nêu key hay id nào, và hai trường hợp không phân biệt được từ ngoài.
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/403",
                 *       "title": "Bị từ chối",
                 *       "status": 403,
                 *       "detail": "Bạn không có quyền thực hiện thao tác này.",
                 *       "instance": "/api/v1/users/me/avatar",
                 *       "traceId": "c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4d6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Vượt hạn mức 100 req/phút/user (ISS-04). Không có `Retry-After`. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/429",
                 *       "title": "Quá nhiều yêu cầu",
                 *       "status": 429,
                 *       "detail": "Bạn đã gửi quá nhiều yêu cầu. Vui lòng thử lại sau ít phút.",
                 *       "instance": "/api/v1/users/me/profile",
                 *       "traceId": "e0b2d4f6a8c0e2b4d6f8a0c2e4b6d8f0"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /**
         * @description Lỗi không mong muốn. **Không bao giờ có `detail`** — `GlobalExceptionHandler` giấu chi tiết
         *     nội bộ, chỉ `traceId` đi ra ngoài để đối chiếu với log.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://httpstatuses.io/500",
                 *       "title": "Đã xảy ra lỗi không mong muốn",
                 *       "status": 500,
                 *       "instance": "/api/v1/users/me/profile",
                 *       "traceId": "b6d8f0a2c4e6b8d0f2a4c6e8b0d2f4a6"
                 *     }
                 */
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        /** @description UUID v7 của người dùng. Sai dạng → 400. */
        UserId: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Correlation ID của request, bằng đúng `traceId` trong Problem Details khi có lỗi.
         *     Client gửi header cùng tên thì server dùng lại giá trị đó.
         * @example 9f2c7b1e4a6d4f0b8c3e5a7d9b1f3c5e
         */
        XCorrelationId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID v7 của người dùng. Sai dạng → 400. */
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hồ sơ của người dùng. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *       "displayName": "An Nguyễn",
                     *       "bio": "Sinh viên năm 3, thích chụp ảnh phố.",
                     *       "avatarUrl": "https://<account-id>.r2.cloudflarestorage.com/socialmedia-dev/avatars/0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10/01a0b811f70376b7812581bf3209feca.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=…",
                     *       "createdAt": "2026-09-20T02:10:22Z",
                     *       "updatedAt": "2026-09-20T02:10:22Z"
                     *     }
                     */
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            /** @description Người dùng chưa có hồ sơ (chưa onboarding), hoặc không tồn tại — cùng một phản hồi. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/404",
                     *       "title": "Không tìm thấy tài nguyên",
                     *       "status": 404,
                     *       "detail": "Người dùng này chưa có hồ sơ.",
                     *       "instance": "/api/v1/users/0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10/profile",
                     *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8"
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    upsertMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertProfileRequest"];
            };
        };
        responses: {
            /** @description Hồ sơ sau khi tạo/sửa. */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    setMyAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "mediaKey": "avatars/0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10/01a0b811f70376b7812581bf3209feca.jpg"
                 *     }
                 */
                "application/json": components["schemas"]["SetAvatarRequest"];
            };
        };
        responses: {
            /** @description Hồ sơ với `avatarUrl` mới (presigned GET 15 phút). */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
            /**
             * @description `mediaKey` sai dạng, object chưa tồn tại trên R2, hoặc loại ảnh ngoài allowlist. `errors.mediaKey`
             *     nêu lý do.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/400",
                     *       "title": "Dữ liệu không hợp lệ",
                     *       "status": 400,
                     *       "detail": "Dữ liệu đầu vào không hợp lệ",
                     *       "instance": "/api/v1/users/me/avatar",
                     *       "traceId": "a4c6e8b0d2f4a6c8e0b2d4f6a8c0e2b4",
                     *       "errors": {
                     *         "mediaKey": [
                     *           "Ảnh chưa được tải lên xong. Hãy chờ tải lên hoàn tất rồi thử lại."
                     *         ]
                     *       }
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    removeMyAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Đã gỡ (hoặc vốn không có). */
            204: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    searchUsers: {
        parameters: {
            query: {
                /** @description Từ khóa, **sau khi bỏ khoảng trắng hai đầu** dài 2–50 ký tự. Ngắn/dài/thiếu → 400 `errors.q`. */
                q: string;
                /** @description Loại đối tượng tìm. Hiện chỉ `user` (mặc định). Giá trị khác → 400 `errors.type`. */
                type?: "user";
                /** @description Số kết quả tối đa, `1..20`. Ngoài khoảng → 400 `errors.limit`. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kết quả tốt nhất trước. Không khớp ai → `items` rỗng (không phải 404). */
            200: {
                headers: {
                    "X-Correlation-ID": components["headers"]["XCorrelationId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "items": [
                     *         {
                     *           "userId": "0192f3c1-8a4e-7c31-9f2a-6b5d4e3c2a10",
                     *           "displayName": "Nguyễn Văn An",
                     *           "avatarUrl": null
                     *         },
                     *         {
                     *           "userId": "0192f3c4-1b2c-7d3e-8f4a-5b6c7d8e9f01",
                     *           "displayName": "Trần Nguyên Khang",
                     *           "avatarUrl": null
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            /** @description Tham số sai — `errors` có key `q`, `type` hoặc `limit`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "https://httpstatuses.io/400",
                     *       "title": "Dữ liệu không hợp lệ",
                     *       "status": 400,
                     *       "detail": "Dữ liệu đầu vào không hợp lệ",
                     *       "instance": "/api/v1/search",
                     *       "traceId": "5e7a9c1b3d5f7092a4c6e8b0d2f4a6c8",
                     *       "errors": {
                     *         "q": [
                     *           "Nhập ít nhất 2 ký tự."
                     *         ]
                     *       }
                     *     }
                     */
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
}
